//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: Adapt_It.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_Adapt_It_H__
#define __WDR_Adapt_It_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "Adapt_It_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_STATICBITMAP = -1;
const int ID_TEXT = 0;
const int ID_ABOUT_VERSION_LABEL = 1;
const int ID_ABOUT_VERSION_NUM = 2;
const int ID_ABOUT_VERSION_DATE = 3;
const int ID_STATIC_UNICODE_OR_ANSI = 4;
const int ID_STATIC_WX_VERSION_USED = 5;
const int ID_LINE = 6;
const int ID_STATIC_UI_LANGUAGE = 7;
const int ID_STATIC_HOST_OS = 8;
const int ID_STATIC_SYS_LANGUAGE = 9;
const int ID_STATIC_SYS_LOCALE_NAME = 10;
const int ID_STATIC_CANONICAL_LOCALE_NAME = 11;
const int ID_STATIC_SYS_ENCODING_NAME = 12;
const int ID_STATIC_SYSTEM_LAYOUT_DIR = 13;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *ID_CONTROLBAR_1_LINE_SIZER;
const int IDC_RADIO_DRAFTING = 14;
const int IDC_RADIO_REVIEWING = 15;
const int IDC_CHECK_SINGLE_STEP = 16;
const int IDC_CHECK_KB_SAVE = 17;
const int IDC_CHECK_FORCE_ASK = 18;
const int IDC_BUTTON_NO_ADAPT = 19;
const int IDC_STATIC = 20;
const int IDC_EDIT_DELAY = 21;
const int IDC_CHECK_ISGLOSSING = 22;
wxSizer *ControlBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_COMPOSE = 23;
const int IDC_BUTTON_SHORTEN = 24;
const int IDC_BUTTON_PREV = 25;
const int IDC_BUTTON_LENGTHEN = 26;
const int IDC_BUTTON_NEXT = 27;
const int IDC_BUTTON_REMOVE = 28;
const int IDC_BUTTON_APPLY = 29;
const int IDC_STATIC_SECTION_DEF = 30;
const int IDC_RADIO_PUNCT_SECTION = 31;
const int IDC_RADIO_VERSE_SECTION = 32;
const int IDC_BUTTON_CLEAR = 33;
const int IDC_BUTTON_SELECT_ALL = 34;
wxSizer *ComposeBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LISTBOX_ADAPTIONS = 35;
wxSizer *OpenExistingProjectDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_FILENAME = 36;
const int ID_TEXT_INVALID_CHARACTERS = 37;
wxSizer *GetOutputFilenameDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SOURCE_LANGUAGE = 38;
const int ID_EDIT_SOURCE_LANG_CODE = 39;
const int IDC_TARGET_LANGUAGE = 40;
const int ID_EDIT_TARGET_LANG_CODE = 41;
const int ID_BUTTON_LOOKUP_CODES = 42;
wxSizer *LanguagesPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SOURCE_FONTNAME = 43;
const int IDC_CHECK_SRC_RTL = 44;
const int IDC_SOURCE_SIZE = 45;
const int IDC_SOURCE_LANG = 46;
const int IDC_BUTTON_SOURCE_COLOR = 47;
const int ID_BUTTON_CHANGE_SRC_ENCODING = 48;
const int IDC_TARGET_FONTNAME = 49;
const int IDC_CHECK_TGT_RTL = 50;
const int IDC_TARGET_SIZE = 51;
const int IDC_TARGET_LANG = 52;
const int IDC_BUTTON_TARGET_COLOR = 53;
const int ID_BUTTON_CHANGE_TGT_ENCODING = 54;
const int IDC_NAVTEXT_FONTNAME = 55;
const int IDC_CHECK_NAVTEXT_RTL = 56;
const int IDC_NAVTEXT_SIZE = 57;
const int IDC_CHANGE_NAV_TEXT = 58;
const int IDC_BUTTON_NAV_TEXT_COLOR = 59;
const int ID_BUTTON_CHANGE_NAV_ENCODING = 60;
const int ID_TEXTCTRL_AS_STATIC_FONTPAGE = 61;
const int IDC_BUTTON_SPECTEXTCOLOR = 62;
const int IDC_RETRANSLATION_BUTTON = 63;
const int ID_BUTTON_TEXT_DIFFS = 64;
wxSizer *FontsPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_PLEASE_WAIT = 65;
wxSizer *WaitDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_ACCEPTED = 66;
const int IDC_BUTTON_REJECT = 67;
const int IDC_BUTTON_ACCEPT = 68;
const int ID_BUTTON_REJECT_ALL_FILES = 69;
const int ID_BUTTON_ACCEPT_ALL_FILES = 70;
const int IDC_LIST_REJECTED = 71;
wxSizer *WhichFilesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES1 = 72;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES2 = 73;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES3 = 74;
wxSizer *TransformToGlossesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECK_SOURCE_USES_CAPS = 75;
const int ID_CHECK_USE_AUTO_CAPS = 76;
const int ID_TEXTCTRL_AS_CASE_PAGE_STATIC_TEXT = 77;
const int ID_TEXT_SL = 78;
const int ID_TEXT_TL = 79;
const int ID_TEXT_GL = 80;
const int IDC_EDIT_SRC_CASE_EQUIVALENCES = 81;
const int IDC_EDIT_TGT_CASE_EQUIVALENCES = 82;
const int IDC_EDIT_GLOSS_CASE_EQUIVALENCES = 83;
const int IDC_BUTTON_CLEAR_SRC_LIST = 84;
const int IDC_BUTTON_CLEAR_TGT_LIST = 85;
const int IDC_BUTTON_CLEAR_GLOSS_LIST = 86;
const int IDC_BUTTON_SRC_SET_ENGLISH = 87;
const int IDC_BUTTON_TGT_SET_ENGLISH = 88;
const int IDC_BUTTON_GLOSS_SET_ENGLISH = 89;
const int IDC_BUTTON_SRC_COPY_TO_NEXT = 90;
const int IDC_BUTTON_TGT_COPY_TO_NEXT = 91;
const int IDC_BUTTON_GLOSS_COPY_TO_NEXT = 92;
const int IDC_BUTTON_SRC_COPY_TO_GLOSS = 93;
wxSizer *CaseEquivDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_WELCOME_TO = 94;
const int IDC_EDIT_ADAPT_IT = 95;
const int ID_TEXTCTRL_AS_STATIC_WELCOME = 96;
const int IDC_CHECK_NOLONGER_SHOW = 97;
wxSizer *WelcomeDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_DOCPAGE = 98;
const int IDC_STATIC_WHICH_MODE = 99;
const int IDC_BUTTON_WHAT_IS_DOC = 100;
const int IDC_STATIC_WHICH_FOLDER = 101;
const int IDC_LIST_NEWDOC_AND_EXISTINGDOC = 102;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES = 103;
const int IDC_CHANGE_FOLDER_BTN = 104;
const int IDC_CHECK_FORCE_UTF8 = 105;
wxSizer *DocPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_PROJECTPAGE = 106;
const int IDC_BUTTON_WHAT_IS_PROJECT = 107;
const int IDC_LIST_NEW_AND_EXISTING = 108;
wxSizer *ProjectPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC = 109;
const int IDC_LIST_PUNCTS = 110;
const int ID_TEXTCTRL_AS_STATIC_PLACE_INT_PUNCT = 111;
const int IDC_EDIT_TGT = 112;
const int IDC_BUTTON_PLACE = 113;
wxSizer *PlaceInternalPunctDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_INCHES = 114;
const int IDC_RADIO_CM = 115;
wxSizer *UnitsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_MATCHED_SOURCE = 116;
const int IDC_MYLISTBOX_TRANSLATIONS = 117;
const int IDC_EDIT_REFERENCES = 118;
const int IDC_BUTTON_MOVE_UP = 119;
const int IDC_BUTTON_MOVE_DOWN = 120;
const int IDC_BUTTON_CANCEL_ASK = 121;
const int IDC_BUTTON_CANCEL_AND_SELECT = 122;
const int IDC_EDIT_NEW_TRANSLATION = 123;
wxSizer *ChooseTranslationDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_SRC = 124;
const int IDC_EDIT_PRECONTEXT = 125;
const int IDC_EDIT_SOURCE_TEXT = 126;
const int IDC_EDIT_RETRANSLATION = 127;
const int IDC_COPY_RETRANSLATION_TO_CLIPBOARD = 128;
const int IDC_BUTTON_TOGGLE = 129;
const int IDC_STATIC_TGT = 130;
const int IDC_EDIT_FOLLCONTEXT = 131;
wxSizer *RetranslationDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC_TEXT = 132;
const int IDC_EDIT_TGT_TEXT = 133;
const int IDC_SPIN_CHAPTER = 134;
const int IDC_SPIN_VERSE = 135;
const int IDC_GET_CHVERSE_TEXT = 136;
const int IDC_CLOSE_AND_JUMP = 137;
const int IDC_SHOW_MORE = 138;
const int IDC_SHOW_LESS = 139;
const int IDC_STATIC_BEGIN = 140;
const int IDC_STATIC_END = 141;
wxSizer *EarlierTransDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_CHECK_KB_BACKUP = 142;
const int IDC_CHECK_BAKUP_DOC = 143;
const int ID_TEXTCTRL_AS_STATIC_BACKUPS_AND_KB_PAGE = 144;
const int IDC_EDIT_SRC_NAME = 145;
const int IDC_EDIT_TGT_NAME = 146;
const int IDC_RADIO_ADAPT_BEFORE_GLOSS = 147;
const int IDC_RADIO_GLOSS_BEFORE_ADAPT = 148;
const int IDC_CHECK_LEGACY_SRC_TEXT_COPY = 149;
wxSizer *BackupsAndKBPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int STATIC_TEXT_V4 = 150;
const int IDC_EDIT_LEADING = 151;
const int STATIC_TEXT_V5 = 152;
const int IDC_EDIT_GAP_WIDTH = 153;
const int STATIC_TEXT_V6 = 154;
const int IDC_EDIT_LEFTMARGIN = 155;
const int STATIC_TEXT_V7 = 156;
const int IDC_EDIT_MULTIPLIER = 157;
const int IDC_EDIT_DIALOGFONTSIZE = 158;
const int IDC_CHECK_WELCOME_VISIBLE = 159;
const int IDC_CHECK_HIGHLIGHT_AUTO_INSERTED_TRANSLATIONS = 160;
const int ID_PANEL_AUTO_INSERT_COLOR = 161;
const int IDC_BUTTON_CHOOSE_HIGHLIGHT_COLOR = 162;
const int IDC_CHECK_SHOW_ADMIN_MENU = 163;
wxSizer *ViewPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *UnitsPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_AUTOSAVE = 164;
const int IDC_CHECK_NO_AUTOSAVE = 165;
const int IDC_RADIO_BY_MINUTES = 166;
const int IDC_EDIT_MINUTES = 167;
const int IDC_SPIN_MINUTES = 168;
const int IDC_RADIO_BY_MOVES = 169;
const int IDC_EDIT_MOVES = 170;
const int IDC_SPIN_MOVES = 171;
const int IDC_EDIT_KB_MINUTES = 172;
const int IDC_SPIN_KB_MINUTES = 173;
wxSizer *AutoSavingPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_DIV1 = 174;
const int IDC_RADIO_DIV2 = 175;
const int IDC_RADIO_DIV3 = 176;
const int IDC_RADIO_DIV4 = 177;
const int IDC_RADIO_DIV5 = 178;
const int IDC_COMBO_CHOOSE_BOOK = 179;
const int ID_TEXT_AS_STATIC = 180;
wxSizer *WhichBookDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_MSG = 181;
const int IDC_EDIT_ERR_XML = 182;
const int IDC_STATIC_LBL = 183;
const int IDC_EDIT_OFFSET = 184;
wxSizer *XMLErrorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_ED_SILCONVERTER_NAME = 185;
const int IDC_BTN_SELECT_SILCONVERTER = 186;
const int IDC_ED_SILCONVERTER_INFO = 187;
const int IDC_BTN_CLEAR_SILCONVERTER = 188;
wxSizer *SilConvertersDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_FOLDER_DOCS = 189;
const int IDC_LIST_FOLDER_DOCS = 190;
const int IDC_BUTTON_NEXT_CHAPTER = 191;
const int IDC_BUTTON_SPLIT_NOW = 192;
const int IDC_STATIC_SPLITTING_WAIT = 193;
const int IDC_RADIO_PHRASEBOX_LOCATION = 194;
const int IDC_RADIO_CHAPTER_SFMARKER = 195;
const int IDC_RADIO_DIVIDE_INTO_CHAPTERS = 196;
const int IDC_STATIC_SPLIT_NAME = 197;
const int IDC_EDIT1 = 198;
const int IDC_STATIC_REMAIN_NAME = 199;
const int IDC_EDIT2 = 200;
wxSizer *SplitDialogFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_MARKERS = 201;
const int IDC_TEXTCTRL_AS_STATIC_PLACE_INT_MKRS = 202;
wxSizer *PlaceInternalMarkersDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_NOTE = 203;
const int IDC_EDIT_FIND_TEXT = 204;
const int IDC_FIND_NEXT_BTN = 205;
const int IDC_LAST_BTN = 206;
const int IDC_NEXT_BTN = 207;
const int IDC_PREV_BTN = 208;
const int IDC_FIRST_BTN = 209;
const int IDC_DELETE_BTN = 210;
wxSizer *NoteDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_COLLECT_BT = 211;
const int IDC_RADIO_COLLECT_ADAPTATIONS = 212;
const int IDC_RADIO_COLLECT_GLOSSES = 213;
wxSizer *CollectBackTranslationsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SPIN_DELAY_TICKS = 214;
wxSizer *SetDelayDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_EXPORT_ALL = 215;
const int IDC_RADIO_EXPORT_SELECTED_MARKERS = 216;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_OPTIONS = 217;
const int IDC_LIST_SFMS = 218;
const int IDC_BUTTON_EXCLUDE_FROM_EXPORT = 219;
const int IDC_BUTTON_INCLUDE_IN_EXPORT = 220;
const int IDC_BUTTON_UNDO = 221;
const int IDC_STATIC_SPECIAL_NOTE = 222;
const int IDC_CHECK_PLACE_FREE_TRANS = 223;
const int IDC_CHECK_INTERLINEAR_PLACE_FREE_TRANS = 224;
const int IDC_CHECK_PLACE_BACK_TRANS = 225;
const int IDC_CHECK_INTERLINEAR_PLACE_BACK_TRANS = 226;
const int IDC_CHECK_PLACE_AI_NOTES = 227;
const int IDC_CHECK_INTERLINEAR_PLACE_AI_NOTES = 228;
wxSizer *ExportOptionsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_TITLE = 229;
const int IDC_RADIO_EXPORT_AS_SFM = 230;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_1 = 231;
const int IDC_RADIO_EXPORT_AS_RTF = 232;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_2 = 233;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_3 = 234;
const int IDC_BUTTON_EXPORT_FILTER_OPTIONS = 235;
wxSizer *ExportSaveAsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_CHECK_INCLUDE_NAV_TEXT = 236;
const int IDC_CHECK_INCLUDE_SOURCE_TEXT = 237;
const int IDC_CHECK_INCLUDE_TARGET_TEXT = 238;
const int IDC_CHECK_INCLUDE_GLS_TEXT = 239;
const int ID_TEXTCTRL_AS_STATIC_EXP_INTERLINEAR = 240;
const int IDC_RADIO_PORTRAIT = 241;
const int IDC_RADIO_LANDSCAPE = 242;
const int IDC_RADIO_OUTPUT_ALL = 243;
const int IDC_RADIO_OUTPUT_CHAPTER_VERSE_RANGE = 244;
const int IDC_EDIT_FROM_CHAPTER = 245;
const int IDC_EDIT_FROM_VERSE = 246;
const int IDC_EDIT_TO_CHAPTER = 247;
const int IDC_EDIT_TO_VERSE = 248;
const int IDC_RADIO_OUTPUT_PRELIM = 249;
const int IDC_RADIO_OUTPUT_FINAL = 250;
const int ID_CHECK_NEW_TABLES_FOR_NEWLINE_MARKERS = 251;
const int ID_CHECK_CENTER_TABLES_FOR_CENTERED_MARKERS = 252;
const int IDC_BUTTON_RTF_EXPORT_FILTER_OPTIONS = 253;
wxSizer *ExportInterlinearDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_MARKER = 254;
const int IDC_EDIT_MARKER_TEXT = 255;
const int IDC_REMOVE_BTN = 256;
const int IDC_BUTTON_SWITCH_ENCODING = 257;
const int IDC_LIST_MARKER_END = 258;
const int IDC_STATIC_MARKER_DESCRIPTION = 259;
const int IDC_STATIC_MARKER_STATUS = 260;
wxSizer *ViewFilteredMaterialDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_CHAPTER = 261;
const int IDC_EDIT_VERSE = 262;
wxSizer *GoToDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_MAIN_MSG = 263;
const int IDC_EDIT_KEY = 264;
extern wxSizer *m_topRightBoxLabel;
const int IDC_EDIT_ADAPTATION = 265;
const int IDC_RADIO_ACCEPT_HERE = 266;
const int ID_TEXT_NO_ADAPT_MSG = 267;
const int IDC_RADIO_CHANGE_INSTEAD = 268;
const int IDC_EDIT_CH_VERSE = 269;
const int ID_TEXT_AVAIL_ADAPT_OR_GLOSS = 270;
const int IDC_LIST_TRANSLATIONS = 271;
extern wxSizer *m_pNumberedPointsStaticBoxSizer;
const int ID_TEXT_CLICK_LISTED = 272;
const int ID_TEXT_CLICK_EDIT_LISTED = 273;
const int ID_TEXT_TYPE_NEW = 274;
const int IDC_CHECK_DO_SAME = 275;
wxSizer *ConsistencyCheckDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_CHECK_OPEN_DOC_ONLY = 276;
const int IDC_RADIO_CHECK_SELECTED_DOCS = 277;
const int ID_TEXTCTRL_MSG = 278;
wxSizer *ChooseConsistencyCheckTypeDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC0 = 279;
const int ID_TEXTCTRL = 280;
const int IDC_EDIT_OLD_SOURCE_TEXT = 281;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC1 = 282;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC2 = 283;
const int IDC_EDIT_NEW_SOURCE = 284;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC4 = 285;
wxSizer *EditSourceTextDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_UNPACK_WARN = 286;
wxSizer *UnpackWarningDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_COUNT = 287;
const int IDC_LIST_SRC_KEYS = 288;
const int IDC_LIST_EXISTING_TRANSLATIONS = 289;
const int IDC_EDIT_EDITORADD = 290;
const int IDC_BUTTON_UPDATE = 291;
const int IDC_BUTTON_ADD = 292;
const int IDC_ADD_NOTHING = 293;
const int IDC_EDIT_SHOW_FLAG = 294;
const int IDC_BUTTON_FLAG_TOGGLE = 295;
const int IDC_EDIT_SRC_KEY = 296;
const int IDC_EDIT_REF_COUNT = 297;
const int ID_TEXTCTRL_SEARCH = 298;
const int ID_BUTTON_GO = 299;
const int ID_BUTTON_ERASE_ALL_LINES = 300;
const int ID_COMBO_OLD_SEARCHES = 301;
wxSizer *KBEditorPanelFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATIC_TEXT_SELECT_A_TAB = 302;
const int ID_STATIC_WHICH_KB = 303;
const int ID_KB_EDITOR_NOTEBOOK = 304;
wxSizer *KBEditorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_DOCS_IN_FOLDER = 305;
const int IDC_LIST_SOURCE_FOLDER_DOCS = 306;
const int IDC_RADIO_TO_BOOK_FOLDER = 307;
const int IDC_RADIO_FROM_BOOK_FOLDER = 308;
const int IDC_VIEW_OTHER = 309;
const int IDC_BUTTON_RENAME_DOC = 310;
const int IDC_MOVE_NOW = 311;
wxSizer *MoveDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_JOIN1 = 312;
const int IDC_BUTTON_MOVE_ALL_RIGHT = 313;
const int IDC_BUTTON_MOVE_ALL_LEFT = 314;
const int ID_TEXTCTRL_AS_STATIC_JOIN2 = 315;
const int ID_TEXTCTRL_AS_STATIC_JOIN3 = 316;
const int ID_JOIN_NOW = 317;
const int IDC_STATIC_JOINING_WAIT = 318;
const int ID_TEXTCTRL_AS_STATIC_JOIN4 = 319;
const int IDC_EDIT_NEW_FILENAME = 320;
wxSizer *JoinDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *ListDocInOtherFolderDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATIC_SET_FONT_TITLE = 321;
const int ID_STATIC_CURR_ENCODING_IS = 322;
const int ID_TEXT_CURR_ENCODING = 323;
const int ID_LISTBOX_POSSIBLE_FACENAMES = 324;
const int ID_LISTBOX_POSSIBLE_ENCODINGS = 325;
extern wxSizer *pTestBoxStaticTextBoxSizer;
const int ID_TEXT_TEST_ENCODING_BOX = 326;
const int ID_BUTTON_CHART_FONT_SIZE_DECREASE = 327;
const int ID_BUTTON_CHART_FONT_SIZE_INCREASE = 328;
const int ID_STATIC_CHART_FONT_SIZE = 329;
const int ID_SCROLLED_ENCODING_WINDOW = 330;
wxSizer *SetEncodingDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_CCT = 331;
wxSizer *CCTableEditDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_CCTABLES = 332;
const int IDC_EDIT_SELECTED_TABLE = 333;
const int IDC_BUTTON_BROWSE = 334;
const int IDC_BUTTON_CREATE_CCT = 335;
const int IDC_BUTTON_EDIT_CCT = 336;
const int IDC_BUTTON_SELECT_NONE = 337;
const int IDC_EDIT_FOLDER_PATH = 338;
wxSizer *CCTablePageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_SRC_ONLY_FIND = 339;
const int IDC_RADIO_TGT_ONLY_FIND = 340;
const int IDC_RADIO_SRC_AND_TGT_FIND = 341;
const int IDC_CHECK_IGNORE_CASE_FIND = 342;
const int IDC_STATIC_SRC_FIND = 343;
const int IDC_EDIT_SRC_FIND = 344;
const int IDC_STATIC_TGT_FIND = 345;
const int IDC_EDIT_TGT_FIND = 346;
const int IDC_CHECK_INCLUDE_PUNCT_FIND = 347;
const int IDC_CHECK_SPAN_SRC_PHRASES_FIND = 348;
const int IDC_STATIC_SPECIAL = 349;
extern wxSizer *IDC_STATIC_SIZER_SPECIAL;
const int IDC_RADIO_RETRANSLATION = 350;
const int IDC_RADIO_NULL_SRC_PHRASE = 351;
const int IDC_RADIO_SFM = 352;
const int IDC_STATIC_SELECT_MKR = 353;
const int IDC_COMBO_SFM = 354;
const int IDC_BUTTON_SPECIAL = 355;
wxSizer *FindDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_SRC_ONLY_REPLACE = 356;
const int IDC_RADIO_TGT_ONLY_REPLACE = 357;
const int IDC_RADIO_SRC_AND_TGT_REPLACE = 358;
const int IDC_CHECK_IGNORE_CASE_REPLACE = 359;
const int IDC_STATIC_SRC_REPLACE = 360;
const int IDC_EDIT_SRC_REPLACE = 361;
const int IDC_STATIC_TGT_REPLACE = 362;
const int IDC_EDIT_TGT_REPLACE = 363;
const int IDC_CHECK_INCLUDE_PUNCT_REPLACE = 364;
const int IDC_CHECK_SPAN_SRC_PHRASES_REPLACE = 365;
const int IDC_STATIC_REPLACE = 366;
const int IDC_EDIT_REPLACE = 367;
const int IDC_REPLACE = 368;
const int IDC_REPLACE_ALL_BUTTON = 369;
wxSizer *ReplaceDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC = 370;
const int IDC_EDIT_TBLNAME = 371;
wxSizer *CCTableNameDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_EDIT_AS_STATIC = 372;
const int ID_CHECKBOX_INCLUDE_FREE_TRANS_TEXT = 373;
const int ID_CHECKBOX_INCLUDE_GLOSSES_TEXT = 374;
const int ID_RADIO_ALL = 375;
const int ID_RADIO_SELECTION = 376;
const int IDC_RADIO_PAGES = 377;
const int IDC_EDIT_PAGES_FROM = 378;
const int IDC_EDIT_PAGES_TO = 379;
const int IDC_RADIO_CHAPTER_VERSE_RANGE = 380;
const int IDC_EDIT3 = 381;
const int IDC_EDIT4 = 382;
const int IDC_CHECK_SUPPRESS_PREC_HEADING = 383;
const int IDC_CHECK_INCLUDE_FOLL_HEADING = 384;
const int IDC_CHECK_SUPPRESS_FOOTER = 385;
wxSizer *PrintOptionsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CC_TABBED_NOTEBOOK = 386;
wxSizer *CCTabbedNotebookFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LIST_UI_LANGUAGES = 387;
const int ID_TEXT_AS_STATIC_SHORT_LANG_NAME = 388;
const int ID_TEXT_AS_STATIC_LONG_LANG_NAME = 389;
const int IDC_LOCALIZATION_PATH = 390;
const int IDC_BTN_BROWSE_PATH = 391;
wxSizer *ChooseLanguageDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_COMBO_REMOVALS = 392;
const int ID_STATIC_TEXT_REMOVALS = 393;
const int IDC_BUTTON_UNDO_LAST_COPY = 394;
wxSizer *RemovalsBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_MSG_TEXT = 395;
const int IDC_BUTTON_PREV_STEP = 396;
const int IDC_BUTTON_NEXT_STEP = 397;
const int ID_BUTTON_END_NOW = 398;
const int ID_BUTTON_CANCEL_ALL_STEPS = 399;
wxSizer *VertEditBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_TITLE = 400;
const int ID_TEXTCTRL_AS_STATIC_PUNCT_CORRESP_PAGE = 401;
const int IDC_TOGGLE_UNNNN_BTN = 402;
const int ID_NOTEBOOK = 403;
wxSizer *PunctCorrespPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC0 = 404;
const int IDC_EDIT_TGT0 = 405;
const int IDC_EDIT_SRC9 = 406;
const int IDC_EDIT_TGT9 = 407;
const int IDC_EDIT_SRC18 = 408;
const int IDC_EDIT_TGT18 = 409;
const int IDC_EDIT_SRC1 = 410;
const int IDC_EDIT_TGT1 = 411;
const int IDC_EDIT_SRC10 = 412;
const int IDC_EDIT_TGT10 = 413;
const int IDC_EDIT_SRC19 = 414;
const int IDC_EDIT_TGT19 = 415;
const int IDC_EDIT_SRC2 = 416;
const int IDC_EDIT_TGT2 = 417;
const int IDC_EDIT_SRC11 = 418;
const int IDC_EDIT_TGT11 = 419;
const int IDC_EDIT_SRC20 = 420;
const int IDC_EDIT_TGT20 = 421;
const int IDC_EDIT_SRC3 = 422;
const int IDC_EDIT_TGT3 = 423;
const int IDC_EDIT_SRC12 = 424;
const int IDC_EDIT_TGT12 = 425;
const int IDC_EDIT_SRC21 = 426;
const int IDC_EDIT_TGT21 = 427;
const int IDC_EDIT_SRC4 = 428;
const int IDC_EDIT_TGT4 = 429;
const int IDC_EDIT_SRC13 = 430;
const int IDC_EDIT_TGT13 = 431;
const int IDC_EDIT_SRC22 = 432;
const int IDC_EDIT_TGT22 = 433;
const int IDC_EDIT_SRC5 = 434;
const int IDC_EDIT_TGT5 = 435;
const int IDC_EDIT_SRC14 = 436;
const int IDC_EDIT_TGT14 = 437;
const int IDC_EDIT_SRC23 = 438;
const int IDC_EDIT_TGT23 = 439;
const int IDC_EDIT_SRC6 = 440;
const int IDC_EDIT_TGT6 = 441;
const int IDC_EDIT_SRC15 = 442;
const int IDC_EDIT_TGT15 = 443;
const int IDC_EDIT_SRC24 = 444;
const int IDC_EDIT_TGT24 = 445;
const int IDC_EDIT_SRC7 = 446;
const int IDC_EDIT_TGT7 = 447;
const int IDC_EDIT_SRC16 = 448;
const int IDC_EDIT_TGT16 = 449;
const int IDC_EDIT_SRC25 = 450;
const int IDC_EDIT_TGT25 = 451;
const int IDC_EDIT_SRC8 = 452;
const int IDC_EDIT_TGT8 = 453;
const int IDC_EDIT_SRC17 = 454;
const int IDC_EDIT_TGT17 = 455;
wxSizer *SinglePunctTabPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_2SRC0 = 456;
const int IDC_EDIT_2TGT0 = 457;
const int IDC_EDIT_2SRC5 = 458;
const int IDC_EDIT_2TGT5 = 459;
const int IDC_EDIT_2SRC1 = 460;
const int IDC_EDIT_2TGT1 = 461;
const int IDC_EDIT_2SRC6 = 462;
const int IDC_EDIT_2TGT6 = 463;
const int IDC_EDIT_2SRC2 = 464;
const int IDC_EDIT_2TGT2 = 465;
const int IDC_EDIT_2SRC7 = 466;
const int IDC_EDIT_2TGT7 = 467;
const int IDC_EDIT_2SRC3 = 468;
const int IDC_EDIT_2TGT3 = 469;
const int IDC_EDIT_2SRC8 = 470;
const int IDC_EDIT_2TGT8 = 471;
const int IDC_EDIT_2SRC4 = 472;
const int IDC_EDIT_2TGT4 = 473;
const int IDC_EDIT_2SRC9 = 474;
const int IDC_EDIT_2TGT9 = 475;
wxSizer *DoublePunctTabPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_TOP;
extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_BOTTOM;
wxSizer *ControlBar2LineFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_MSG1 = 476;
const int ID_BUTTON_LOCATE_SOURCE_FOLDER = 477;
const int ID_BITMAPBUTTON_SRC_OPEN_FOLDER_UP = 478;
const int ID_TEXT_SOURCE_FOLDER_PATH = 479;
const int ID_TEXTCTRL_SOURCE_PATH = 480;
const int ID_LISTCTRL_SOURCE_CONTENTS = 481;
const int ID_BUTTON_LOCATE_DESTINATION_FOLDER = 482;
const int ID_BITMAPBUTTON_DEST_OPEN_FOLDER_UP = 483;
const int ID_TEXTCTRL_DESTINATION_PATH = 484;
const int ID_LISTCTRL_DESTINATION_CONTENTS = 485;
const int ID_BUTTON_MOVE = 486;
const int ID_BUTTON_COPY = 487;
const int ID_BUTTON_PEEK = 488;
const int ID_BUTTON_RENAME = 489;
const int ID_BUTTON_DELETE = 490;
wxSizer *MoveOrCopyFilesOrFoldersFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_MSG1 = 491;
const int ID_TEXTCTRL_SOURCE_FILE_DETAILS = 492;
const int ID_TEXTCTRL_DESTINATION_FILE_DETAILS = 493;
const int ID_RADIOBUTTON_REPLACE = 494;
const int ID_RADIOBUTTON_NO_COPY = 495;
const int ID_RADIOBUTTON_COPY_AND_RENAME = 496;
const int ID_TEXT_MODIFY_NAME = 497;
const int ID_CHECKBOX_HANDLE_SAME = 498;
wxSizer *FilenameConflictFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LISTBOX_UPDATED = 499;
const int ID_TEXTCTRL_INFO_SOURCE = 500;
const int ID_TEXTCTRL_INFO_REFS = 501;
const int ID_LISTBOX_MATCHED = 502;
const int ID_BUTTON_UPDATE = 503;
const int ID_TEXTCTRL_LOCAL_SEARCH = 504;
const int ID_BUTTON_FIND_NEXT = 505;
const int ID_TEXTCTRL_EDITBOX = 506;
const int ID_BUTTON_RESTORE = 507;
const int ID_BUTTON_REMOVE_UPDATE = 508;
wxSizer *KBEditSearchFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATICTEXT_SCROLL_LIST = 509;
const int ID_LIST_LANGUAGE_CODES_NAMES = 510;
const int ID_STATICTEXT_SEARCH_FOR_LANG_NAME = 511;
const int ID_TEXTCTRL_SEARCH_LANG_NAME = 512;
const int ID_BUTTON_USE_SEL_AS_SRC = 513;
const int ID_BUTTON_USE_SEL_AS_TGT = 514;
const int ID_SRC_LANGUAGE_CODE = 515;
const int ID_TEXTCTRL_SRC_LANG_CODE = 516;
const int ID_TGT_LANGUAGE_CODE = 517;
const int ID_TEXTCTRL_TGT_LANG_CODE = 518;
wxSizer *LanguageCodesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_PEEKMSG = 519;
extern wxSizer *m_pHorizBox_for_textctrl;
const int ID_TEXTCTRL_LINES100 = 520;
const int ID_BUTTON_TOGGLE_TEXT_DIRECTION = 521;
wxSizer *PeekAtFileFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_INSTRUCTIONS = 522;
const int ID_LISTBOX_LOADABLES_FILENAMES = 523;
wxSizer *NewDocFromSourceDataFolderFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATIC_SELECT_A_TAB = 524;
const int ID_MENU_EDITOR_NOTEBOOK = 525;
const int ID_RADIOBUTTON_NONE = 526;
const int ID_RADIOBUTTON_USE_PROFILE = 527;
const int ID_COMBO_PROFILE_ITEMS = 528;
const int ID_BUTTON_RESET_TO_FACTORY = 529;
const int ID_TEXT_STATIC_DESCRIPTION = 530;
const int ID_TEXTCTRL_PROFILE_DESCRIPTION = 531;
wxSizer *MenuEditorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKLISTBOX_MENU_ITEMS = 532;
wxSizer *MenuEditorPanelFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_USE_UBS_SET_ONLY = 533;
const int IDC_RADIO_USE_SILPNG_SET_ONLY = 534;
const int IDC_RADIO_USE_BOTH_SETS = 535;
const int IDC_RADIO_USE_UBS_SET_ONLY_PROJ = 536;
const int IDC_RADIO_USE_SILPNG_SET_ONLY_PROJ = 537;
const int IDC_RADIO_USE_BOTH_SETS_PROJ = 538;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES_USFM = 539;
const int ID_TEXTCTRL_AS_STATIC_FILTERPAGE = 540;
const int IDC_LIST_SFMS_PROJ = 541;
wxSizer *UsfmFilterPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECK_USE_GUESSER = 542;
const int ID_PANEL_GUESS_COLOR_DISPLAY = 543;
const int ID_BUTTON_GUESS_HIGHLIGHT_COLOR = 544;
const int ID_SLIDER_GUESSER = 545;
const int ID_CHECK_ALLOW_GUESSER_ON_UNCHANGED_CC_OUTPUT = 546;
const int ID_TEXT_STATIC_NUM_CORRESP_ADAPTATIONS_GUESSER = 547;
const int ID_TEXT_STATIC_NUM_CORRESP_GLOSSING_GUESSER = 548;
wxSizer *GuesserSettingsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_DEVS_EMAIL_ADDR = 549;
const int ID_TEXTCTRL_MY_EMAIL_ADDR = 550;
const int ID_TEXTCTRL_SUMMARY_SUBJECT = 551;
extern wxSizer *STATIC_TEXT_DESCRIPTION;
const int ID_TEXTCTRL_DESCRIPTION_BODY = 552;
const int ID_TEXTCTRL_SENDERS_NAME = 553;
const int ID_CHECKBOX_LET_DEVS_KNOW_AI_USAGE = 554;
const int ID_BUTTON_VIEW_USAGE_LOG = 555;
const int ID_TEXT_AI_VERSION = 556;
const int ID_TEXT_RELEASE_DATE = 557;
const int ID_TEXT_DATA_TYPE = 558;
const int ID_TEXT_FREE_MEMORY = 559;
const int ID_TEXT_SYS_LOCALE = 560;
const int ID_TEXT_INTERFACE_LANGUAGE = 561;
const int ID_TEXT_SYS_ENCODING = 562;
const int ID_TEXT_SYS_LAYOUT_DIR = 563;
const int ID_TEXT_WXWIDGETS_VERSION = 564;
const int ID_TEXT_OS_VERSION = 565;
const int ID_BUTTON_SAVE_REPORT_AS_TEXT_FILE = 566;
const int ID_BUTTON_LOAD_SAVED_REPORT = 567;
const int ID_RADIOBUTTON_SEND_DIRECTLY_FROM_AI = 568;
const int ID_RADIOBUTTON_SEND_TO_MY_EMAIL = 569;
const int ID_BUTTON_ATTACH_PACKED_DOC = 570;
const int ID_BUTTON_SEND_NOW = 571;
wxSizer *EmailReportDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_LOG_FILE_PATH_AND_NAME = 572;
const int ID_TEXTCTRL_LOGGED_TEXT = 573;
wxSizer *LogViewerFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_STATIC_LIST_OF_PROJECTS = 574;
const int IDC_LIST_OF_COLLAB_PROJECTS = 575;
const int ID_TEXTCTRL_AS_STATIC_TOP_NOTE = 576;
const int ID_LINE_1 = 577;
const int ID_TEXT_STATIC_SELECT_WHICH_PROJECTS = 578;
const int ID_TEXT_STATIC_SELECT_THIRD_PROJECT = 579;
const int ID_TEXT_STATIC_SRC_FROM_THIS_PROJECT = 580;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_SRC_PROJ = 581;
const int ID_BUTTON_SELECT_FROM_LIST_SOURCE_PROJ = 582;
const int ID_TEXT_STATIC_TARGET_TO_THIS_PROJECT = 583;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_TGT_PROJ = 584;
const int ID_BUTTON_SELECT_FROM_LIST_TARGET_PROJ = 585;
const int ID_TEXT_STATIC_TO_THIS_FT_PROJECT = 586;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_FREE_TRANS_PROJ = 587;
const int ID_BUTTON_SELECT_FROM_LIST_FREE_TRANS_PROJ = 588;
const int ID_BUTTON_NO_FREE_TRANS = 589;
const int ID_LINE_2 = 590;
const int ID_TEXT_STATIC_SELECT_SUITABLE_AI_PROJECT = 591;
const int ID_COMBO_AI_PROJECTS = 592;
const int ID_RADIOBOX_COLLABORATION_ON_OFF = 593;
extern wxSizer *pNewNamesSizer2;
const int ID_TEXT_ENTER_LANG_NAME = 594;
const int ID_TEXT_AS_STATIC_NEW_AI_PROJ_NAME = 595;
const int ID_TEXT_SRC_NAME_LABEL = 596;
const int ID_TEXTCTRL_SRC_LANG_NAME = 597;
const int ID_TEXT_TGT_NAME_LABEL = 598;
const int ID_TEXTCTRL_TGT_LANG_NAME = 599;
const int ID_TEXTCTRL_NEW_AI_PROJ_NAME = 600;
wxSizer *SetupEditorCollaborationFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_RADIOBOX_WHOLE_BOOK_OR_CHAPTER = 601;
const int ID_LISTBOX_BOOK_NAMES = 602;
const int ID_TEXT_SELECT_A_CHAPTER = 603;
const int ID_LISTCTRL_CHAPTER_NUMBER_AND_STATUS = 604;
const int ID_TEXTCTRL_AS_STATIC_NOTE = 605;
const int ID_BUTTON_CHANGE_PROJECTS = 606;
extern wxSizer *pProjectSelectionControlsSizer;
const int ID_TEXT_DO_NOT_CHANGE_NOTE = 607;
const int ID_COMBO_SOURCE_PROJECT_NAME = 608;
const int ID_COMBO_DESTINATION_PROJECT_NAME = 609;
const int ID_COMBO_FREE_TRANS_PROJECT_NAME = 610;
const int ID_TEXT_USE_DROP_DOWN = 611;
extern wxSizer *pNewNamesSizer;
const int ID_LINE_3 = 612;
wxSizer *GetSourceTextFromEditorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_TOP_INFO = 613;
const int ID_CHECKBOX_PROTECT_SOURCE_INPUTS = 614;
const int ID_BUTTON_PRE_LOAD_SOURCE_TEXTS = 615;
const int ID_CHECKBOX_PROTECT_FREETRANS_OUTPUTS = 616;
const int ID_CHECKBOX_PROTECT_FREETRANS_RTF_OUTPUTS = 617;
const int ID_CHECKBOX_PROTECT_GLOSS_OUTPUTS = 618;
const int ID_CHECKBOX_PROTECT_GLOSS_RTF_OUTPUTS = 619;
const int ID_CHECKBOX_PROTECT_SOURCE_OUTPUTS = 620;
const int ID_CHECKBOX_PROTECT_SOURCE_RTF_OUTPUTS = 621;
const int ID_CHECKBOX_PROTECT_TARGET_OUTPUTS = 622;
const int ID_CHECKBOX_PROTECT_TARGET_RTF_OUTPUTS = 623;
const int ID_CHECKBOX_PROTECT_REPORTS_OUTPUTS = 624;
const int ID_CHECKBOX_PROTECT_INTERLINEAR_RTF_OUTPUTS = 625;
const int ID_CHECKBOX_PROTECT_KB_INPUTS_AND_OUTPUTS = 626;
const int ID_CHECKBOX_PROTECT_LIFT_INPUTS_AND_OUTPUTS = 627;
const int ID_CHECKBOX_PROTECT_PACKED_INPUTS_AND_OUTPUTS = 628;
const int ID_CHECKBOX_PROTECT_CCTABLE_INPUTS_AND_OUTPUTS = 629;
const int ID_BUTTON_SELECT_ALL_CHECKBOXES = 630;
wxSizer *AssignLocationsForInputsOutputsFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_SOURCE_PHRASE_1 = 631;
const int ID_TEXT_EMPTY_STR = 632;
const int ID_RADIO_NO_ADAPTATION = 633;
const int ID_RADIO_LEAVE_HOLE = 634;
const int ID_RADIO_NOT_IN_KB = 635;
const int ID_CHECK_DO_SAME = 636;
wxSizer *ConsistencyCheck_EmptyNoTU_DlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_SOURCE_PHRASE_2 = 637;
const int ID_TEXTCTRL_TARGET_PHRASE_2 = 638;
const int ID_TEXT_EXISTS_STR = 639;
const int ID_RADIO_STORE_NORMALLY = 640;
const int ID_RADIO_NOT_IN_KB_LEAVEINDOC = 641;
const int ID_CHECK_DO_SAME2 = 642;
wxSizer *ConsistencyCheck_ExistsNoTU_DlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_FILE_MENU = 643;
const int ID_SAVE_AS = 644;
const int ID_FILE_PACK_DOC = 645;
const int ID_FILE_UNPACK_DOC = 646;
const int ID_MENU = 647;
const int ID_FILE_STARTUP_WIZARD = 648;
const int ID_FILE_CLOSEKB = 649;
const int ID_FILE_CHANGEFOLDER = 650;
const int ID_FILE_SAVEKB = 651;
const int ID_FILE_BACKUP_KB = 652;
const int ID_FILE_RESTORE_KB = 653;
const int ID_EDIT_MENU = 654;
const int ID_EDIT_CUT = 655;
const int ID_EDIT_COPY = 656;
const int ID_EDIT_PASTE = 657;
const int ID_GO_TO = 658;
const int ID_EDIT_SOURCE_TEXT = 659;
const int ID_EDIT_CONSISTENCY_CHECK = 660;
const int ID_EDIT_MOVE_NOTE_FORWARD = 661;
const int ID_EDIT_MOVE_NOTE_BACKWARD = 662;
const int ID_VIEW_MENU = 663;
const int ID_VIEW_TOOLBAR = 664;
const int ID_VIEW_STATUS_BAR = 665;
const int ID_VIEW_COMPOSE_BAR = 666;
const int ID_COPY_SOURCE = 667;
const int ID_MARKER_WRAPS_STRIP = 668;
const int ID_UNITS = 669;
const int ID_CHANGE_INTERFACE_LANGUAGE = 670;
const int ID_VIEW_SHOW_ADMIN_MENU = 671;
const int ID_TOOLS_MENU = 672;
const int ID_TOOLS_DEFINE_CC = 673;
const int ID_UNLOAD_CC_TABLES = 674;
const int ID_USE_CC = 675;
const int ID_ACCEPT_CHANGES = 676;
const int ID_TOOLS_DEFINE_SILCONVERTER = 677;
const int ID_USE_SILCONVERTER = 678;
const int ID_TOOLS_KB_EDITOR = 679;
const int ID_TOOLS_AUTO_CAPITALIZATION = 680;
const int ID_RETRANS_REPORT = 681;
const int ID_TOOLS_SPLIT_DOC = 682;
const int ID_TOOLS_JOIN_DOCS = 683;
const int ID_TOOLS_MOVE_DOC = 684;
const int ID_EXPORT_IMPORT_MENU = 685;
const int ID_FILE_EXPORT_SOURCE = 686;
const int ID_FILE_EXPORT = 687;
const int ID_FILE_EXPORT_TO_RTF = 688;
const int ID_EXPORT_GLOSSES = 689;
const int ID_EXPORT_FREE_TRANS = 690;
const int ID_FILE_EXPORT_KB = 691;
const int ID_IMPORT_TO_KB = 692;
const int ID_MENU_IMPORT_EDITED_SOURCE_TEXT = 693;
const int ID_ADVANCED_MENU = 694;
const int ID_ADVANCED_SEE_GLOSSES = 695;
const int ID_ADVANCED_GLOSSING_USES_NAV_FONT = 696;
const int ID_ADVANCED_TRANSFORM_ADAPTATIONS_INTO_GLOSSES = 697;
const int ID_ADVANCED_DELAY = 698;
const int ID_ADVANCED_BOOKMODE = 699;
const int ID_ADVANCED_FREE_TRANSLATION_MODE = 700;
const int ID_ADVANCED_TARGET_TEXT_IS_DEFAULT = 701;
const int ID_ADVANCED_GLOSS_TEXT_IS_DEFAULT = 702;
const int ID_ADVANCED_REMOVE_FILTERED_FREE_TRANSLATIONS = 703;
const int ID_ADVANCED_COLLECT_BACKTRANSLATIONS = 704;
const int ID_ADVANCED_REMOVE_FILTERED_BACKTRANSLATIONS = 705;
const int ID_ADVANCED_USETRANSLITERATIONMODE = 706;
const int ID_ADVANCED_SENDSYNCHRONIZEDSCROLLINGMESSAGES = 707;
const int ID_ADVANCED_RECEIVESYNCHRONIZEDSCROLLINGMESSAGES = 708;
const int ID_LAYOUT_MENU = 709;
const int ID_ALIGNMENT = 710;
const int ID_HELP_MENU = 711;
const int ID_ONLINE_HELP = 712;
const int ID_REPORT_A_PROBLEM = 713;
const int ID_GIVE_FEEDBACK = 714;
const int ID_HELP_USE_TOOLTIPS = 715;
const int ID_ADMINISTRATOR_MENU = 716;
const int ID_MENU_HELP_FOR_ADMINISTRATORS = 717;
const int ID_SETUP_EDITOR_COLLABORATION = 718;
const int ID_EDIT_USER_MENU_SETTINGS_PROFILE = 719;
const int ID_ASSIGN_LOCATIONS_FOR_INPUTS_OUTPUTS = 720;
const int ID_MOVE_OR_COPY_FOLDERS_OR_FILES = 721;
const int ID_SET_PASSWORD_MENU = 722;
const int ID_CUSTOM_WORK_FOLDER_LOCATION = 723;
const int ID_LOCK_CUSTOM_LOCATION = 724;
const int ID_UNLOCK_CUSTOM_LOCATION = 725;
const int ID_LOCAL_WORK_FOLDER_MENU = 726;
wxMenuBar *AIMenuBarFunc();

// Declare toolbar functions

const int ID_BUTTON_GUESSER = 727;
const int ID_BUTTON_CREATE_NOTE = 728;
const int ID_BUTTON_PREV_NOTE = 729;
const int ID_BUTTON_NEXT_NOTE = 730;
const int ID_BUTTON_DELETE_ALL_NOTES = 731;
const int ID_BUTTON_RESPECTING_BDRY = 732;
const int ID_BUTTON_SHOWING_PUNCT = 733;
const int ID_BUTTON_TO_END = 734;
const int ID_BUTTON_TO_START = 735;
const int ID_BUTTON_STEP_DOWN = 736;
const int ID_BUTTON_STEP_UP = 737;
const int ID_BUTTON_BACK = 738;
const int ID_BUTTON_MERGE = 739;
const int ID_BUTTON_RETRANSLATION = 740;
const int ID_BUTTON_EDIT_RETRANSLATION = 741;
const int ID_REMOVE_RETRANSLATION = 742;
const int ID_BUTTON_NULL_SRC = 743;
const int ID_BUTTON_REMOVE_NULL_SRCPHRASE = 744;
const int ID_BUTTON_CHOOSE_TRANSLATION = 745;
const int ID_SHOWING_ALL = 746;
const int ID_BUTTON_EARLIER_TRANSLATION = 747;
const int ID_BUTTON_NO_PUNCT_COPY = 748;
void AIToolBarFunc( wxToolBar *parent );

void AIToolBar32x30Func( wxToolBar *parent );

// Declare bitmap functions

wxBitmap AIToolBarBitmapsUnToggledFunc( size_t index );

const int ID_BITMAP_FOLDERAI = 749;
const int ID_BITMAP_FILEAI = 750;
const int ID_BITMAP_EMPTY_FOLDER = 751;
wxBitmap AIMainFrameIcons( size_t index );

const int ID_BUTTON_IGNORING_BDRY = 752;
const int ID_BUTTON_HIDING_PUNCT = 753;
const int ID_SHOWING_TGT = 754;
const int ID_BUTTON_ENABLE_PUNCT_COPY = 755;
wxBitmap AIToolBarBitmapsToggledFunc( size_t index );

wxBitmap WhichFilesBitmapsFunc( size_t index );

wxBitmap AIToolBarBitmapsToggled32x30Func( size_t index );

wxBitmap AIToolBarBitmapsUnToggled32x30Func( size_t index );

#endif

// End of generated file
