//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: Adapt_It.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_Adapt_It_H__
#define __WDR_Adapt_It_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "Adapt_It_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_STATICBITMAP = -1;
const int ID_TEXT = 0;
const int ID_ABOUT_VERSION_LABEL = 1;
const int ID_ABOUT_VERSION_NUM = 2;
const int ID_ABOUT_VERSION_DATE = 3;
const int ID_STATIC_UNICODE_OR_ANSI = 4;
const int ID_STATIC_WX_VERSION_USED = 5;
const int ID_LINE = 6;
const int ID_STATIC_UI_LANGUAGE = 7;
const int ID_STATIC_HOST_OS = 8;
const int ID_STATIC_SYS_LANGUAGE = 9;
const int ID_STATIC_SYS_LOCALE_NAME = 10;
const int ID_STATIC_CANONICAL_LOCALE_NAME = 11;
const int ID_STATIC_SYS_ENCODING_NAME = 12;
const int ID_STATIC_SYSTEM_LAYOUT_DIR = 13;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_DRAFTING = 14;
const int IDC_RADIO_REVIEWING = 15;
const int IDC_CHECK_SINGLE_STEP = 16;
const int IDC_CHECK_KB_SAVE = 17;
const int IDC_CHECK_FORCE_ASK = 18;
const int IDC_BUTTON_NO_ADAPT = 19;
const int IDC_STATIC = 20;
const int IDC_EDIT_DELAY = 21;
const int IDC_CHECK_ISGLOSSING = 22;
wxSizer *ControlBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_COMPOSE = 23;
const int IDC_BUTTON_SHORTEN = 24;
const int IDC_BUTTON_PREV = 25;
const int IDC_BUTTON_LENGTHEN = 26;
const int IDC_BUTTON_NEXT = 27;
const int IDC_BUTTON_REMOVE = 28;
const int IDC_BUTTON_APPLY = 29;
const int IDC_STATIC_SECTION_DEF = 30;
const int IDC_RADIO_PUNCT_SECTION = 31;
const int IDC_RADIO_VERSE_SECTION = 32;
const int IDC_BUTTON_CLEAR = 33;
const int IDC_BUTTON_SELECT_ALL = 34;
wxSizer *ComposeBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LISTBOX_ADAPTIONS = 35;
wxSizer *OpenExistingProjectDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_FILENAME = 36;
const int ID_TEXT_INVALID_CHARACTERS = 37;
wxSizer *GetOutputFilenameDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SOURCE_LANGUAGE = 38;
const int ID_EDIT_SOURCE_LANG_CODE = 39;
const int IDC_TARGET_LANGUAGE = 40;
const int ID_EDIT_TARGET_LANG_CODE = 41;
const int ID_BUTTON_LOOKUP_CODES = 42;
wxSizer *LanguagesPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SOURCE_FONTNAME = 43;
const int IDC_CHECK_SRC_RTL = 44;
const int IDC_SOURCE_SIZE = 45;
const int IDC_SOURCE_LANG = 46;
const int IDC_BUTTON_SOURCE_COLOR = 47;
const int ID_BUTTON_CHANGE_SRC_ENCODING = 48;
const int IDC_TARGET_FONTNAME = 49;
const int IDC_CHECK_TGT_RTL = 50;
const int IDC_TARGET_SIZE = 51;
const int IDC_TARGET_LANG = 52;
const int IDC_BUTTON_TARGET_COLOR = 53;
const int ID_BUTTON_CHANGE_TGT_ENCODING = 54;
const int IDC_NAVTEXT_FONTNAME = 55;
const int IDC_CHECK_NAVTEXT_RTL = 56;
const int IDC_NAVTEXT_SIZE = 57;
const int IDC_CHANGE_NAV_TEXT = 58;
const int IDC_BUTTON_NAV_TEXT_COLOR = 59;
const int ID_BUTTON_CHANGE_NAV_ENCODING = 60;
const int ID_TEXTCTRL_AS_STATIC_FONTPAGE = 61;
const int IDC_BUTTON_SPECTEXTCOLOR = 62;
const int IDC_RETRANSLATION_BUTTON = 63;
wxSizer *FontsPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_PLEASE_WAIT = 64;
wxSizer *WaitDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_ACCEPTED = 65;
const int IDC_BUTTON_REJECT = 66;
const int IDC_BUTTON_ACCEPT = 67;
const int IDC_LIST_REJECTED = 68;
wxSizer *WhichFilesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES1 = 69;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES2 = 70;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES3 = 71;
wxSizer *TransformToGlossesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECK_SOURCE_USES_CAPS = 72;
const int ID_CHECK_USE_AUTO_CAPS = 73;
const int ID_TEXTCTRL_AS_CASE_PAGE_STATIC_TEXT = 74;
const int ID_TEXT_SL = 75;
const int ID_TEXT_TL = 76;
const int ID_TEXT_GL = 77;
const int IDC_EDIT_SRC_CASE_EQUIVALENCES = 78;
const int IDC_EDIT_TGT_CASE_EQUIVALENCES = 79;
const int IDC_EDIT_GLOSS_CASE_EQUIVALENCES = 80;
const int IDC_BUTTON_CLEAR_SRC_LIST = 81;
const int IDC_BUTTON_CLEAR_TGT_LIST = 82;
const int IDC_BUTTON_CLEAR_GLOSS_LIST = 83;
const int IDC_BUTTON_SRC_SET_ENGLISH = 84;
const int IDC_BUTTON_TGT_SET_ENGLISH = 85;
const int IDC_BUTTON_GLOSS_SET_ENGLISH = 86;
const int IDC_BUTTON_SRC_COPY_TO_NEXT = 87;
const int IDC_BUTTON_TGT_COPY_TO_NEXT = 88;
const int IDC_BUTTON_GLOSS_COPY_TO_NEXT = 89;
const int IDC_BUTTON_SRC_COPY_TO_GLOSS = 90;
wxSizer *CaseEquivDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_WELCOME_TO = 91;
const int IDC_EDIT_ADAPT_IT = 92;
const int ID_TEXTCTRL_AS_STATIC_WELCOME = 93;
const int IDC_CHECK_NOLONGER_SHOW = 94;
wxSizer *WelcomeDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_DOCPAGE = 95;
const int IDC_STATIC_WHICH_MODE = 96;
const int IDC_BUTTON_WHAT_IS_DOC = 97;
const int IDC_STATIC_WHICH_FOLDER = 98;
const int IDC_LIST_NEWDOC_AND_EXISTINGDOC = 99;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES = 100;
const int IDC_CHANGE_FOLDER_BTN = 101;
const int IDC_CHECK_FORCE_UTF8 = 102;
wxSizer *DocPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_PROJECTPAGE = 103;
const int IDC_BUTTON_WHAT_IS_PROJECT = 104;
const int IDC_LIST_NEW_AND_EXISTING = 105;
wxSizer *ProjectPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC = 106;
const int IDC_LIST_PUNCTS = 107;
const int ID_TEXTCTRL_AS_STATIC_PLACE_INT_PUNCT = 108;
const int IDC_EDIT_TGT = 109;
const int IDC_BUTTON_PLACE = 110;
wxSizer *PlaceInternalPunctDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_INCHES = 111;
const int IDC_RADIO_CM = 112;
wxSizer *UnitsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_MATCHED_SOURCE = 113;
const int IDC_MYLISTBOX_TRANSLATIONS = 114;
const int IDC_EDIT_REFERENCES = 115;
const int IDC_BUTTON_MOVE_UP = 116;
const int IDC_BUTTON_MOVE_DOWN = 117;
const int IDC_BUTTON_CANCEL_ASK = 118;
const int IDC_BUTTON_CANCEL_AND_SELECT = 119;
const int IDC_EDIT_NEW_TRANSLATION = 120;
wxSizer *ChooseTranslationDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_SRC = 121;
const int IDC_EDIT_PRECONTEXT = 122;
const int IDC_EDIT_SOURCE_TEXT = 123;
const int IDC_EDIT_RETRANSLATION = 124;
const int IDC_COPY_RETRANSLATION_TO_CLIPBOARD = 125;
const int IDC_BUTTON_TOGGLE = 126;
const int IDC_STATIC_TGT = 127;
const int IDC_EDIT_FOLLCONTEXT = 128;
wxSizer *RetranslationDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC_TEXT = 129;
const int IDC_EDIT_TGT_TEXT = 130;
const int IDC_SPIN_CHAPTER = 131;
const int IDC_SPIN_VERSE = 132;
const int IDC_GET_CHVERSE_TEXT = 133;
const int IDC_CLOSE_AND_JUMP = 134;
const int IDC_SHOW_MORE = 135;
const int IDC_SHOW_LESS = 136;
const int IDC_STATIC_BEGIN = 137;
const int IDC_STATIC_END = 138;
wxSizer *EarlierTransDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_CHECK_KB_BACKUP = 139;
const int IDC_CHECK_BAKUP_DOC = 140;
const int ID_TEXTCTRL_AS_STATIC_BACKUPS_AND_KB_PAGE = 141;
const int IDC_EDIT_SRC_NAME = 142;
const int IDC_EDIT_TGT_NAME = 143;
const int IDC_RADIO_ADAPT_BEFORE_GLOSS = 144;
const int IDC_RADIO_GLOSS_BEFORE_ADAPT = 145;
const int IDC_CHECK_LEGACY_SRC_TEXT_COPY = 146;
wxSizer *BackupsAndKBPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int STATIC_TEXT_V4 = 147;
const int IDC_EDIT_LEADING = 148;
const int STATIC_TEXT_V5 = 149;
const int IDC_EDIT_GAP_WIDTH = 150;
const int STATIC_TEXT_V6 = 151;
const int IDC_EDIT_LEFTMARGIN = 152;
const int STATIC_TEXT_V7 = 153;
const int IDC_EDIT_MULTIPLIER = 154;
const int IDC_EDIT_DIALOGFONTSIZE = 155;
const int IDC_CHECK_WELCOME_VISIBLE = 156;
const int IDC_CHECK_HIGHLIGHT_AUTO_INSERTED_TRANSLATIONS = 157;
const int IDC_BUTTON_CHOOSE_HIGHLIGHT_COLOR = 158;
const int IDC_CHECK_SHOW_ADMIN_MENU = 159;
wxSizer *ViewPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *UnitsPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_AUTOSAVE = 160;
const int IDC_CHECK_NO_AUTOSAVE = 161;
const int IDC_RADIO_BY_MINUTES = 162;
const int IDC_EDIT_MINUTES = 163;
const int IDC_SPIN_MINUTES = 164;
const int IDC_RADIO_BY_MOVES = 165;
const int IDC_EDIT_MOVES = 166;
const int IDC_SPIN_MOVES = 167;
const int IDC_EDIT_KB_MINUTES = 168;
const int IDC_SPIN_KB_MINUTES = 169;
wxSizer *AutoSavingPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_DIV1 = 170;
const int IDC_RADIO_DIV2 = 171;
const int IDC_RADIO_DIV3 = 172;
const int IDC_RADIO_DIV4 = 173;
const int IDC_RADIO_DIV5 = 174;
const int IDC_COMBO_CHOOSE_BOOK = 175;
const int ID_TEXT_AS_STATIC = 176;
wxSizer *WhichBookDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_MSG = 177;
const int IDC_EDIT_ERR_XML = 178;
const int IDC_STATIC_LBL = 179;
const int IDC_EDIT_OFFSET = 180;
wxSizer *XMLErrorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_USFMPAGE = 181;
const int IDC_RADIO_USE_UBS_SET_ONLY = 182;
const int IDC_RADIO_USE_SILPNG_SET_ONLY = 183;
const int IDC_RADIO_USE_BOTH_SETS = 184;
const int IDC_RADIO_USE_UBS_SET_ONLY_PROJ = 185;
const int IDC_RADIO_USE_SILPNG_SET_ONLY_PROJ = 186;
const int IDC_RADIO_USE_BOTH_SETS_PROJ = 187;
const int IDC_RADIO_USE_UBS_SET_ONLY_FACTORY = 188;
const int IDC_RADIO_USE_SILPNG_SET_ONLY_FACTORY = 189;
const int IDC_RADIO_USE_BOTH_SETS_FACTORY = 190;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES_USFM = 191;
wxSizer *USFMPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_FILTERPAGE = 192;
const int IDC_LIST_SFMS = 193;
const int IDC_LIST_SFMS_PROJ = 194;
const int IDC_LIST_SFMS_FACTORY = 195;
wxSizer *FilterPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_ED_SILCONVERTER_NAME = 196;
const int IDC_BTN_SELECT_SILCONVERTER = 197;
const int IDC_ED_SILCONVERTER_INFO = 198;
const int IDC_BTN_CLEAR_SILCONVERTER = 199;
wxSizer *SilConvertersDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_FOLDER_DOCS = 200;
const int IDC_LIST_FOLDER_DOCS = 201;
const int IDC_BUTTON_NEXT_CHAPTER = 202;
const int IDC_BUTTON_SPLIT_NOW = 203;
const int IDC_STATIC_SPLITTING_WAIT = 204;
const int IDC_RADIO_PHRASEBOX_LOCATION = 205;
const int IDC_RADIO_CHAPTER_SFMARKER = 206;
const int IDC_RADIO_DIVIDE_INTO_CHAPTERS = 207;
const int IDC_STATIC_SPLIT_NAME = 208;
const int IDC_EDIT1 = 209;
const int IDC_STATIC_REMAIN_NAME = 210;
const int IDC_EDIT2 = 211;
wxSizer *SplitDialogFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_MARKERS = 212;
const int IDC_TEXTCTRL_AS_STATIC_PLACE_INT_MKRS = 213;
wxSizer *PlaceInternalMarkersDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_NOTE = 214;
const int IDC_EDIT_FIND_TEXT = 215;
const int IDC_FIND_NEXT_BTN = 216;
const int IDC_LAST_BTN = 217;
const int IDC_NEXT_BTN = 218;
const int IDC_PREV_BTN = 219;
const int IDC_FIRST_BTN = 220;
const int IDC_DELETE_BTN = 221;
wxSizer *NoteDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_COLLECT_BT = 222;
const int IDC_RADIO_COLLECT_ADAPTATIONS = 223;
const int IDC_RADIO_COLLECT_GLOSSES = 224;
wxSizer *CollectBackTranslationsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_SPIN_DELAY_TICKS = 225;
wxSizer *SetDelayDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_EXPORT_ALL = 226;
const int IDC_RADIO_EXPORT_SELECTED_MARKERS = 227;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_OPTIONS = 228;
const int IDC_BUTTON_EXCLUDE_FROM_EXPORT = 229;
const int IDC_BUTTON_INCLUDE_IN_EXPORT = 230;
const int IDC_BUTTON_UNDO = 231;
const int IDC_STATIC_SPECIAL_NOTE = 232;
const int IDC_CHECK_PLACE_FREE_TRANS = 233;
const int IDC_CHECK_INTERLINEAR_PLACE_FREE_TRANS = 234;
const int IDC_CHECK_PLACE_BACK_TRANS = 235;
const int IDC_CHECK_INTERLINEAR_PLACE_BACK_TRANS = 236;
const int IDC_CHECK_PLACE_AI_NOTES = 237;
const int IDC_CHECK_INTERLINEAR_PLACE_AI_NOTES = 238;
wxSizer *ExportOptionsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_TITLE = 239;
const int IDC_RADIO_EXPORT_AS_SFM = 240;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_1 = 241;
const int IDC_RADIO_EXPORT_AS_RTF = 242;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_2 = 243;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_SAVE_AS_3 = 244;
const int IDC_BUTTON_EXPORT_FILTER_OPTIONS = 245;
wxSizer *ExportSaveAsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_CHECK_INCLUDE_NAV_TEXT = 246;
const int IDC_CHECK_INCLUDE_SOURCE_TEXT = 247;
const int IDC_CHECK_INCLUDE_TARGET_TEXT = 248;
const int IDC_CHECK_INCLUDE_GLS_TEXT = 249;
const int ID_TEXTCTRL_AS_STATIC_EXP_INTERLINEAR = 250;
const int IDC_RADIO_PORTRAIT = 251;
const int IDC_RADIO_LANDSCAPE = 252;
const int IDC_RADIO_OUTPUT_ALL = 253;
const int IDC_RADIO_OUTPUT_CHAPTER_VERSE_RANGE = 254;
const int IDC_EDIT_FROM_CHAPTER = 255;
const int IDC_EDIT_FROM_VERSE = 256;
const int IDC_EDIT_TO_CHAPTER = 257;
const int IDC_EDIT_TO_VERSE = 258;
const int IDC_RADIO_OUTPUT_PRELIM = 259;
const int IDC_RADIO_OUTPUT_FINAL = 260;
const int ID_CHECK_NEW_TABLES_FOR_NEWLINE_MARKERS = 261;
const int ID_CHECK_CENTER_TABLES_FOR_CENTERED_MARKERS = 262;
const int IDC_BUTTON_RTF_EXPORT_FILTER_OPTIONS = 263;
wxSizer *ExportInterlinearDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_MARKER = 264;
const int IDC_EDIT_MARKER_TEXT = 265;
const int IDC_REMOVE_BTN = 266;
const int IDC_BUTTON_SWITCH_ENCODING = 267;
const int IDC_LIST_MARKER_END = 268;
const int IDC_STATIC_MARKER_DESCRIPTION = 269;
const int IDC_STATIC_MARKER_STATUS = 270;
wxSizer *ViewFilteredMaterialDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_CHAPTER = 271;
const int IDC_EDIT_VERSE = 272;
wxSizer *GoToDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_KEY = 273;
const int IDC_EDIT_CH_VERSE = 274;
const int IDC_EDIT_ADAPTATION = 275;
const int IDC_LIST_TRANSLATIONS = 276;
const int IDC_RADIO_LIST_SELECT = 277;
const int IDC_RADIO_ACCEPT_CURRENT = 278;
const int IDC_RADIO_TYPE_NEW = 279;
const int IDC_EDIT_TYPE_NEW = 280;
const int IDC_NOTHING = 281;
const int IDC_BUTTON_IGNORE_IT = 282;
const int IDC_CHECK_DO_SAME = 283;
wxSizer *ConsistencyCheckDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_CHECK_OPEN_DOC_ONLY = 284;
const int IDC_RADIO_CHECK_SELECTED_DOCS = 285;
const int ID_TEXTCTRL_AS_STATIC_CHOOSE_CONSISTENCY_CHECK_TYPE = 286;
const int ID_TEXTCTRL_MSG_TWO = 287;
wxSizer *ChooseConsistencyCheckTypeDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC0 = 288;
const int ID_TEXTCTRL = 289;
const int IDC_EDIT_OLD_SOURCE_TEXT = 290;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC1 = 291;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC2 = 292;
const int IDC_EDIT_NEW_SOURCE = 293;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC4 = 294;
wxSizer *EditSourceTextDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_UNPACK_WARN = 295;
wxSizer *UnpackWarningDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_COUNT = 296;
const int IDC_LIST_SRC_KEYS = 297;
const int IDC_LIST_EXISTING_TRANSLATIONS = 298;
const int IDC_EDIT_EDITORADD = 299;
const int IDC_BUTTON_UPDATE = 300;
const int IDC_BUTTON_ADD = 301;
const int IDC_ADD_NOTHING = 302;
const int IDC_EDIT_SHOW_FLAG = 303;
const int IDC_BUTTON_FLAG_TOGGLE = 304;
const int IDC_EDIT_SRC_KEY = 305;
const int IDC_EDIT_REF_COUNT = 306;
const int ID_TEXTCTRL_SEARCH = 307;
const int ID_BUTTON_GO = 308;
const int ID_BUTTON_ERASE_ALL_LINES = 309;
const int ID_COMBO_OLD_SEARCHES = 310;
wxSizer *KBEditorPanelFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATIC_TEXT_SELECT_A_TAB = 311;
const int ID_KB_EDITOR_NOTEBOOK = 312;
wxSizer *KBEditorDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_STATIC_DOCS_IN_FOLDER = 313;
const int IDC_LIST_SOURCE_FOLDER_DOCS = 314;
const int IDC_RADIO_TO_BOOK_FOLDER = 315;
const int IDC_RADIO_FROM_BOOK_FOLDER = 316;
const int IDC_VIEW_OTHER = 317;
const int IDC_BUTTON_RENAME_DOC = 318;
const int IDC_MOVE_NOW = 319;
wxSizer *MoveDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC_JOIN1 = 320;
const int IDC_BUTTON_MOVE_ALL_RIGHT = 321;
const int IDC_BUTTON_MOVE_ALL_LEFT = 322;
const int ID_TEXTCTRL_AS_STATIC_JOIN2 = 323;
const int ID_TEXTCTRL_AS_STATIC_JOIN3 = 324;
const int ID_JOIN_NOW = 325;
const int IDC_STATIC_JOINING_WAIT = 326;
const int ID_TEXTCTRL_AS_STATIC_JOIN4 = 327;
const int IDC_EDIT_NEW_FILENAME = 328;
wxSizer *JoinDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *ListDocInOtherFolderDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATIC_SET_FONT_TITLE = 329;
const int ID_STATIC_CURR_ENCODING_IS = 330;
const int ID_TEXT_CURR_ENCODING = 331;
const int ID_LISTBOX_POSSIBLE_FACENAMES = 332;
const int ID_LISTBOX_POSSIBLE_ENCODINGS = 333;
extern wxSizer *pTestBoxStaticTextBoxSizer;
const int ID_TEXT_TEST_ENCODING_BOX = 334;
const int ID_BUTTON_CHART_FONT_SIZE_DECREASE = 335;
const int ID_BUTTON_CHART_FONT_SIZE_INCREASE = 336;
const int ID_STATIC_CHART_FONT_SIZE = 337;
const int ID_SCROLLED_ENCODING_WINDOW = 338;
wxSizer *SetEncodingDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_CCT = 339;
wxSizer *CCTableEditDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_LIST_CCTABLES = 340;
const int IDC_EDIT_SELECTED_TABLE = 341;
const int IDC_BUTTON_BROWSE = 342;
const int IDC_BUTTON_CREATE_CCT = 343;
const int IDC_BUTTON_EDIT_CCT = 344;
const int IDC_BUTTON_SELECT_NONE = 345;
const int IDC_EDIT_FOLDER_PATH = 346;
wxSizer *CCTablePageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_SRC_ONLY_FIND = 347;
const int IDC_RADIO_TGT_ONLY_FIND = 348;
const int IDC_RADIO_SRC_AND_TGT_FIND = 349;
const int IDC_CHECK_IGNORE_CASE_FIND = 350;
const int IDC_STATIC_SRC_FIND = 351;
const int IDC_EDIT_SRC_FIND = 352;
const int IDC_STATIC_TGT_FIND = 353;
const int IDC_EDIT_TGT_FIND = 354;
const int IDC_CHECK_INCLUDE_PUNCT_FIND = 355;
const int IDC_CHECK_SPAN_SRC_PHRASES_FIND = 356;
const int IDC_STATIC_SPECIAL = 357;
extern wxSizer *IDC_STATIC_SIZER_SPECIAL;
const int IDC_RADIO_RETRANSLATION = 358;
const int IDC_RADIO_NULL_SRC_PHRASE = 359;
const int IDC_RADIO_SFM = 360;
const int IDC_STATIC_SELECT_MKR = 361;
const int IDC_COMBO_SFM = 362;
const int IDC_BUTTON_SPECIAL = 363;
wxSizer *FindDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_RADIO_SRC_ONLY_REPLACE = 364;
const int IDC_RADIO_TGT_ONLY_REPLACE = 365;
const int IDC_RADIO_SRC_AND_TGT_REPLACE = 366;
const int IDC_CHECK_IGNORE_CASE_REPLACE = 367;
const int IDC_STATIC_SRC_REPLACE = 368;
const int IDC_EDIT_SRC_REPLACE = 369;
const int IDC_STATIC_TGT_REPLACE = 370;
const int IDC_EDIT_TGT_REPLACE = 371;
const int IDC_CHECK_INCLUDE_PUNCT_REPLACE = 372;
const int IDC_CHECK_SPAN_SRC_PHRASES_REPLACE = 373;
const int IDC_STATIC_REPLACE = 374;
const int IDC_EDIT_REPLACE = 375;
const int IDC_REPLACE = 376;
const int IDC_REPLACE_ALL_BUTTON = 377;
wxSizer *ReplaceDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_AS_STATIC = 378;
const int IDC_EDIT_TBLNAME = 379;
wxSizer *CCTableNameDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_EDIT_AS_STATIC = 380;
const int ID_RADIO_ALL = 381;
const int ID_RADIO_SELECTION = 382;
const int IDC_RADIO_PAGES = 383;
const int IDC_EDIT_PAGES_FROM = 384;
const int IDC_EDIT_PAGES_TO = 385;
const int IDC_RADIO_CHAPTER_VERSE_RANGE = 386;
const int IDC_EDIT3 = 387;
const int IDC_EDIT4 = 388;
const int IDC_CHECK_SUPPRESS_PREC_HEADING = 389;
const int IDC_CHECK_INCLUDE_FOLL_HEADING = 390;
const int IDC_CHECK_SUPPRESS_FOOTER = 391;
wxSizer *PrintOptionsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CC_TABBED_NOTEBOOK = 392;
wxSizer *CCTabbedNotebookFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LIST_UI_LANGUAGES = 393;
const int ID_TEXT_AS_STATIC_SHORT_LANG_NAME = 394;
const int ID_TEXT_AS_STATIC_LONG_LANG_NAME = 395;
const int IDC_LOCALIZATION_PATH = 396;
const int IDC_BTN_BROWSE_PATH = 397;
wxSizer *ChooseLanguageDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_COMBO_REMOVALS = 398;
const int ID_STATIC_TEXT_REMOVALS = 399;
const int IDC_BUTTON_UNDO_LAST_COPY = 400;
wxSizer *RemovalsBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_MSG_TEXT = 401;
const int IDC_BUTTON_PREV_STEP = 402;
const int IDC_BUTTON_NEXT_STEP = 403;
const int ID_BUTTON_END_NOW = 404;
const int ID_BUTTON_CANCEL_ALL_STEPS = 405;
wxSizer *VertEditBarFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_TITLE = 406;
const int ID_TEXTCTRL_AS_STATIC_PUNCT_CORRESP_PAGE = 407;
const int IDC_TOGGLE_UNNNN_BTN = 408;
const int ID_NOTEBOOK = 409;
wxSizer *PunctCorrespPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_SRC0 = 410;
const int IDC_EDIT_TGT0 = 411;
const int IDC_EDIT_SRC9 = 412;
const int IDC_EDIT_TGT9 = 413;
const int IDC_EDIT_SRC18 = 414;
const int IDC_EDIT_TGT18 = 415;
const int IDC_EDIT_SRC1 = 416;
const int IDC_EDIT_TGT1 = 417;
const int IDC_EDIT_SRC10 = 418;
const int IDC_EDIT_TGT10 = 419;
const int IDC_EDIT_SRC19 = 420;
const int IDC_EDIT_TGT19 = 421;
const int IDC_EDIT_SRC2 = 422;
const int IDC_EDIT_TGT2 = 423;
const int IDC_EDIT_SRC11 = 424;
const int IDC_EDIT_TGT11 = 425;
const int IDC_EDIT_SRC20 = 426;
const int IDC_EDIT_TGT20 = 427;
const int IDC_EDIT_SRC3 = 428;
const int IDC_EDIT_TGT3 = 429;
const int IDC_EDIT_SRC12 = 430;
const int IDC_EDIT_TGT12 = 431;
const int IDC_EDIT_SRC21 = 432;
const int IDC_EDIT_TGT21 = 433;
const int IDC_EDIT_SRC4 = 434;
const int IDC_EDIT_TGT4 = 435;
const int IDC_EDIT_SRC13 = 436;
const int IDC_EDIT_TGT13 = 437;
const int IDC_EDIT_SRC22 = 438;
const int IDC_EDIT_TGT22 = 439;
const int IDC_EDIT_SRC5 = 440;
const int IDC_EDIT_TGT5 = 441;
const int IDC_EDIT_SRC14 = 442;
const int IDC_EDIT_TGT14 = 443;
const int IDC_EDIT_SRC23 = 444;
const int IDC_EDIT_TGT23 = 445;
const int IDC_EDIT_SRC6 = 446;
const int IDC_EDIT_TGT6 = 447;
const int IDC_EDIT_SRC15 = 448;
const int IDC_EDIT_TGT15 = 449;
const int IDC_EDIT_SRC24 = 450;
const int IDC_EDIT_TGT24 = 451;
const int IDC_EDIT_SRC7 = 452;
const int IDC_EDIT_TGT7 = 453;
const int IDC_EDIT_SRC16 = 454;
const int IDC_EDIT_TGT16 = 455;
const int IDC_EDIT_SRC25 = 456;
const int IDC_EDIT_TGT25 = 457;
const int IDC_EDIT_SRC8 = 458;
const int IDC_EDIT_TGT8 = 459;
const int IDC_EDIT_SRC17 = 460;
const int IDC_EDIT_TGT17 = 461;
wxSizer *SinglePunctTabPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDC_EDIT_2SRC0 = 462;
const int IDC_EDIT_2TGT0 = 463;
const int IDC_EDIT_2SRC5 = 464;
const int IDC_EDIT_2TGT5 = 465;
const int IDC_EDIT_2SRC1 = 466;
const int IDC_EDIT_2TGT1 = 467;
const int IDC_EDIT_2SRC6 = 468;
const int IDC_EDIT_2TGT6 = 469;
const int IDC_EDIT_2SRC2 = 470;
const int IDC_EDIT_2TGT2 = 471;
const int IDC_EDIT_2SRC7 = 472;
const int IDC_EDIT_2TGT7 = 473;
const int IDC_EDIT_2SRC3 = 474;
const int IDC_EDIT_2TGT3 = 475;
const int IDC_EDIT_2SRC8 = 476;
const int IDC_EDIT_2TGT8 = 477;
const int IDC_EDIT_2SRC4 = 478;
const int IDC_EDIT_2TGT4 = 479;
const int IDC_EDIT_2SRC9 = 480;
const int IDC_EDIT_2TGT9 = 481;
wxSizer *DoublePunctTabPageFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

wxSizer *ControlBar2LineFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_MSG = 482;
const int ID_BUTTON_LOCATE_SOURCE_FOLDER = 483;
const int ID_BITMAPBUTTON_SRC_OPEN_FOLDER_UP = 484;
const int ID_TEXT_SOURCE_FOLDER_PATH = 485;
const int ID_TEXTCTRL_SOURCE_PATH = 486;
const int ID_LISTCTRL_SOURCE_CONTENTS = 487;
const int ID_BUTTON_LOCATE_DESTINATION_FOLDER = 488;
const int ID_BITMAPBUTTON_DEST_OPEN_FOLDER_UP = 489;
const int ID_TEXTCTRL_DESTINATION_PATH = 490;
const int ID_LISTCTRL_DESTINATION_CONTENTS = 491;
const int ID_BUTTON_MOVE = 492;
const int ID_BUTTON_COPY = 493;
const int ID_BUTTON_RENAME = 494;
const int ID_BUTTON_DELETE = 495;
wxSizer *MoveOrCopyFilesOrFoldersFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_MSG1 = 496;
const int ID_TEXTCTRL_SOURCE_FILE_DETAILS = 497;
const int ID_TEXTCTRL_DESTINATION_FILE_DETAILS = 498;
const int ID_RADIOBUTTON_REPLACE = 499;
const int ID_RADIOBUTTON_NO_COPY = 500;
const int ID_RADIOBUTTON_COPY_AND_RENAME = 501;
const int ID_TEXT_MODIFY_NAME = 502;
const int ID_CHECKBOX_HANDLE_SAME = 503;
wxSizer *FilenameConflictFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LISTBOX_UPDATED = 504;
const int ID_TEXTCTRL_INFO_SOURCE = 505;
const int ID_TEXTCTRL_INFO_REFS = 506;
const int ID_LISTBOX_MATCHED = 507;
const int ID_BUTTON_UPDATE = 508;
const int ID_TEXTCTRL_LOCAL_SEARCH = 509;
const int ID_BUTTON_FIND_NEXT = 510;
const int ID_TEXTCTRL_EDITBOX = 511;
const int ID_BUTTON_RESTORE = 512;
const int ID_BUTTON_REMOVE_UPDATE = 513;
wxSizer *KBEditSearchFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATICTEXT_SCROLL_LIST = 514;
const int ID_LIST_LANGUAGE_CODES_NAMES = 515;
const int ID_STATICTEXT_SEARCH_FOR_LANG_NAME = 516;
const int ID_TEXTCTRL_SEARCH_LANG_NAME = 517;
const int ID_BUTTON_USE_SEL_AS_SRC = 518;
const int ID_BUTTON_USE_SEL_AS_TGT = 519;
const int ID_SRC_LANGUAGE_CODE = 520;
const int ID_TEXTCTRL_SRC_LANG_CODE = 521;
const int ID_TGT_LANGUAGE_CODE = 522;
const int ID_TEXTCTRL_TGT_LANG_CODE = 523;
wxSizer *LanguageCodesDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_FILE_MENU = 524;
const int ID_SAVE_AS = 525;
const int ID_FILE_PACK_DOC = 526;
const int ID_FILE_UNPACK_DOC = 527;
const int ID_MENU = 528;
const int ID_FILE_STARTUP_WIZARD = 529;
const int ID_FILE_CLOSEKB = 530;
const int ID_FILE_CHANGEFOLDER = 531;
const int ID_FILE_SAVEKB = 532;
const int ID_FILE_BACKUP_KB = 533;
const int ID_FILE_RESTORE_KB = 534;
const int ID_EDIT_MENU = 535;
const int ID_EDIT_CUT = 536;
const int ID_EDIT_COPY = 537;
const int ID_EDIT_PASTE = 538;
const int ID_GO_TO = 539;
const int ID_EDIT_SOURCE_TEXT = 540;
const int ID_EDIT_CONSISTENCY_CHECK = 541;
const int ID_EDIT_MOVE_NOTE_FORWARD = 542;
const int ID_EDIT_MOVE_NOTE_BACKWARD = 543;
const int ID_VIEW_MENU = 544;
const int ID_VIEW_TOOLBAR = 545;
const int ID_VIEW_STATUS_BAR = 546;
const int ID_VIEW_COMPOSE_BAR = 547;
const int ID_COPY_SOURCE = 548;
const int ID_MARKER_WRAPS_STRIP = 549;
const int ID_UNITS = 550;
const int ID_CHANGE_INTERFACE_LANGUAGE = 551;
const int ID_TOOLS_MENU = 552;
const int ID_TOOLS_DEFINE_CC = 553;
const int ID_UNLOAD_CC_TABLES = 554;
const int ID_USE_CC = 555;
const int ID_ACCEPT_CHANGES = 556;
const int ID_TOOLS_DEFINE_SILCONVERTER = 557;
const int ID_USE_SILCONVERTER = 558;
const int ID_TOOLS_KB_EDITOR = 559;
const int ID_TOOLS_AUTO_CAPITALIZATION = 560;
const int ID_RETRANS_REPORT = 561;
const int ID_TOOLS_SPLIT_DOC = 562;
const int ID_TOOLS_JOIN_DOCS = 563;
const int ID_TOOLS_MOVE_DOC = 564;
const int ID_EXPORT_IMPORT_MENU = 565;
const int ID_FILE_EXPORT_SOURCE = 566;
const int ID_FILE_EXPORT = 567;
const int ID_FILE_EXPORT_TO_RTF = 568;
const int ID_EXPORT_GLOSSES = 569;
const int ID_EXPORT_FREE_TRANS = 570;
const int ID_FILE_EXPORT_KB = 571;
const int ID_IMPORT_TO_KB = 572;
const int ID_ADVANCED_MENU = 573;
const int ID_ADVANCED_ENABLEGLOSSING = 574;
const int ID_ADVANCED_GLOSSING_USES_NAV_FONT = 575;
const int ID_ADVANCED_TRANSFORM_ADAPTATIONS_INTO_GLOSSES = 576;
const int ID_ADVANCED_DELAY = 577;
const int ID_ADVANCED_BOOKMODE = 578;
const int ID_ADVANCED_FREE_TRANSLATION_MODE = 579;
const int ID_ADVANCED_TARGET_TEXT_IS_DEFAULT = 580;
const int ID_ADVANCED_GLOSS_TEXT_IS_DEFAULT = 581;
const int ID_ADVANCED_REMOVE_FILTERED_FREE_TRANSLATIONS = 582;
const int ID_ADVANCED_COLLECT_BACKTRANSLATIONS = 583;
const int ID_ADVANCED_REMOVE_FILTERED_BACKTRANSLATIONS = 584;
const int ID_ADVANCED_USETRANSLITERATIONMODE = 585;
const int ID_ADVANCED_SENDSYNCHRONIZEDSCROLLINGMESSAGES = 586;
const int ID_ADVANCED_RECEIVESYNCHRONIZEDSCROLLINGMESSAGES = 587;
const int ID_LAYOUT_MENU = 588;
const int ID_ALIGNMENT = 589;
const int ID_HELP_MENU = 590;
const int ID_ONLINE_HELP = 591;
const int ID_USER_FORUM = 592;
const int ID_HELP_USE_TOOLTIPS = 593;
const int ID_ADMINISTRATOR_MENU = 594;
const int ID_CUSTOM_WORK_FOLDER_LOCATION = 595;
const int ID_LOCK_CUSTOM_LOCATION = 596;
const int ID_UNLOCK_CUSTOM_LOCATION = 597;
const int ID_LOCAL_WORK_FOLDER_MENU = 598;
const int ID_SET_PASSWORD_MENU = 599;
const int ID_MOVE_OR_COPY_FOLDERS_OR_FILES = 600;
wxMenuBar *AIMenuBarFunc();

// Declare toolbar functions

const int ID_BUTTON_CREATE_NOTE = 601;
const int ID_BUTTON_PREV_NOTE = 602;
const int ID_BUTTON_NEXT_NOTE = 603;
const int ID_BUTTON_DELETE_ALL_NOTES = 604;
const int ID_BUTTON_RESPECTING_BDRY = 605;
const int ID_BUTTON_SHOWING_PUNCT = 606;
const int ID_BUTTON_TO_END = 607;
const int ID_BUTTON_TO_START = 608;
const int ID_BUTTON_STEP_DOWN = 609;
const int ID_BUTTON_STEP_UP = 610;
const int ID_BUTTON_BACK = 611;
const int ID_BUTTON_MERGE = 612;
const int ID_BUTTON_RETRANSLATION = 613;
const int ID_BUTTON_EDIT_RETRANSLATION = 614;
const int ID_REMOVE_RETRANSLATION = 615;
const int ID_BUTTON_NULL_SRC = 616;
const int ID_BUTTON_REMOVE_NULL_SRCPHRASE = 617;
const int ID_BUTTON_CHOOSE_TRANSLATION = 618;
const int ID_SHOWING_ALL = 619;
const int ID_BUTTON_EARLIER_TRANSLATION = 620;
const int ID_BUTTON_NO_PUNCT_COPY = 621;
void AIToolBarFunc( wxToolBar *parent );

void AIToolBar32x30Func( wxToolBar *parent );

// Declare bitmap functions

wxBitmap AIToolBarBitmapsUnToggledFunc( size_t index );

const int ID_BITMAP_FOLDERAI = 622;
const int ID_BITMAP_FILEAI = 623;
const int ID_BITMAP_EMPTY_FOLDER = 624;
wxBitmap AIMainFrameIcons( size_t index );

const int ID_BUTTON_IGNORING_BDRY = 625;
const int ID_BUTTON_HIDING_PUNCT = 626;
const int ID_SHOWING_TGT = 627;
const int ID_BUTTON_ENABLE_PUNCT_COPY = 628;
wxBitmap AIToolBarBitmapsToggledFunc( size_t index );

wxBitmap WhichFilesBitmapsFunc( size_t index );

wxBitmap AIToolBarBitmapsToggled32x30Func( size_t index );

wxBitmap AIToolBarBitmapsUnToggled32x30Func( size_t index );

#endif

// End of generated file
