//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: Adapt_It.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_Adapt_It_H__
#define __WDR_Adapt_It_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "Adapt_It_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>
#include <wx/collpane.h>
#include <wx/hyperlink.h>
#include <wx/animate.h>
#include <wx/filepicker.h>
#include <wx/datectrl.h>
#include <wx/fontpicker.h>
#include <wx/clrpicker.h>
#include <wx/srchctrl.h>
#if wxCHECK_VERSION(2,9,0)
#include <wx/editlbox.h>
#endif

// Declare window functions

extern wxSizer *ID_ABOUT_TOP_AREA;
const int ID_ABOUT_AI_BMP = 10000;
const int ID_TEXT = 10001;
const int ID_ABOUT_VERSION_LABEL = 10002;
const int ID_ABOUT_VERSION_NUM = 10003;
const int ID_ABOUT_VERSION_DATE = 10004;
const int ID_STATIC_UNICODE_OR_ANSI = 10005;
const int ID_STATIC_WX_VERSION_USED = 10006;
const int ID_LINE = 10007;
const int ID_STATIC_UI_LANGUAGE = 10008;
const int ID_STATIC_HOST_OS = 10009;
const int ID_STATIC_SYS_LANGUAGE = 10010;
const int ID_STATIC_SYS_LOCALE_NAME = 10011;
const int ID_STATIC_CANONICAL_LOCALE_NAME = 10012;
const int ID_STATIC_SYS_ENCODING_NAME = 10013;
const int ID_STATIC_SYSTEM_LAYOUT_DIR = 10014;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *ID_CONTROLBAR_1_LINE_SIZER;
const int IDC_RADIO_DRAFTING = 10015;
const int IDC_RADIO_REVIEWING = 10016;
const int IDC_CHECK_SINGLE_STEP = 10017;
const int IDC_CHECK_KB_SAVE = 10018;
const int IDC_CHECK_FORCE_ASK = 10019;
const int IDC_BUTTON_NO_ADAPT = 10020;
const int IDC_STATIC = 10021;
const int IDC_EDIT_DELAY = 10022;
const int IDC_CHECK_ISGLOSSING = 10023;
wxSizer *ControlBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_COMPOSE = 10024;
extern wxSizer *ID_BSH_COMPOSE_LH_BUTTONS;
const int IDC_BUTTON_SHORTEN = 10025;
const int IDC_BUTTON_PREV = 10026;
const int IDC_BUTTON_LENGTHEN = 10027;
const int IDC_BUTTON_NEXT = 10028;
const int IDC_BUTTON_REMOVE = 10029;
const int IDC_BUTTON_APPLY = 10030;
const int ID_BUTTON_ADJUST = 10031;
const int ID_BUTTON_JOIN_TO_NEXT = 10032;
extern wxSizer *ID_BSV_SECTIONS;
const int IDC_STATIC_SECTION_DEF = 10033;
const int IDC_RADIO_PUNCT_SECTION = 10034;
const int IDC_RADIO_VERSE_SECTION = 10035;
extern wxSizer *ID_BSH_COMPOSE_RH_BUTTONS;
const int IDC_BUTTON_CLEAR = 10036;
const int IDC_BUTTON_SELECT_ALL = 10037;
wxSizer *ComposeBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LISTBOX_ADAPTIONS = 10038;
wxSizer *OpenExistingProjectDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_FILENAME = 10039;
const int ID_TEXT_INVALID_CHARACTERS = 10040;
wxSizer *GetOutputFilenameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SOURCE_LANGUAGE = 10041;
const int ID_EDIT_SOURCE_LANG_CODE = 10042;
const int IDC_TARGET_LANGUAGE = 10043;
const int ID_EDIT_TARGET_LANG_CODE = 10044;
const int ID_BUTTON_LOOKUP_CODES = 10045;
wxSizer *LanguagesPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SOURCE_FONTNAME = 10046;
const int IDC_CHECK_SRC_RTL = 10047;
const int IDC_SOURCE_SIZE = 10048;
const int IDC_SOURCE_LANG = 10049;
const int IDC_BUTTON_SOURCE_COLOR = 10050;
const int ID_BUTTON_CHANGE_SRC_ENCODING = 10051;
const int IDC_TARGET_FONTNAME = 10052;
const int IDC_CHECK_TGT_RTL = 10053;
const int IDC_TARGET_SIZE = 10054;
const int IDC_TARGET_LANG = 10055;
const int IDC_BUTTON_TARGET_COLOR = 10056;
const int ID_BUTTON_CHANGE_TGT_ENCODING = 10057;
const int IDC_NAVTEXT_FONTNAME = 10058;
const int IDC_CHECK_NAVTEXT_RTL = 10059;
const int IDC_NAVTEXT_SIZE = 10060;
const int IDC_CHANGE_NAV_TEXT = 10061;
const int IDC_BUTTON_NAV_TEXT_COLOR = 10062;
const int ID_BUTTON_CHANGE_NAV_ENCODING = 10063;
const int ID_TEXTCTRL_AS_STATIC_FONTPAGE = 10064;
const int IDC_BUTTON_SPECTEXTCOLOR = 10065;
const int IDC_RETRANSLATION_BUTTON = 10066;
const int ID_BUTTON_TEXT_DIFFS = 10067;
wxSizer *FontsPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_PLEASE_WAIT = 10068;
wxSizer *WaitDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_ACCEPTED = 10069;
const int IDC_BUTTON_REJECT = 10070;
const int IDC_BUTTON_ACCEPT = 10071;
const int ID_BUTTON_REJECT_ALL_FILES = 10072;
const int ID_BUTTON_ACCEPT_ALL_FILES = 10073;
const int IDC_LIST_REJECTED = 10074;
wxSizer *WhichFilesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES1 = 10075;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES2 = 10076;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES3 = 10077;
wxSizer *TransformToGlossesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECK_SOURCE_USES_CAPS = 10078;
const int ID_CHECK_USE_AUTO_CAPS = 10079;
const int ID_TEXTCTRL_AS_CASE_PAGE_STATIC_TEXT = 10080;
const int ID_TEXT_SL = 10081;
const int ID_TEXT_TL = 10082;
const int ID_TEXT_GL = 10083;
const int IDC_EDIT_SRC_CASE_EQUIVALENCES = 10084;
const int IDC_EDIT_TGT_CASE_EQUIVALENCES = 10085;
const int IDC_EDIT_GLOSS_CASE_EQUIVALENCES = 10086;
const int IDC_BUTTON_CLEAR_SRC_LIST = 10087;
const int IDC_BUTTON_CLEAR_TGT_LIST = 10088;
const int IDC_BUTTON_CLEAR_GLOSS_LIST = 10089;
const int IDC_BUTTON_SRC_SET_ENGLISH = 10090;
const int IDC_BUTTON_TGT_SET_ENGLISH = 10091;
const int IDC_BUTTON_GLOSS_SET_ENGLISH = 10092;
const int IDC_BUTTON_SRC_COPY_TO_NEXT = 10093;
const int IDC_BUTTON_TGT_COPY_TO_NEXT = 10094;
const int IDC_BUTTON_GLOSS_COPY_TO_NEXT = 10095;
const int IDC_BUTTON_SRC_COPY_TO_GLOSS = 10096;
wxSizer *CaseEquivDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_WELCOME_TO = 10097;
const int IDC_EDIT_ADAPT_IT = 10098;
const int ID_TEXTCTRL_AS_STATIC_WELCOME = 10099;
const int IDC_CHECK_NOLONGER_SHOW = 10100;
wxSizer *WelcomeDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_DOCPAGE = 10101;
const int IDC_STATIC_WHICH_MODE = 10102;
const int IDC_BUTTON_WHAT_IS_DOC = 10103;
const int IDC_STATIC_WHICH_FOLDER = 10104;
const int IDC_LIST_NEWDOC_AND_EXISTINGDOC = 10105;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES = 10106;
const int IDC_CHANGE_FOLDER_BTN = 10107;
const int IDC_CHECK_FORCE_UTF8 = 10108;
wxSizer *DocPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_PROJECTPAGE = 10109;
const int IDC_BUTTON_WHAT_IS_PROJECT = 10110;
const int IDC_LIST_NEW_AND_EXISTING = 10111;
wxSizer *ProjectPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_SRC = 10112;
const int IDC_LIST_PUNCTS = 10113;
const int ID_TEXTCTRL_AS_STATIC_PLACE_INT_PUNCT = 10114;
const int IDC_EDIT_TGT = 10115;
const int IDC_BUTTON_PLACE = 10116;
wxSizer *PlaceInternalPunctDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_INCHES = 10117;
const int IDC_RADIO_CM = 10118;
wxSizer *UnitsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_SRC = 10119;
const int IDC_EDIT_PRECONTEXT = 10120;
const int IDC_EDIT_SOURCE_TEXT = 10121;
const int IDC_EDIT_RETRANSLATION = 10122;
const int IDC_COPY_RETRANSLATION_TO_CLIPBOARD = 10123;
const int IDC_BUTTON_TOGGLE = 10124;
const int IDC_STATIC_TGT = 10125;
const int IDC_EDIT_FOLLCONTEXT = 10126;
wxSizer *RetranslationDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_SRC_TEXT = 10127;
const int IDC_EDIT_TGT_TEXT = 10128;
const int IDC_SPIN_CHAPTER = 10129;
const int IDC_SPIN_VERSE = 10130;
const int IDC_GET_CHVERSE_TEXT = 10131;
const int IDC_CLOSE_AND_JUMP = 10132;
const int IDC_SHOW_MORE = 10133;
const int IDC_SHOW_LESS = 10134;
const int IDC_STATIC_BEGIN = 10135;
const int IDC_STATIC_END = 10136;
wxSizer *EarlierTransDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_CHECK_KB_BACKUP = 10137;
const int IDC_CHECK_BAKUP_DOC = 10138;
const int ID_TEXTCTRL_AS_STATIC_BACKUPS_AND_KB_PAGE = 10139;
const int IDC_EDIT_SRC_NAME = 10140;
const int IDC_EDIT_TGT_NAME = 10141;
const int IDC_EDIT_GLS_NAME = 10142;
const int ID_EDIT_GLOSS_LANG_CODE = 10143;
const int ID_EDIT_FRTR_NAME = 10144;
const int ID_EDIT_FRTR_LANG_CODE = 10145;
const int IDC_RADIO_ADAPT_BEFORE_GLOSS = 10146;
const int IDC_RADIO_GLOSS_BEFORE_ADAPT = 10147;
const int IDC_CHECK_LEGACY_SRC_TEXT_COPY = 10148;
const int IDC_RADIO_COPY_SRC_WORD_DELIM = 10149;
const int IDC_RADIO_USE_ONLY_LATIN_SPACE = 10150;
wxSizer *BackupsAndKBPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int STATIC_TEXT_V4 = 10151;
const int IDC_EDIT_LEADING = 10152;
const int STATIC_TEXT_V5 = 10153;
const int IDC_EDIT_GAP_WIDTH = 10154;
const int STATIC_TEXT_V6 = 10155;
const int IDC_EDIT_LEFTMARGIN = 10156;
const int STATIC_TEXT_V7 = 10157;
const int IDC_EDIT_MULTIPLIER = 10158;
const int IDC_EDIT_DIALOGFONTSIZE = 10159;
const int IDC_CHECK_WELCOME_VISIBLE = 10160;
const int IDC_CHECK_HIGHLIGHT_AUTO_INSERTED_TRANSLATIONS = 10161;
const int ID_PANEL_AUTO_INSERT_COLOR = 10162;
const int IDC_BUTTON_CHOOSE_HIGHLIGHT_COLOR = 10163;
const int IDC_CHECK_SHOW_ADMIN_MENU = 10164;
const int ID_RADIOBOX_SCROLL_INTO_VIEW = 10165;
const int ID_CHECKBOX_ENABLE_INSERT_ZWSP = 10166;
wxSizer *ViewPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

wxSizer *UnitsPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_AUTOSAVE = 10167;
const int IDC_CHECK_NO_AUTOSAVE = 10168;
const int IDC_RADIO_BY_MINUTES = 10169;
const int IDC_EDIT_MINUTES = 10170;
const int IDC_SPIN_MINUTES = 10171;
const int IDC_RADIO_BY_MOVES = 10172;
const int IDC_EDIT_MOVES = 10173;
const int IDC_SPIN_MOVES = 10174;
const int IDC_EDIT_KB_MINUTES = 10175;
const int IDC_SPIN_KB_MINUTES = 10176;
wxSizer *AutoSavingPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_DIV1 = 10177;
const int IDC_RADIO_DIV2 = 10178;
const int IDC_RADIO_DIV3 = 10179;
const int IDC_RADIO_DIV4 = 10180;
const int IDC_RADIO_DIV5 = 10181;
const int IDC_COMBO_CHOOSE_BOOK = 10182;
const int ID_TEXT_AS_STATIC = 10183;
wxSizer *WhichBookDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_MSG = 10184;
const int IDC_EDIT_ERR_XML = 10185;
const int IDC_STATIC_LBL = 10186;
const int IDC_EDIT_OFFSET = 10187;
wxSizer *XMLErrorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_ED_SILCONVERTER_NAME = 10188;
const int IDC_BTN_SELECT_SILCONVERTER = 10189;
const int IDC_ED_SILCONVERTER_INFO = 10190;
const int IDC_BTN_CLEAR_SILCONVERTER = 10191;
wxSizer *SilConvertersDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_FOLDER_DOCS = 10192;
const int IDC_LIST_FOLDER_DOCS = 10193;
const int IDC_BUTTON_NEXT_CHAPTER = 10194;
const int IDC_BUTTON_SPLIT_NOW = 10195;
const int IDC_STATIC_SPLITTING_WAIT = 10196;
const int IDC_RADIO_PHRASEBOX_LOCATION = 10197;
const int IDC_RADIO_CHAPTER_SFMARKER = 10198;
const int IDC_RADIO_DIVIDE_INTO_CHAPTERS = 10199;
const int IDC_STATIC_SPLIT_NAME = 10200;
const int IDC_EDIT1 = 10201;
const int IDC_STATIC_REMAIN_NAME = 10202;
const int IDC_EDIT2 = 10203;
wxSizer *SplitDialogFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_MARKERS = 10204;
const int IDC_TEXTCTRL_AS_STATIC_PLACE_INT_MKRS = 10205;
wxSizer *PlaceInternalMarkersDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_NOTE = 10206;
const int IDC_EDIT_FIND_TEXT = 10207;
const int IDC_FIND_NEXT_BTN = 10208;
const int IDC_LAST_BTN = 10209;
const int IDC_NEXT_BTN = 10210;
const int IDC_PREV_BTN = 10211;
const int IDC_FIRST_BTN = 10212;
const int IDC_DELETE_BTN = 10213;
wxSizer *NoteDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_COLLECT_BT = 10214;
const int IDC_RADIO_COLLECT_ADAPTATIONS = 10215;
const int IDC_RADIO_COLLECT_GLOSSES = 10216;
wxSizer *CollectBackTranslationsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SPIN_DELAY_TICKS = 10217;
wxSizer *SetDelayDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_EXPORT_ALL = 10218;
const int IDC_RADIO_EXPORT_SELECTED_MARKERS = 10219;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_OPTIONS = 10220;
const int IDC_LIST_SFMS = 10221;
const int IDC_BUTTON_EXCLUDE_FROM_EXPORT = 10222;
const int IDC_BUTTON_INCLUDE_IN_EXPORT = 10223;
const int IDC_BUTTON_UNDO = 10224;
const int IDC_STATIC_SPECIAL_NOTE = 10225;
const int IDC_CHECK_PLACE_FREE_TRANS = 10226;
const int IDC_CHECK_INTERLINEAR_PLACE_FREE_TRANS = 10227;
const int IDC_CHECK_PLACE_BACK_TRANS = 10228;
const int IDC_CHECK_INTERLINEAR_PLACE_BACK_TRANS = 10229;
const int IDC_CHECK_PLACE_AI_NOTES = 10230;
const int IDC_CHECK_INTERLINEAR_PLACE_AI_NOTES = 10231;
wxSizer *ExportOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_PNLEXPORT = 10232;
const int ID_BUTTON_CHANGE_BOOK_NAME = 10233;
const int ID_LBLEXPORTTYPEDESCRIPTION = 10234;
const int ID_RDOFILTEROFF = 10235;
const int ID_RDOFILTERON = 10236;
const int ID_BTNFILTEROPTIONS = 10237;
const int ID_CHKPROJECTNAMEPREFIX = 10238;
const int ID_CHKTARGETTEXTPREFIX = 10239;
const int ID_CHKDATETIMESUFFIX = 10240;
wxSizer *ExportSaveAsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_CHECK_INCLUDE_NAV_TEXT = 10241;
const int IDC_CHECK_INCLUDE_SOURCE_TEXT = 10242;
const int IDC_CHECK_INCLUDE_TARGET_TEXT = 10243;
const int IDC_CHECK_INCLUDE_GLS_TEXT = 10244;
const int ID_TEXTCTRL_AS_STATIC_EXP_INTERLINEAR = 10245;
const int IDC_RADIO_PORTRAIT = 10246;
const int IDC_RADIO_LANDSCAPE = 10247;
const int IDC_RADIO_OUTPUT_ALL = 10248;
const int IDC_RADIO_OUTPUT_CHAPTER_VERSE_RANGE = 10249;
const int IDC_EDIT_FROM_CHAPTER = 10250;
const int IDC_EDIT_FROM_VERSE = 10251;
const int IDC_EDIT_TO_CHAPTER = 10252;
const int IDC_EDIT_TO_VERSE = 10253;
const int IDC_RADIO_OUTPUT_PRELIM = 10254;
const int IDC_RADIO_OUTPUT_FINAL = 10255;
const int ID_CHECK_NEW_TABLES_FOR_NEWLINE_MARKERS = 10256;
const int ID_CHECK_CENTER_TABLES_FOR_CENTERED_MARKERS = 10257;
const int ID_CHECKBOX_PREFIX_EXPORT_PROJ_NAME = 10258;
const int ID_CHECKBOX_PREFIX_EXPORT_TYPE = 10259;
const int ID_CHECKBOX_SUFFIX_EXPORT_DATETIME_STAMP = 10260;
const int IDC_BUTTON_RTF_EXPORT_FILTER_OPTIONS = 10261;
wxSizer *ExportInterlinearDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_MARKER = 10262;
const int IDC_EDIT_MARKER_TEXT = 10263;
const int IDC_REMOVE_BTN = 10264;
const int IDC_BUTTON_SWITCH_ENCODING = 10265;
const int IDC_LIST_MARKER_END = 10266;
const int IDC_STATIC_MARKER_DESCRIPTION = 10267;
const int IDC_STATIC_MARKER_STATUS = 10268;
wxSizer *ViewFilteredMaterialDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_CHAPTER = 10269;
const int IDC_EDIT_VERSE = 10270;
wxSizer *GoToDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_MAIN_MSG = 10271;
const int IDC_EDIT_KEY = 10272;
extern wxSizer *m_topRightBoxLabel;
const int IDC_EDIT_ADAPTATION = 10273;
const int IDC_RADIO_ACCEPT_HERE = 10274;
const int ID_TEXT_NO_ADAPT_MSG = 10275;
const int IDC_RADIO_CHANGE_INSTEAD = 10276;
const int IDC_EDIT_CH_VERSE = 10277;
const int ID_TEXT_AVAIL_ADAPT_OR_GLOSS = 10278;
const int IDC_LIST_TRANSLATIONS = 10279;
extern wxSizer *m_pNumberedPointsStaticBoxSizer;
const int ID_TEXT_CLICK_LISTED = 10280;
const int ID_TEXT_CLICK_EDIT_LISTED = 10281;
const int ID_TEXT_TYPE_NEW = 10282;
const int IDC_CHECK_DO_SAME = 10283;
const int ID_BUTTON_IGNORE_IT = 10284;
wxSizer *ConsistencyCheckDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_CHECK_OPEN_DOC_ONLY = 10285;
const int IDC_RADIO_CHECK_SELECTED_DOCS = 10286;
const int ID_TEXTCTRL_MSG = 10287;
wxSizer *ChooseConsistencyCheckTypeDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL = 10288;
const int IDC_EDIT_OLD_SOURCE_TEXT = 10289;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC1 = 10290;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC2 = 10291;
const int IDC_EDIT_NEW_SOURCE = 10292;
wxSizer *EditSourceTextDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_UNPACK_WARN = 10293;
wxSizer *UnpackWarningDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_COUNT = 10294;
const int IDC_LIST_SRC_KEYS = 10295;
const int IDC_LIST_EXISTING_TRANSLATIONS = 10296;
const int IDC_EDIT_EDITORADD = 10297;
const int IDC_BUTTON_UPDATE = 10298;
const int IDC_BUTTON_MOVE_UP = 10299;
const int IDC_BUTTON_ADD = 10300;
const int IDC_BUTTON_MOVE_DOWN = 10301;
const int IDC_ADD_NOTHING = 10302;
const int IDC_EDIT_SHOW_FLAG = 10303;
const int IDC_BUTTON_FLAG_TOGGLE = 10304;
const int IDC_EDIT_SRC_KEY = 10305;
const int IDC_EDIT_REF_COUNT = 10306;
const int ID_BUTTON_REMOVE_SOME = 10307;
const int ID_TEXTCTRL_SEARCH = 10308;
const int ID_BUTTON_GO = 10309;
const int ID_BUTTON_ERASE_ALL_LINES = 10310;
const int ID_COMBO_OLD_SEARCHES = 10311;
wxSizer *KBEditorPanelFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_TEXT_SELECT_A_TAB = 10312;
const int ID_STATIC_WHICH_KB = 10313;
const int ID_KB_EDITOR_NOTEBOOK = 10314;
wxSizer *KBEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_DOCS_IN_FOLDER = 10315;
const int IDC_LIST_SOURCE_FOLDER_DOCS = 10316;
const int IDC_RADIO_TO_BOOK_FOLDER = 10317;
const int IDC_RADIO_FROM_BOOK_FOLDER = 10318;
const int IDC_VIEW_OTHER = 10319;
const int IDC_BUTTON_RENAME_DOC = 10320;
const int IDC_MOVE_NOW = 10321;
wxSizer *MoveDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_JOIN1 = 10322;
const int IDC_BUTTON_MOVE_ALL_RIGHT = 10323;
const int IDC_BUTTON_MOVE_ALL_LEFT = 10324;
const int ID_TEXTCTRL_AS_STATIC_JOIN2 = 10325;
const int ID_TEXTCTRL_AS_STATIC_JOIN3 = 10326;
const int ID_JOIN_NOW = 10327;
const int IDC_STATIC_JOINING_WAIT = 10328;
const int ID_TEXTCTRL_AS_STATIC_JOIN4 = 10329;
const int IDC_EDIT_NEW_FILENAME = 10330;
wxSizer *JoinDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

wxSizer *ListDocInOtherFolderDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_SET_FONT_TITLE = 10331;
const int ID_STATIC_CURR_ENCODING_IS = 10332;
const int ID_TEXT_CURR_ENCODING = 10333;
const int ID_LISTBOX_POSSIBLE_FACENAMES = 10334;
const int ID_LISTBOX_POSSIBLE_ENCODINGS = 10335;
extern wxSizer *pTestBoxStaticTextBoxSizer;
const int ID_TEXT_TEST_ENCODING_BOX = 10336;
const int ID_BUTTON_CHART_FONT_SIZE_DECREASE = 10337;
const int ID_BUTTON_CHART_FONT_SIZE_INCREASE = 10338;
const int ID_STATIC_CHART_FONT_SIZE = 10339;
const int ID_SCROLLED_ENCODING_WINDOW = 10340;
wxSizer *SetEncodingDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_CCT = 10341;
wxSizer *CCTableEditDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_CCTABLES = 10342;
const int IDC_EDIT_SELECTED_TABLE = 10343;
const int IDC_BUTTON_BROWSE = 10344;
const int IDC_BUTTON_CREATE_CCT = 10345;
const int IDC_BUTTON_EDIT_CCT = 10346;
const int IDC_BUTTON_SELECT_NONE = 10347;
const int IDC_EDIT_FOLDER_PATH = 10348;
wxSizer *CCTablePageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_SRC_ONLY_FIND = 10349;
const int IDC_RADIO_TGT_ONLY_FIND = 10350;
const int IDC_RADIO_SRC_AND_TGT_FIND = 10351;
const int IDC_CHECK_IGNORE_CASE_FIND = 10352;
const int IDC_STATIC_SRC_FIND = 10353;
const int IDC_EDIT_SRC_FIND = 10354;
const int IDC_STATIC_TGT_FIND = 10355;
const int IDC_EDIT_TGT_FIND = 10356;
const int IDC_CHECK_INCLUDE_PUNCT_FIND = 10357;
const int IDC_CHECK_SPAN_SRC_PHRASES_FIND = 10358;
const int IDC_STATIC_SPECIAL = 10359;
extern wxSizer *IDC_STATIC_SIZER_SPECIAL;
const int IDC_RADIO_RETRANSLATION = 10360;
const int IDC_RADIO_NULL_SRC_PHRASE = 10361;
const int IDC_RADIO_SFM = 10362;
const int IDC_STATIC_SELECT_MKR = 10363;
const int IDC_COMBO_SFM = 10364;
const int IDC_BUTTON_SPECIAL = 10365;
wxSizer *FindDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_SRC_ONLY_REPLACE = 10366;
const int IDC_RADIO_TGT_ONLY_REPLACE = 10367;
const int IDC_RADIO_SRC_AND_TGT_REPLACE = 10368;
const int IDC_CHECK_IGNORE_CASE_REPLACE = 10369;
const int IDC_STATIC_SRC_REPLACE = 10370;
const int IDC_EDIT_SRC_REPLACE = 10371;
const int IDC_STATIC_TGT_REPLACE = 10372;
const int IDC_EDIT_TGT_REPLACE = 10373;
const int IDC_CHECK_INCLUDE_PUNCT_REPLACE = 10374;
const int IDC_CHECK_SPAN_SRC_PHRASES_REPLACE = 10375;
const int IDC_STATIC_REPLACE = 10376;
const int IDC_EDIT_REPLACE = 10377;
const int IDC_REPLACE = 10378;
const int IDC_REPLACE_ALL_BUTTON = 10379;
wxSizer *ReplaceDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC = 10380;
const int IDC_EDIT_TBLNAME = 10381;
wxSizer *CCTableNameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_EDIT_AS_STATIC = 10382;
const int ID_CHECKBOX_INCLUDE_FREE_TRANS_TEXT = 10383;
const int ID_CHECKBOX_INCLUDE_GLOSSES_TEXT = 10384;
const int ID_RADIO_ALL = 10385;
const int ID_RADIO_SELECTION = 10386;
const int IDC_RADIO_PAGES = 10387;
const int IDC_EDIT_PAGES_FROM = 10388;
const int IDC_EDIT_PAGES_TO = 10389;
const int IDC_RADIO_CHAPTER_VERSE_RANGE = 10390;
const int IDC_EDIT3 = 10391;
const int IDC_EDIT4 = 10392;
const int IDC_CHECK_SUPPRESS_PREC_HEADING = 10393;
const int IDC_CHECK_INCLUDE_FOLL_HEADING = 10394;
const int IDC_CHECK_SUPPRESS_FOOTER = 10395;
wxSizer *PrintOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CC_TABBED_NOTEBOOK = 10396;
wxSizer *CCTabbedNotebookFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LIST_UI_LANGUAGES = 10397;
const int ID_TEXT_AS_STATIC_SHORT_LANG_NAME = 10398;
const int ID_TEXT_AS_STATIC_LONG_LANG_NAME = 10399;
const int IDC_LOCALIZATION_PATH = 10400;
wxSizer *ChooseLanguageDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_COMBO_REMOVALS = 10401;
const int ID_STATIC_TEXT_REMOVALS = 10402;
const int IDC_BUTTON_UNDO_LAST_COPY = 10403;
wxSizer *RemovalsBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_MSG_TEXT = 10404;
const int IDC_BUTTON_PREV_STEP = 10405;
const int IDC_BUTTON_NEXT_STEP = 10406;
const int ID_BUTTON_END_NOW = 10407;
const int ID_BUTTON_CANCEL_ALL_STEPS = 10408;
wxSizer *VertEditBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_TITLE = 10409;
const int IDC_TOGGLE_UNNNN_BTN = 10410;
const int ID_TEXTCTRL_AS_STATIC_PUNCT_CORRESP_PAGE = 10411;
const int IDC_EDIT_SRC0 = 10412;
const int IDC_EDIT_TGT0 = 10413;
const int IDC_EDIT_SRC1 = 10414;
const int IDC_EDIT_TGT1 = 10415;
const int IDC_EDIT_SRC2 = 10416;
const int IDC_EDIT_TGT2 = 10417;
const int IDC_EDIT_SRC3 = 10418;
const int IDC_EDIT_TGT3 = 10419;
const int IDC_EDIT_SRC4 = 10420;
const int IDC_EDIT_TGT4 = 10421;
const int IDC_EDIT_SRC5 = 10422;
const int IDC_EDIT_TGT5 = 10423;
const int IDC_EDIT_SRC6 = 10424;
const int IDC_EDIT_TGT6 = 10425;
const int IDC_EDIT_SRC7 = 10426;
const int IDC_EDIT_TGT7 = 10427;
const int IDC_EDIT_SRC8 = 10428;
const int IDC_EDIT_TGT8 = 10429;
const int IDC_EDIT_SRC9 = 10430;
const int IDC_EDIT_TGT9 = 10431;
const int IDC_EDIT_SRC10 = 10432;
const int IDC_EDIT_TGT10 = 10433;
const int IDC_EDIT_SRC11 = 10434;
const int IDC_EDIT_TGT11 = 10435;
const int IDC_EDIT_SRC12 = 10436;
const int IDC_EDIT_TGT12 = 10437;
const int IDC_EDIT_SRC13 = 10438;
const int IDC_EDIT_TGT13 = 10439;
const int IDC_EDIT_SRC14 = 10440;
const int IDC_EDIT_TGT14 = 10441;
const int IDC_EDIT_SRC15 = 10442;
const int IDC_EDIT_TGT15 = 10443;
const int IDC_EDIT_SRC16 = 10444;
const int IDC_EDIT_TGT16 = 10445;
const int IDC_EDIT_SRC17 = 10446;
const int IDC_EDIT_TGT17 = 10447;
const int IDC_EDIT_SRC18 = 10448;
const int IDC_EDIT_TGT18 = 10449;
const int IDC_EDIT_SRC19 = 10450;
const int IDC_EDIT_TGT19 = 10451;
const int IDC_EDIT_SRC20 = 10452;
const int IDC_EDIT_TGT20 = 10453;
const int IDC_EDIT_SRC21 = 10454;
const int IDC_EDIT_TGT21 = 10455;
const int IDC_EDIT_SRC22 = 10456;
const int IDC_EDIT_TGT22 = 10457;
const int IDC_EDIT_SRC23 = 10458;
const int IDC_EDIT_TGT23 = 10459;
const int IDC_EDIT_SRC24 = 10460;
const int IDC_EDIT_TGT24 = 10461;
const int IDC_EDIT_SRC25 = 10462;
const int IDC_EDIT_TGT25 = 10463;
const int IDC_EDIT_2SRC0 = 10464;
const int IDC_EDIT_2TGT0 = 10465;
const int IDC_EDIT_2SRC1 = 10466;
const int IDC_EDIT_2TGT1 = 10467;
const int IDC_EDIT_2SRC2 = 10468;
const int IDC_EDIT_2TGT2 = 10469;
const int IDC_EDIT_2SRC3 = 10470;
const int IDC_EDIT_2TGT3 = 10471;
const int IDC_EDIT_2SRC4 = 10472;
const int IDC_EDIT_2TGT4 = 10473;
const int IDC_EDIT_2SRC5 = 10474;
const int IDC_EDIT_2TGT5 = 10475;
const int IDC_EDIT_2SRC6 = 10476;
const int IDC_EDIT_2TGT6 = 10477;
const int IDC_EDIT_2SRC7 = 10478;
const int IDC_EDIT_2TGT7 = 10479;
const int IDC_EDIT_2SRC8 = 10480;
const int IDC_EDIT_2TGT8 = 10481;
const int IDC_EDIT_2SRC9 = 10482;
const int IDC_EDIT_2TGT9 = 10483;
wxSizer *PunctCorrespPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_TOP;
extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_BOTTOM;
wxSizer *ControlBar2LineFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_MSG1 = 10484;
const int ID_BUTTON_LOCATE_SOURCE_FOLDER = 10485;
const int ID_BITMAPBUTTON_SRC_OPEN_FOLDER_UP = 10486;
const int ID_TEXT_SOURCE_FOLDER_PATH = 10487;
const int ID_TEXTCTRL_SOURCE_PATH = 10488;
const int ID_LISTCTRL_SOURCE_CONTENTS = 10489;
const int ID_BUTTON_LOCATE_DESTINATION_FOLDER = 10490;
const int ID_BITMAPBUTTON_DEST_OPEN_FOLDER_UP = 10491;
const int ID_TEXTCTRL_DESTINATION_PATH = 10492;
const int ID_LISTCTRL_DESTINATION_CONTENTS = 10493;
const int ID_BUTTON_MOVE = 10494;
const int ID_BUTTON_COPY = 10495;
const int ID_BUTTON_PEEK = 10496;
const int ID_BUTTON_RENAME = 10497;
const int ID_BUTTON_DELETE = 10498;
wxSizer *MoveOrCopyFilesOrFoldersFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_MSG1 = 10499;
const int ID_STATICBITMAP = 10500;
const int ID_TEXTCTRL_SOURCE_FILE_DETAILS = 10501;
const int ID_TEXTCTRL_DESTINATION_FILE_DETAILS = 10502;
const int ID_RADIOBUTTON_REPLACE = 10503;
const int ID_RADIOBUTTON_NO_COPY = 10504;
const int ID_RADIOBUTTON_COPY_AND_RENAME = 10505;
const int ID_TEXT_MODIFY_NAME = 10506;
const int ID_CHECKBOX_HANDLE_SAME = 10507;
wxSizer *FilenameConflictFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LISTBOX_UPDATED = 10508;
const int ID_TEXTCTRL_INFO_SOURCE = 10509;
const int ID_TEXTCTRL_INFO_REFS = 10510;
const int ID_LISTBOX_MATCHED = 10511;
const int ID_BUTTON_UPDATE = 10512;
const int ID_TEXTCTRL_LOCAL_SEARCH = 10513;
const int ID_BUTTON_FIND_NEXT = 10514;
const int ID_TEXTCTRL_EDITBOX = 10515;
const int ID_BUTTON_RESTORE = 10516;
const int ID_BUTTON_REMOVE_UPDATE = 10517;
wxSizer *KBEditSearchFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATICTEXT_SCROLL_LIST = 10518;
const int ID_LIST_LANGUAGE_CODES_NAMES = 10519;
const int ID_STATICTEXT_SEARCH_FOR_LANG_NAME = 10520;
const int ID_TEXTCTRL_SEARCH_LANG_NAME = 10521;
const int ID_BUTTON_FIND_CODE = 10522;
const int ID_BUTTON_FIND_LANGUAGE = 10523;
const int ID_BUTTON_USE_SEL_AS_SRC = 10524;
const int ID_BUTTON_USE_SEL_AS_TGT = 10525;
const int ID_BUTTON_USE_SEL_AS_GLS = 10526;
const int ID_BUTTON_USE_SEL_AS_FRTR = 10527;
const int ID_TEXT_CODES_MSG1 = 10528;
const int ID_TEXT_CODES_MSG2 = 10529;
const int ID_SRC_LANGUAGE_CODE = 10530;
const int ID_TGT_LANGUAGE_CODE = 10531;
const int ID_GLS_LANGUAGE_CODE = 10532;
const int ID_TEXT_FRTR = 10533;
const int ID_TEXTCTRL_SRC_LANG_CODE = 10534;
const int ID_TEXTCTRL_TGT_LANG_CODE = 10535;
const int ID_TEXTCTRL_GLS_LANG_CODE = 10536;
const int ID_TEXTCTRL_FRTR_LANG_CODE = 10537;
wxSizer *LanguageCodesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_PEEKMSG = 10538;
extern wxSizer *m_pHorizBox_for_textctrl;
const int ID_TEXTCTRL_LINES100 = 10539;
const int ID_BUTTON_TOGGLE_TEXT_DIRECTION = 10540;
wxSizer *PeekAtFileFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_INSTRUCTIONS = 10541;
const int ID_LISTBOX_LOADABLES_FILENAMES = 10542;
wxSizer *NewDocFromSourceDataFolderFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_SELECT_A_TAB = 10543;
const int ID_MENU_EDITOR_NOTEBOOK = 10544;
const int ID_RADIOBUTTON_NONE = 10545;
const int ID_RADIOBUTTON_USE_PROFILE = 10546;
const int ID_COMBO_PROFILE_ITEMS = 10547;
const int ID_BUTTON_RESET_TO_FACTORY = 10548;
const int ID_TEXT_STATIC_DESCRIPTION = 10549;
const int ID_TEXTCTRL_PROFILE_DESCRIPTION = 10550;
wxSizer *MenuEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECKLISTBOX_MENU_ITEMS = 10551;
wxSizer *MenuEditorPanelFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_USE_UBS_SET_ONLY = 10552;
const int IDC_RADIO_USE_SILPNG_SET_ONLY = 10553;
const int IDC_RADIO_USE_BOTH_SETS = 10554;
const int IDC_RADIO_USE_UBS_SET_ONLY_PROJ = 10555;
const int IDC_RADIO_USE_SILPNG_SET_ONLY_PROJ = 10556;
const int IDC_RADIO_USE_BOTH_SETS_PROJ = 10557;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES_USFM = 10558;
const int ID_TEXTCTRL_AS_STATIC_FILTERPAGE = 10559;
const int IDC_LIST_SFMS_PROJ = 10560;
wxSizer *UsfmFilterPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECK_USE_GUESSER = 10561;
const int ID_PANEL_GUESS_COLOR_DISPLAY = 10562;
const int ID_BUTTON_GUESS_HIGHLIGHT_COLOR = 10563;
const int ID_SLIDER_GUESSER = 10564;
const int ID_CHECK_ALLOW_GUESSER_ON_UNCHANGED_CC_OUTPUT = 10565;
const int ID_TEXT_STATIC_NUM_CORRESP_ADAPTATIONS_GUESSER = 10566;
const int ID_TEXT_STATIC_NUM_CORRESP_GLOSSING_GUESSER = 10567;
const int ID_BTN_GUESSER_HOW_TO_USE_DLG = 10568;
wxSizer *GuesserSettingsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_DEVS_EMAIL_ADDR = 10569;
const int ID_TEXTCTRL_MY_EMAIL_ADDR = 10570;
const int ID_TEXTCTRL_SUMMARY_SUBJECT = 10571;
extern wxSizer *STATIC_TEXT_DESCRIPTION;
const int ID_TEXTCTRL_DESCRIPTION_BODY = 10572;
const int ID_TEXTCTRL_SENDERS_NAME = 10573;
const int ID_CHECKBOX_LET_DEVS_KNOW_AI_USAGE = 10574;
const int ID_BUTTON_VIEW_USAGE_LOG = 10575;
const int ID_TEXT_AI_VERSION = 10576;
const int ID_TEXT_RELEASE_DATE = 10577;
const int ID_TEXT_DATA_TYPE = 10578;
const int ID_TEXT_FREE_MEMORY = 10579;
const int ID_TEXT_SYS_LOCALE = 10580;
const int ID_TEXT_INTERFACE_LANGUAGE = 10581;
const int ID_TEXT_SYS_ENCODING = 10582;
const int ID_TEXT_SYS_LAYOUT_DIR = 10583;
const int ID_TEXT_WXWIDGETS_VERSION = 10584;
const int ID_TEXT_OS_VERSION = 10585;
const int ID_BUTTON_SAVE_REPORT_AS_TEXT_FILE = 10586;
const int ID_BUTTON_LOAD_SAVED_REPORT = 10587;
const int ID_RADIOBUTTON_SEND_DIRECTLY_FROM_AI = 10588;
const int ID_RADIOBUTTON_SEND_TO_MY_EMAIL = 10589;
const int ID_BUTTON_ATTACH_PACKED_DOC = 10590;
const int ID_BUTTON_SEND_NOW = 10591;
wxSizer *EmailReportDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_LOG_FILE_PATH_AND_NAME = 10592;
const int ID_TEXTCTRL_LOGGED_TEXT = 10593;
wxSizer *LogViewerFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *STATIC_TEXT_PTorBE_PROJECTS;
const int ID_TEXT_SRC_PROJ = 10594;
const int ID_STATIC_TEXT_SRC_PROJ = 10595;
const int ID_TEXT_TGT_PROJ = 10596;
const int ID_STATIC_TEXT_TGT_PROJ = 10597;
const int ID_TEXT_FREETRANS_PROJ = 10598;
const int ID_STATIC_TEXT_FREETRANS_PROJ = 10599;
const int ID_TEXT_AI_PROJ = 10600;
const int ID_TEXT_SELECT_A_CHAPTER = 10601;
const int ID_LISTBOX_BOOK_NAMES = 10602;
const int ID_LISTCTRL_CHAPTER_NUMBER_AND_STATUS = 10603;
const int ID_TEXTCTRL_AS_STATIC_NOTE = 10604;
const int ID_LINE_1 = 10605;
wxSizer *GetSourceTextFromEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_TOP_INFO = 10606;
const int ID_CHECKBOX_PROTECT_SOURCE_INPUTS = 10607;
const int ID_BUTTON_PRE_LOAD_SOURCE_TEXTS = 10608;
const int ID_CHECKBOX_PROTECT_FREETRANS_OUTPUTS = 10609;
const int ID_CHECKBOX_PROTECT_FREETRANS_RTF_OUTPUTS = 10610;
const int ID_CHECKBOX_PROTECT_GLOSS_OUTPUTS = 10611;
const int ID_CHECKBOX_PROTECT_GLOSS_RTF_OUTPUTS = 10612;
const int ID_CHECKBOX_PROTECT_SOURCE_OUTPUTS = 10613;
const int ID_CHECKBOX_PROTECT_SOURCE_RTF_OUTPUTS = 10614;
const int ID_CHECKBOX_PROTECT_TARGET_OUTPUTS = 10615;
const int ID_CHECKBOX_PROTECT_TARGET_RTF_OUTPUTS = 10616;
const int ID_CHECKBOX_PROTECT_REPORTS_OUTPUTS = 10617;
const int ID_CHECKBOX_PROTECT_INTERLINEAR_RTF_OUTPUTS = 10618;
const int ID_CHECKBOX_PROTECT_XHTML_OUTPUTS = 10619;
const int ID_CHECKBOX_PROTECT_PATHWAY_OUTPUTS = 10620;
const int ID_CHECKBOX_PROTECT_KB_INPUTS_AND_OUTPUTS = 10621;
const int ID_CHECKBOX_PROTECT_LIFT_INPUTS_AND_OUTPUTS = 10622;
const int ID_CHECKBOX_PROTECT_PACKED_INPUTS_AND_OUTPUTS = 10623;
const int ID_CHECKBOX_PROTECT_CCTABLE_INPUTS_AND_OUTPUTS = 10624;
const int ID_BUTTON_UNSELECT_ALL_CHECKBOXES = 10625;
const int ID_BUTTON_SELECT_ALL_CHECKBOXES = 10626;
wxSizer *AssignLocationsForInputsOutputsFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_SOURCE_PHRASE_1 = 10627;
const int ID_TEXT_EMPTY_STR = 10628;
const int ID_RADIO_NO_ADAPTATION = 10629;
const int ID_RADIO_LEAVE_HOLE = 10630;
const int ID_RADIO_NOT_IN_KB = 10631;
const int ID_RADIOBUTTON_TYPE_AORG = 10632;
const int ID_TEXTCTRL_TYPED_AORG = 10633;
const int ID_CHECK_DO_SAME = 10634;
wxSizer *ConsistencyCheck_EmptyNoTU_DlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_SOURCE_PHRASE_2 = 10635;
const int ID_TEXTCTRL_TARGET_PHRASE_2 = 10636;
const int ID_TEXT_EXISTS_STR = 10637;
const int ID_RADIO_STORE_NORMALLY = 10638;
const int ID_RADIO_NOT_IN_KB_LEAVEINDOC = 10639;
const int ID_CHECK_DO_SAME2 = 10640;
wxSizer *ConsistencyCheck_ExistsNoTU_DlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_BITMAPBUTTON_MOVE_BACK = 10641;
const int ID_BITMAPBUTTON_MOVE_FORWARD = 10642;
const int ID_BUTTON_OPEN_HTML_FILE = 10643;
const int ID_TEXTCTRL_HTML_FILE_PATH = 10644;
const int ID_HTML_WINDOW = 10645;
wxSizer *HtmlFileViewerDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_SRC = 10646;
const int ID_TEXTCTRL_SRC_LANG = 10647;
const int ID_TEXT_NOTCHANGED = 10648;
const int ID_TEXT_TGT_CODE = 10649;
const int ID_LISTBOX_TGT = 10650;
const int ID_TEXT_GLOSS_CODE = 10651;
const int ID_LISTBOX_GLOSS = 10652;
const int ID_TEXTCTRL_TELL = 10653;
const int ID_TEXTCTRL_MSG2 = 10654;
wxSizer *LiftLangFilterFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_RADIOBOX_KB_EXPORT_IMPORT_OPTIONS = 10655;
extern wxSizer *pKBExpImpCheckBoxesSizer;
wxSizer *KBExportImportOptionsFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_SELECTED_AI_PROJECT = 10656;
const int ID_BUTTON_TELL_ME_MORE = 10657;
const int ID_RADIOBUTTON_TURN_COLLAB_ON = 10658;
const int ID_TEXTCTRL_NOT_INSTALLED_ERROR_MSG = 10659;
const int ID_RADIOBUTTON_TURN_COLLAB_OFF = 10660;
const int ID_RADIOBUTTON_READ_ONLY_MODE = 10661;
wxSizer *ChooseCollabOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_USE_THIS_DIALOG = 10662;
const int ID_COMBO_AI_PROJECTS = 10663;
const int ID_BUTTON_CREATE_NEW_AI_PROJECT = 10664;
const int ID_TEXT_STATIC_LIST_OF_PROJECTS = 10665;
const int ID_RADIOBOX_EXTERNAL_SCRIPTURE_EDITOR = 10666;
const int IDC_LIST_OF_COLLAB_PROJECTS = 10667;
const int ID_TEXTCTRL_AS_STATIC_TOP_NOTE = 10668;
const int ID_TEXT_STATIC_SELECT_WHICH_PROJECTS = 10669;
const int ID_TEXT_STATIC_SRC_FROM_THIS_PROJECT = 10670;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_SRC_PROJ = 10671;
const int ID_BUTTON_SELECT_FROM_LIST_SOURCE_PROJ = 10672;
const int ID_RADIO_BY_CHAPTER_ONLY = 10673;
const int ID_RADIO_BY_WHOLE_BOOK = 10674;
const int ID_TEXT_STATIC_TARGET_TO_THIS_PROJECT = 10675;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_TGT_PROJ = 10676;
const int ID_BUTTON_SELECT_FROM_LIST_TARGET_PROJ = 10677;
const int ID_TEXT_STATIC_TO_THIS_FT_PROJECT = 10678;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_FREE_TRANS_PROJ = 10679;
const int ID_BUTTON_SELECT_FROM_LIST_FREE_TRANS_PROJ = 10680;
const int ID_BUTTON_NO_FREE_TRANS = 10681;
const int ID_LINE_2 = 10682;
const int ID_BUTTON_SAVE_SETUP_FOR_THIS_PROJ_NOW = 10683;
const int ID_BUTTON_REMOVE_THIS_PROJ_FROM_COLLAB = 10684;
wxSizer *SetupCollaborationBetweenAIandEditorFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_TOP_INFO_1 = 10685;
const int ID_TEXT_TOP_INFO_2 = 10686;
const int ID_TEXTCTRL_SRC_LANG_NAME = 10687;
const int ID_TEXTCTRL_TGT_LANG_NAME = 10688;
const int ID_TEXT_AS_STATIC_NEW_AI_PROJ_NAME = 10689;
const int ID_TEXTCTRL_NEW_AI_PROJ_NAME = 10690;
wxSizer *CreateNewAIProjForCollabFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_STATIC_LAST_BOOKNAME = 10691;
const int ID_TEXTCTRL_OLD_BOOKNAME = 10692;
const int ID_TEXT_STATIC_TOP_MSG = 10693;
const int ID_RADIO_USE_LAST_BOOKNAME = 10694;
const int ID_RADIO_BOOKNAME_IS_INAPPROPRIATE = 10695;
const int ID_RADIO_SUGGESTED_BOOKNAME_ACCEPTABLE = 10696;
const int ID_RADIO_DIFFERENT_BOOKNAME = 10697;
const int ID_TEXTCTRL_BOOKNAME = 10698;
wxSizer *BookNameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_SPINCTRL_RECEIVE = 10699;
const int ID_RADIO_SHARING_OFF = 10700;
const int ID_GET_RECENT = 10701;
const int ID_GET_ALL = 10702;
const int ID_SEND_ALL = 10703;
wxSizer *kb_sharing_dlg_func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LST_TOOLBAR_BUTTONS = 10704;
const int ID_BMP_TOOLBAR_SMALL = 10705;
const int ID_BMP_TOOLBAR_MEDIUM = 10706;
const int ID_BMP_TOOLBAR_LARGE = 10707;
const int ID_RDO_TOOLBAR_SMALL = 10708;
const int ID_RDO_TOOLBAR_MEDIUM = 10709;
const int ID_RDO_TOOLBAR_LARGE = 10710;
const int ID_CBO_TOOLBAR_ICON = 10711;
const int ID_BTN_TOOLBAR_MINIMAL = 10712;
const int ID_TOOLBAR_RESET = 10713;
wxSizer *ToolbarPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_MYLISTBOX_TRANSLATIONS = 10714;
const int IDC_EDIT_MATCHED_SOURCE = 10715;
const int IDC_EDIT_REFERENCES = 10716;
const int ID_BUTTON_CANCEL_ASK = 10717;
const int ID_BUTTON_CANCEL_AND_SELECT = 10718;
const int IDC_EDIT_NEW_TRANSLATION = 10719;
wxSizer *ChooseTranslationDlgFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_COMMIT_COMMENT = 10720;
const int IDC_COMMIT_BLURB = 10721;
wxSizer *DVCSDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_COMMITTER = 10722;
const int ID_VERSION_DATE = 10723;
const int ID_VERSION_COMMENT = 10724;
const int ID_BTN_PREV = 10725;
const int ID_BTN_NEXT = 10726;
const int ID_ACCEPT = 10727;
const int ID_LATEST = 10728;
wxSizer *DVCSNavDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LST_VERSIONS = 10729;
wxSizer *DVCSLogDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_USERNAME_MSG = 10730;
const int ID_TEXTCTRL_USERNAME = 10731;
const int ID_TEXTCTRL_USERNAME_INFORMAL_MSG = 10732;
const int ID_TEXTCTRL_USERNAME_INFORMAL = 10733;
wxSizer *UsernameInputFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LISTBOX_CUR_USERS = 10734;
const int ID_THE_USERNAME = 10735;
const int ID_TEXTCTRL_INFORMAL_NAME = 10736;
const int ID_TEXTCTRL_PASSWORD = 10737;
const int ID_TEXTCTRL_PASSWORD_TWO = 10738;
const int ID_CHECKBOX_USERADMIN = 10739;
const int ID_CHECKBOX_KBADMIN = 10740;
const int ID_BUTTON_CLEAR_CONTROLS = 10741;
const int ID_BUTTON_ADD_USER = 10742;
const int ID_BUTTON_EDIT_USER = 10743;
const int ID_BUTTON_REMOVE_USER = 10744;
wxSizer *SharedKBManagerUsersPageFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_CONNECTED_TO = 10745;
const int ID_TEXT_SERVER_URL = 10746;
const int ID_SHAREDKB_MANAGER_DLG = 10747;
wxSizer *SharedKBManagerNotebookFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_RADIOBUTTON_TYPE1_KB = 10748;
const int ID_RADIOBUTTON_TYPE2_KB = 10749;
const int ID_TEXT_EXISTING_KB_CODE_PAIRS = 10750;
const int ID_LISTBOX_KB_CODE_PAIRS = 10751;
const int ID_TEXTCTRL_CREATED_BY = 10752;
const int ID_BUTTON_LOOKUP_THE_CODES = 10753;
const int ID_BUTTON_RFC5646 = 10754;
const int ID_BUTTON_CLEAR_LIST_SELECTION = 10755;
const int ID_TEXTCTRL_SRC = 10756;
const int ID_TEXT_TGT_LANG_CODE = 10757;
const int ID_TEXTCTRL_NONSRC = 10758;
const int ID_BUTTON_ADD_DEFINITION = 10759;
const int ID_BUTTON_CLEAR_BOXES = 10760;
const int ID_BUTTON_UPDATE_LANG_CODES = 10761;
const int ID_BUTTON_REMOVE_SELECTED_DEFINITION = 10762;
wxSizer *SharedKBManager_CreateKbsPageFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_SERVER_URL_LABEL_STATELESS = 10763;
const int ID_TEXTCTRL_SERVER_URL_STATELESS = 10764;
const int ID_TEXT_USERNAME_LABEL_STATELESS = 10765;
const int ID_TEXT_USERNAME_MSG_LABEL_STATELESS = 10766;
const int ID_TEXTCTRL_USERNAME_STATELESS = 10767;
const int ID_TEXT_ASKED_STATELESS = 10768;
wxSizer *kb_sharing_stateless_setup_func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_INDICATE_SHARE = 10769;
const int ID_CHECKBOX_SHARE_MY_TGT_KB = 10770;
const int ID_CHECKBOX_SHARE_MY_GLOSS_KB = 10771;
const int ID_BUTTON_REMOVE_MY_SETUP = 10772;
wxSizer *kb_share_setup_or_remove_func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *m_LIST_CTRL_SIZER;
const int ID_LISTCTRL_BULK_DEL = 10773;
const int ID_RADIO_ORGANISE_BY_KEYS = 10774;
const int ID_RADIO_SIMPLY_TARGET_ALPHABETICAL = 10775;
const int ID_BUTTON_SAVE_ENTRYLIST_TO_FILE = 10776;
wxSizer *Bulk_Delete_Pairs_Func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_TELL_USER = 10777;
const int ID_RADIO_JOIN_TO_NEXT = 10778;
const int ID_RADIO_JOIN_TO_PREVIOUS = 10779;
const int ID_RADIO_SPLIT_OFF = 10780;
wxSizer *FTAdjustFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_SRC_TRANS = 10781;
const int ID_TEXTCTRL_FREE_TRANS = 10782;
const int ID_TEXTCTRL_CURRENT_SECTION = 10783;
const int ID_TEXTCTRL_NEXT_SECTION = 10784;
const int ID_BUTTON_SPLIT_HERE = 10785;
wxSizer *SplitterDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_BUTTON_GUESSER_DLG_EXPLAIN = 10786;
const int ID_RADIO_SUFFIXES_LIST = 10787;
const int ID_RADIO_PREFIXES_LIST = 10788;
const int ID_LISTCTRL_SRC_TGT_AFFIX_PAIR = 10789;
const int ID_TEXT_TGT = 10790;
const int ID_STATICTEXT_SRC_SUFFIX = 10791;
const int ID_TEXT_SRC_AFFIX = 10792;
const int ID_STATICTEXT_SRC_PREFIX = 10793;
const int ID_STATICTEXT_TGT_SUFFIX = 10794;
const int ID_TEXT_TGT_AFFIX = 10795;
const int ID_STATICTEXT_TGT_PREFIX = 10796;
const int ID_BUTTON_ADD = 10797;
const int ID_BUTTON_INSERT = 10798;
wxSizer *GuesserAffixListDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_BUTTON_COPY_TO_CLIPBOARD = 10799;
const int ID_BUTTON_COPY_FREETRANS_TO_CLIPBOARD = 10800;
const int ID_BUTTON_CLIPBOARD_ADAPT_CLOSE = 10801;
wxSizer *ClipboardAdaptBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

const int ID_FILE_MENU = 10802;
const int ID_SAVE_AS = 10803;
const int ID_FILE_SAVE_COMMIT = 10804;
const int ID_FILE_PACK_DOC = 10805;
const int ID_FILE_UNPACK_DOC = 10806;
const int ID_MENU = 10807;
const int ID_FILE_STARTUP_WIZARD = 10808;
const int ID_FILE_CLOSEKB = 10809;
const int ID_FILE_CHANGEFOLDER = 10810;
const int ID_FILE_SAVEKB = 10811;
const int ID_FILE_BACKUP_KB = 10812;
const int ID_FILE_RESTORE_KB = 10813;
const int ID_FILE_REVERT_FILE = 10814;
const int ID_FILE_LIST_VERSIONS = 10815;
const int ID_FILE_TAKE_OWNERSHIP = 10816;
const int ID_EDIT_MENU = 10817;
const int ID_EDIT_CUT = 10818;
const int ID_EDIT_COPY = 10819;
const int ID_EDIT_PASTE = 10820;
const int ID_GO_TO = 10821;
const int ID_EDIT_SOURCE_TEXT = 10822;
const int ID_EDIT_CONSISTENCY_CHECK = 10823;
const int ID_MENU_CHANGE_USERNAME = 10824;
const int ID_EDITMENU_CHANGE_PUNCTS_MKRS_PLACE = 10825;
const int ID_EDIT_MOVE_NOTE_FORWARD = 10826;
const int ID_EDIT_MOVE_NOTE_BACKWARD = 10827;
const int ID_VIEW_MENU = 10828;
const int ID_VIEW_TOOLBAR = 10829;
const int ID_VIEW_STATUS_BAR = 10830;
const int ID_VIEW_COMPOSE_BAR = 10831;
const int ID_VIEW_MODE_BAR = 10832;
const int ID_COPY_SOURCE = 10833;
const int ID_MARKER_WRAPS_STRIP = 10834;
const int ID_UNITS = 10835;
const int ID_CHANGE_INTERFACE_LANGUAGE = 10836;
const int ID_VIEW_SHOW_ADMIN_MENU = 10837;
const int ID_TOOLS_MENU = 10838;
const int ID_TOOLS_CLIPBOARD_ADAPT = 10839;
const int ID_TOOLS_DEFINE_CC = 10840;
const int ID_UNLOAD_CC_TABLES = 10841;
const int ID_USE_CC = 10842;
const int ID_ACCEPT_CHANGES = 10843;
const int ID_TOOLS_DEFINE_SILCONVERTER = 10844;
const int ID_USE_SILCONVERTER = 10845;
const int ID_TOOLS_KB_EDITOR = 10846;
const int ID_TOOLS_AUTO_CAPITALIZATION = 10847;
const int ID_MENU_UPPER_AVAIL = 10848;
const int ID_RETRANS_REPORT = 10849;
const int ID_TOOLS_SPLIT_DOC = 10850;
const int ID_TOOLS_JOIN_DOCS = 10851;
const int ID_TOOLS_MOVE_DOC = 10852;
const int ID_EXPORT_IMPORT_MENU = 10853;
const int ID_FILE_EXPORT_SOURCE = 10854;
const int ID_FILE_EXPORT = 10855;
const int ID_FILE_EXPORT_TO_RTF = 10856;
const int ID_EXPORT_GLOSSES = 10857;
const int ID_EXPORT_FREE_TRANS = 10858;
const int ID_FILE_EXPORT_KB = 10859;
const int ID_IMPORT_TO_KB = 10860;
const int ID_MENU_IMPORT_EDITED_SOURCE_TEXT = 10861;
const int ID_ADVANCED_MENU = 10862;
const int ID_ADVANCED_SEE_GLOSSES = 10863;
const int ID_ADVANCED_GLOSSING_USES_NAV_FONT = 10864;
const int ID_ADVANCED_TRANSFORM_ADAPTATIONS_INTO_GLOSSES = 10865;
const int ID_ADVANCED_DELAY = 10866;
const int ID_ADVANCED_BOOKMODE = 10867;
const int ID_ADVANCED_FREE_TRANSLATION_MODE = 10868;
const int ID_FORCE_VERSE_SECTIONING = 10869;
const int ID_ADVANCED_TARGET_TEXT_IS_DEFAULT = 10870;
const int ID_ADVANCED_GLOSS_TEXT_IS_DEFAULT = 10871;
const int ID_ADVANCED_REMOVE_FILTERED_FREE_TRANSLATIONS = 10872;
const int ID_ADVANCED_COLLECT_BACKTRANSLATIONS = 10873;
const int ID_ADVANCED_REMOVE_FILTERED_BACKTRANSLATIONS = 10874;
const int ID_ADVANCED_USETRANSLITERATIONMODE = 10875;
const int ID_ADVANCED_SENDSYNCHRONIZEDSCROLLINGMESSAGES = 10876;
const int ID_ADVANCED_RECEIVESYNCHRONIZEDSCROLLINGMESSAGES = 10877;
const int ID_LAYOUT_MENU = 10878;
const int ID_ALIGNMENT = 10879;
const int ID_HELP_MENU = 10880;
const int ID_MENU_AI_QUICK_START = 10881;
const int ID_REPORT_A_PROBLEM = 10882;
const int ID_GIVE_FEEDBACK = 10883;
const int ID_HELP_USE_TOOLTIPS = 10884;
const int ID_ADMINISTRATOR_MENU = 10885;
const int ID_MENU_HELP_FOR_ADMINISTRATORS = 10886;
const int ID_SETUP_EDITOR_COLLABORATION = 10887;
const int ID_EDIT_USER_MENU_SETTINGS_PROFILE = 10888;
const int ID_MENU_TEMP_TURN_OFF_CURRENT_PROFILE = 10889;
const int ID_ASSIGN_LOCATIONS_FOR_INPUTS_OUTPUTS = 10890;
const int ID_MOVE_OR_COPY_FOLDERS_OR_FILES = 10891;
const int ID_SET_PASSWORD_MENU = 10892;
const int ID_CUSTOM_WORK_FOLDER_LOCATION = 10893;
const int ID_LOCK_CUSTOM_LOCATION = 10894;
const int ID_UNLOCK_CUSTOM_LOCATION = 10895;
const int ID_LOCAL_WORK_FOLDER_MENU = 10896;
const int ID_DVCS_VERSION = 10897;
const int ID_MENU_KBSHARINGMGR = 10898;
wxMenuBar *AIMenuBarFunc();

// Declare toolbar functions

const int ID_BUTTON_GUESSER = 10899;
const int ID_BUTTON_CREATE_NOTE = 10900;
const int ID_BUTTON_PREV_NOTE = 10901;
const int ID_BUTTON_NEXT_NOTE = 10902;
const int ID_BUTTON_DELETE_ALL_NOTES = 10903;
const int ID_BUTTON_RESPECTING_BDRY = 10904;
const int ID_BUTTON_SHOWING_PUNCT = 10905;
const int ID_BUTTON_TO_END = 10906;
const int ID_BUTTON_TO_START = 10907;
const int ID_BUTTON_STEP_DOWN = 10908;
const int ID_BUTTON_STEP_UP = 10909;
const int ID_BUTTON_BACK = 10910;
const int ID_BUTTON_MERGE = 10911;
const int ID_BUTTON_RETRANSLATION = 10912;
const int ID_BUTTON_EDIT_RETRANSLATION = 10913;
const int ID_REMOVE_RETRANSLATION = 10914;
const int ID_BUTTON_NULL_SRC = 10915;
const int ID_BUTTON_REMOVE_NULL_SRCPHRASE = 10916;
const int ID_BUTTON_CHOOSE_TRANSLATION = 10917;
const int ID_SHOWING_ALL = 10918;
const int ID_BUTTON_EARLIER_TRANSLATION = 10919;
const int ID_BUTTON_NO_PUNCT_COPY = 10920;
void AIToolBarFunc( wxToolBar *parent );

void AIToolBar32x30Func( wxToolBar *parent );

// Declare bitmap functions

wxBitmap AIToolBarBitmapsUnToggledFunc( size_t index );

const int ID_BITMAP_FOLDERAI = 10921;
const int ID_BITMAP_FILEAI = 10922;
const int ID_BITMAP_EMPTY_FOLDER = 10923;
wxBitmap AIMainFrameIcons( size_t index );

const int ID_BUTTON_IGNORING_BDRY = 10924;
const int ID_BUTTON_HIDING_PUNCT = 10925;
const int ID_SHOWING_TGT = 10926;
const int ID_BUTTON_ENABLE_PUNCT_COPY = 10927;
wxBitmap AIToolBarBitmapsToggledFunc( size_t index );

wxBitmap WhichFilesBitmapsFunc( size_t index );

wxBitmap AIToolBarBitmapsToggled32x30Func( size_t index );

wxBitmap AIToolBarBitmapsUnToggled32x30Func( size_t index );

wxBitmap HtmlWindowBitmapsFunc( size_t index );

const int ID_BITMAP_CHBOX_OFF = 10928;
const int ID_BITMAP_CHBOX_ON = 10929;
wxBitmap BulkKbDeleteFunc( size_t index );

#endif

// End of generated file
