//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: Adapt_It.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_Adapt_It_H__
#define __WDR_Adapt_It_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "Adapt_It_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>
#include <wx/collpane.h>
#include <wx/hyperlink.h>
#include <wx/animate.h>
#include <wx/filepicker.h>
#include <wx/datectrl.h>
#include <wx/fontpicker.h>
#include <wx/clrpicker.h>
#include <wx/srchctrl.h>
#if wxCHECK_VERSION(2,9,0)
#include <wx/editlbox.h>
#endif

// Declare window functions

extern wxSizer *ID_ABOUT_TOP_AREA;
const int ID_ABOUT_AI_BMP = 850;
const int ID_TEXT = -1;
const int ID_ABOUT_VERSION_LABEL = 0;
const int ID_ABOUT_VERSION_NUM = 1;
const int ID_ABOUT_VERSION_DATE = 2;
const int ID_STATIC_UNICODE_OR_ANSI = 3;
const int ID_STATIC_WX_VERSION_USED = 4;
const int ID_LINE = 5;
const int ID_STATIC_UI_LANGUAGE = 6;
const int ID_STATIC_HOST_OS = 7;
const int ID_STATIC_SYS_LANGUAGE = 8;
const int ID_STATIC_SYS_LOCALE_NAME = 9;
const int ID_STATIC_CANONICAL_LOCALE_NAME = 10;
const int ID_STATIC_SYS_ENCODING_NAME = 11;
const int ID_STATIC_SYSTEM_LAYOUT_DIR = 12;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *ID_CONTROLBAR_1_LINE_SIZER;
const int IDC_RADIO_DRAFTING = 13;
const int IDC_RADIO_REVIEWING = 14;
const int IDC_CHECK_SINGLE_STEP = 15;
const int IDC_CHECK_KB_SAVE = 16;
const int IDC_CHECK_FORCE_ASK = 17;
const int IDC_BUTTON_NO_ADAPT = 18;
const int IDC_STATIC = 19;
const int IDC_EDIT_DELAY = 20;
const int IDC_CHECK_ISGLOSSING = 21;
wxSizer *ControlBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_COMPOSE = 22;
const int IDC_BUTTON_SHORTEN = 23;
const int IDC_BUTTON_PREV = 24;
const int IDC_BUTTON_LENGTHEN = 25;
const int IDC_BUTTON_NEXT = 26;
const int IDC_BUTTON_REMOVE = 27;
const int IDC_BUTTON_APPLY = 28;
const int IDC_STATIC_SECTION_DEF = 29;
const int IDC_RADIO_PUNCT_SECTION = 30;
const int IDC_RADIO_VERSE_SECTION = 31;
const int IDC_BUTTON_CLEAR = 32;
const int IDC_BUTTON_SELECT_ALL = 33;
wxSizer *ComposeBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LISTBOX_ADAPTIONS = 34;
wxSizer *OpenExistingProjectDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_FILENAME = 35;
const int ID_TEXT_INVALID_CHARACTERS = 36;
wxSizer *GetOutputFilenameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SOURCE_LANGUAGE = 37;
const int ID_EDIT_SOURCE_LANG_CODE = 38;
const int IDC_TARGET_LANGUAGE = 39;
const int ID_EDIT_TARGET_LANG_CODE = 40;
const int ID_BUTTON_LOOKUP_CODES = 41;
wxSizer *LanguagesPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SOURCE_FONTNAME = 42;
const int IDC_CHECK_SRC_RTL = 43;
const int IDC_SOURCE_SIZE = 44;
const int IDC_SOURCE_LANG = 45;
const int IDC_BUTTON_SOURCE_COLOR = 46;
const int ID_BUTTON_CHANGE_SRC_ENCODING = 47;
const int IDC_TARGET_FONTNAME = 48;
const int IDC_CHECK_TGT_RTL = 49;
const int IDC_TARGET_SIZE = 50;
const int IDC_TARGET_LANG = 51;
const int IDC_BUTTON_TARGET_COLOR = 52;
const int ID_BUTTON_CHANGE_TGT_ENCODING = 53;
const int IDC_NAVTEXT_FONTNAME = 54;
const int IDC_CHECK_NAVTEXT_RTL = 55;
const int IDC_NAVTEXT_SIZE = 56;
const int IDC_CHANGE_NAV_TEXT = 57;
const int IDC_BUTTON_NAV_TEXT_COLOR = 58;
const int ID_BUTTON_CHANGE_NAV_ENCODING = 59;
const int ID_TEXTCTRL_AS_STATIC_FONTPAGE = 60;
const int IDC_BUTTON_SPECTEXTCOLOR = 61;
const int IDC_RETRANSLATION_BUTTON = 62;
const int ID_BUTTON_TEXT_DIFFS = 63;
wxSizer *FontsPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_PLEASE_WAIT = 64;
wxSizer *WaitDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_ACCEPTED = 65;
const int IDC_BUTTON_REJECT = 66;
const int IDC_BUTTON_ACCEPT = 67;
const int ID_BUTTON_REJECT_ALL_FILES = 68;
const int ID_BUTTON_ACCEPT_ALL_FILES = 69;
const int IDC_LIST_REJECTED = 70;
wxSizer *WhichFilesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES1 = 71;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES2 = 72;
const int ID_TEXTCTRL_TRANSFORM_TO_GLOSSES3 = 73;
wxSizer *TransformToGlossesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECK_SOURCE_USES_CAPS = 74;
const int ID_CHECK_USE_AUTO_CAPS = 75;
const int ID_TEXTCTRL_AS_CASE_PAGE_STATIC_TEXT = 76;
const int ID_TEXT_SL = 77;
const int ID_TEXT_TL = 78;
const int ID_TEXT_GL = 79;
const int IDC_EDIT_SRC_CASE_EQUIVALENCES = 80;
const int IDC_EDIT_TGT_CASE_EQUIVALENCES = 81;
const int IDC_EDIT_GLOSS_CASE_EQUIVALENCES = 82;
const int IDC_BUTTON_CLEAR_SRC_LIST = 83;
const int IDC_BUTTON_CLEAR_TGT_LIST = 84;
const int IDC_BUTTON_CLEAR_GLOSS_LIST = 85;
const int IDC_BUTTON_SRC_SET_ENGLISH = 86;
const int IDC_BUTTON_TGT_SET_ENGLISH = 87;
const int IDC_BUTTON_GLOSS_SET_ENGLISH = 88;
const int IDC_BUTTON_SRC_COPY_TO_NEXT = 89;
const int IDC_BUTTON_TGT_COPY_TO_NEXT = 90;
const int IDC_BUTTON_GLOSS_COPY_TO_NEXT = 91;
const int IDC_BUTTON_SRC_COPY_TO_GLOSS = 92;
wxSizer *CaseEquivDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_WELCOME_TO = 93;
const int IDC_EDIT_ADAPT_IT = 94;
const int ID_TEXTCTRL_AS_STATIC_WELCOME = 95;
const int IDC_CHECK_NOLONGER_SHOW = 96;
wxSizer *WelcomeDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_DOCPAGE = 97;
const int IDC_STATIC_WHICH_MODE = 98;
const int IDC_BUTTON_WHAT_IS_DOC = 99;
const int IDC_STATIC_WHICH_FOLDER = 100;
const int IDC_LIST_NEWDOC_AND_EXISTINGDOC = 101;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES = 102;
const int IDC_CHANGE_FOLDER_BTN = 103;
const int IDC_CHECK_FORCE_UTF8 = 104;
wxSizer *DocPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_PROJECTPAGE = 105;
const int IDC_BUTTON_WHAT_IS_PROJECT = 106;
const int IDC_LIST_NEW_AND_EXISTING = 107;
const int ID_TEXTCTRL_USERNAME_MSG = 108;
const int ID_TEXTCTRL_USERNAME = 109;
const int ID_TEXTCTRL_USERNAME_INFORMAL_MSG = 110;
const int ID_TEXTCTRL_USERNAME_INFORMAL = 111;
wxSizer *ProjectPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_SRC = 112;
const int IDC_LIST_PUNCTS = 113;
const int ID_TEXTCTRL_AS_STATIC_PLACE_INT_PUNCT = 114;
const int IDC_EDIT_TGT = 115;
const int IDC_BUTTON_PLACE = 116;
wxSizer *PlaceInternalPunctDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_INCHES = 117;
const int IDC_RADIO_CM = 118;
wxSizer *UnitsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_MATCHED_SOURCE = 119;
const int IDC_MYLISTBOX_TRANSLATIONS = 120;
const int IDC_EDIT_REFERENCES = 121;
const int IDC_BUTTON_MOVE_UP = 122;
const int IDC_BUTTON_MOVE_DOWN = 123;
const int IDC_BUTTON_CANCEL_ASK = 124;
const int IDC_BUTTON_CANCEL_AND_SELECT = 125;
const int IDC_EDIT_NEW_TRANSLATION = 126;
wxSizer *ChooseTranslationDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_SRC = 127;
const int IDC_EDIT_PRECONTEXT = 128;
const int IDC_EDIT_SOURCE_TEXT = 129;
const int IDC_EDIT_RETRANSLATION = 130;
const int IDC_COPY_RETRANSLATION_TO_CLIPBOARD = 131;
const int IDC_BUTTON_TOGGLE = 132;
const int IDC_STATIC_TGT = 133;
const int IDC_EDIT_FOLLCONTEXT = 134;
wxSizer *RetranslationDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_SRC_TEXT = 135;
const int IDC_EDIT_TGT_TEXT = 136;
const int IDC_SPIN_CHAPTER = 137;
const int IDC_SPIN_VERSE = 138;
const int IDC_GET_CHVERSE_TEXT = 139;
const int IDC_CLOSE_AND_JUMP = 140;
const int IDC_SHOW_MORE = 141;
const int IDC_SHOW_LESS = 142;
const int IDC_STATIC_BEGIN = 143;
const int IDC_STATIC_END = 144;
wxSizer *EarlierTransDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_CHECK_KB_BACKUP = 145;
const int IDC_CHECK_BAKUP_DOC = 146;
const int ID_TEXTCTRL_AS_STATIC_BACKUPS_AND_KB_PAGE = 147;
const int IDC_EDIT_SRC_NAME = 148;
const int IDC_EDIT_TGT_NAME = 149;
const int IDC_EDIT_GLS_NAME = 150;
const int ID_EDIT_GLOSS_LANG_CODE = 151;
const int ID_EDIT_FRTR_NAME = 152;
const int ID_EDIT_FRTR_LANG_CODE = 153;
const int IDC_RADIO_ADAPT_BEFORE_GLOSS = 154;
const int IDC_RADIO_GLOSS_BEFORE_ADAPT = 155;
const int IDC_CHECK_LEGACY_SRC_TEXT_COPY = 156;
wxSizer *BackupsAndKBPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int STATIC_TEXT_V4 = 157;
const int IDC_EDIT_LEADING = 158;
const int STATIC_TEXT_V5 = 159;
const int IDC_EDIT_GAP_WIDTH = 160;
const int STATIC_TEXT_V6 = 161;
const int IDC_EDIT_LEFTMARGIN = 162;
const int STATIC_TEXT_V7 = 163;
const int IDC_EDIT_MULTIPLIER = 164;
const int IDC_EDIT_DIALOGFONTSIZE = 165;
const int IDC_CHECK_WELCOME_VISIBLE = 166;
const int IDC_CHECK_HIGHLIGHT_AUTO_INSERTED_TRANSLATIONS = 167;
const int ID_PANEL_AUTO_INSERT_COLOR = 168;
const int IDC_BUTTON_CHOOSE_HIGHLIGHT_COLOR = 169;
const int IDC_CHECK_SHOW_ADMIN_MENU = 170;
const int ID_RADIOBOX_SCROLL_INTO_VIEW = 171;
const int ID_RADIOBOX_LEGACY_LOOKUP = 172;
wxSizer *ViewPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

wxSizer *UnitsPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_AUTOSAVE = 173;
const int IDC_CHECK_NO_AUTOSAVE = 174;
const int IDC_RADIO_BY_MINUTES = 175;
const int IDC_EDIT_MINUTES = 176;
const int IDC_SPIN_MINUTES = 177;
const int IDC_RADIO_BY_MOVES = 178;
const int IDC_EDIT_MOVES = 179;
const int IDC_SPIN_MOVES = 180;
const int IDC_EDIT_KB_MINUTES = 181;
const int IDC_SPIN_KB_MINUTES = 182;
wxSizer *AutoSavingPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_DIV1 = 183;
const int IDC_RADIO_DIV2 = 184;
const int IDC_RADIO_DIV3 = 185;
const int IDC_RADIO_DIV4 = 186;
const int IDC_RADIO_DIV5 = 187;
const int IDC_COMBO_CHOOSE_BOOK = 188;
const int ID_TEXT_AS_STATIC = 189;
wxSizer *WhichBookDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_MSG = 190;
const int IDC_EDIT_ERR_XML = 191;
const int IDC_STATIC_LBL = 192;
const int IDC_EDIT_OFFSET = 193;
wxSizer *XMLErrorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_ED_SILCONVERTER_NAME = 194;
const int IDC_BTN_SELECT_SILCONVERTER = 195;
const int IDC_ED_SILCONVERTER_INFO = 196;
const int IDC_BTN_CLEAR_SILCONVERTER = 197;
wxSizer *SilConvertersDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_FOLDER_DOCS = 198;
const int IDC_LIST_FOLDER_DOCS = 199;
const int IDC_BUTTON_NEXT_CHAPTER = 200;
const int IDC_BUTTON_SPLIT_NOW = 201;
const int IDC_STATIC_SPLITTING_WAIT = 202;
const int IDC_RADIO_PHRASEBOX_LOCATION = 203;
const int IDC_RADIO_CHAPTER_SFMARKER = 204;
const int IDC_RADIO_DIVIDE_INTO_CHAPTERS = 205;
const int IDC_STATIC_SPLIT_NAME = 206;
const int IDC_EDIT1 = 207;
const int IDC_STATIC_REMAIN_NAME = 208;
const int IDC_EDIT2 = 209;
wxSizer *SplitDialogFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_MARKERS = 210;
const int IDC_TEXTCTRL_AS_STATIC_PLACE_INT_MKRS = 211;
wxSizer *PlaceInternalMarkersDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_NOTE = 212;
const int IDC_EDIT_FIND_TEXT = 213;
const int IDC_FIND_NEXT_BTN = 214;
const int IDC_LAST_BTN = 215;
const int IDC_NEXT_BTN = 216;
const int IDC_PREV_BTN = 217;
const int IDC_FIRST_BTN = 218;
const int IDC_DELETE_BTN = 219;
wxSizer *NoteDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_COLLECT_BT = 220;
const int IDC_RADIO_COLLECT_ADAPTATIONS = 221;
const int IDC_RADIO_COLLECT_GLOSSES = 222;
wxSizer *CollectBackTranslationsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_SPIN_DELAY_TICKS = 223;
wxSizer *SetDelayDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_EXPORT_ALL = 224;
const int IDC_RADIO_EXPORT_SELECTED_MARKERS = 225;
const int ID_TEXTCTRL_AS_STATIC_EXPORT_OPTIONS = 226;
const int IDC_LIST_SFMS = 227;
const int IDC_BUTTON_EXCLUDE_FROM_EXPORT = 228;
const int IDC_BUTTON_INCLUDE_IN_EXPORT = 229;
const int IDC_BUTTON_UNDO = 230;
const int IDC_STATIC_SPECIAL_NOTE = 231;
const int IDC_CHECK_PLACE_FREE_TRANS = 232;
const int IDC_CHECK_INTERLINEAR_PLACE_FREE_TRANS = 233;
const int IDC_CHECK_PLACE_BACK_TRANS = 234;
const int IDC_CHECK_INTERLINEAR_PLACE_BACK_TRANS = 235;
const int IDC_CHECK_PLACE_AI_NOTES = 236;
const int IDC_CHECK_INTERLINEAR_PLACE_AI_NOTES = 237;
wxSizer *ExportOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_PNLEXPORT = 238;
const int ID_BUTTON_CHANGE_BOOK_NAME = 239;
const int ID_LBLEXPORTTYPEDESCRIPTION = 240;
const int ID_RDOFILTEROFF = 241;
const int ID_RDOFILTERON = 242;
const int ID_BTNFILTEROPTIONS = 243;
const int ID_CHKPROJECTNAMEPREFIX = 244;
const int ID_CHKTARGETTEXTPREFIX = 245;
const int ID_CHKDATETIMESUFFIX = 246;
wxSizer *ExportSaveAsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_CHECK_INCLUDE_NAV_TEXT = 247;
const int IDC_CHECK_INCLUDE_SOURCE_TEXT = 248;
const int IDC_CHECK_INCLUDE_TARGET_TEXT = 249;
const int IDC_CHECK_INCLUDE_GLS_TEXT = 250;
const int ID_TEXTCTRL_AS_STATIC_EXP_INTERLINEAR = 251;
const int IDC_RADIO_PORTRAIT = 252;
const int IDC_RADIO_LANDSCAPE = 253;
const int IDC_RADIO_OUTPUT_ALL = 254;
const int IDC_RADIO_OUTPUT_CHAPTER_VERSE_RANGE = 255;
const int IDC_EDIT_FROM_CHAPTER = 256;
const int IDC_EDIT_FROM_VERSE = 257;
const int IDC_EDIT_TO_CHAPTER = 258;
const int IDC_EDIT_TO_VERSE = 259;
const int IDC_RADIO_OUTPUT_PRELIM = 260;
const int IDC_RADIO_OUTPUT_FINAL = 261;
const int ID_CHECK_NEW_TABLES_FOR_NEWLINE_MARKERS = 262;
const int ID_CHECK_CENTER_TABLES_FOR_CENTERED_MARKERS = 263;
const int ID_CHECKBOX_PREFIX_EXPORT_PROJ_NAME = 264;
const int ID_CHECKBOX_PREFIX_EXPORT_TYPE = 265;
const int ID_CHECKBOX_SUFFIX_EXPORT_DATETIME_STAMP = 266;
const int IDC_BUTTON_RTF_EXPORT_FILTER_OPTIONS = 267;
wxSizer *ExportInterlinearDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_MARKER = 268;
const int IDC_EDIT_MARKER_TEXT = 269;
const int IDC_REMOVE_BTN = 270;
const int IDC_BUTTON_SWITCH_ENCODING = 271;
const int IDC_LIST_MARKER_END = 272;
const int IDC_STATIC_MARKER_DESCRIPTION = 273;
const int IDC_STATIC_MARKER_STATUS = 274;
wxSizer *ViewFilteredMaterialDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_CHAPTER = 275;
const int IDC_EDIT_VERSE = 276;
wxSizer *GoToDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_MAIN_MSG = 277;
const int IDC_EDIT_KEY = 278;
extern wxSizer *m_topRightBoxLabel;
const int IDC_EDIT_ADAPTATION = 279;
const int IDC_RADIO_ACCEPT_HERE = 280;
const int ID_TEXT_NO_ADAPT_MSG = 281;
const int IDC_RADIO_CHANGE_INSTEAD = 282;
const int IDC_EDIT_CH_VERSE = 283;
const int ID_TEXT_AVAIL_ADAPT_OR_GLOSS = 284;
const int IDC_LIST_TRANSLATIONS = 285;
extern wxSizer *m_pNumberedPointsStaticBoxSizer;
const int ID_TEXT_CLICK_LISTED = 286;
const int ID_TEXT_CLICK_EDIT_LISTED = 287;
const int ID_TEXT_TYPE_NEW = 288;
const int IDC_CHECK_DO_SAME = 289;
const int ID_BUTTON_IGNORE_IT = 290;
wxSizer *ConsistencyCheckDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_CHECK_OPEN_DOC_ONLY = 291;
const int IDC_RADIO_CHECK_SELECTED_DOCS = 292;
const int ID_TEXTCTRL_MSG = 293;
wxSizer *ChooseConsistencyCheckTypeDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL = 294;
const int IDC_EDIT_OLD_SOURCE_TEXT = 295;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC1 = 296;
const int ID_TEXTCTRL_EDIT_SOURCE_AS_STATIC2 = 297;
const int IDC_EDIT_NEW_SOURCE = 298;
wxSizer *EditSourceTextDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_UNPACK_WARN = 299;
wxSizer *UnpackWarningDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_COUNT = 300;
const int IDC_LIST_SRC_KEYS = 301;
const int IDC_LIST_EXISTING_TRANSLATIONS = 302;
const int IDC_EDIT_EDITORADD = 303;
const int IDC_BUTTON_UPDATE = 304;
const int IDC_BUTTON_ADD = 305;
const int IDC_ADD_NOTHING = 306;
const int IDC_EDIT_SHOW_FLAG = 307;
const int IDC_BUTTON_FLAG_TOGGLE = 308;
const int IDC_EDIT_SRC_KEY = 309;
const int IDC_EDIT_REF_COUNT = 310;
const int ID_TEXTCTRL_SEARCH = 311;
const int ID_BUTTON_GO = 312;
const int ID_BUTTON_ERASE_ALL_LINES = 313;
const int ID_COMBO_OLD_SEARCHES = 314;
wxSizer *KBEditorPanelFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_TEXT_SELECT_A_TAB = 315;
const int ID_STATIC_WHICH_KB = 316;
const int ID_KB_EDITOR_NOTEBOOK = 317;
wxSizer *KBEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_STATIC_DOCS_IN_FOLDER = 318;
const int IDC_LIST_SOURCE_FOLDER_DOCS = 319;
const int IDC_RADIO_TO_BOOK_FOLDER = 320;
const int IDC_RADIO_FROM_BOOK_FOLDER = 321;
const int IDC_VIEW_OTHER = 322;
const int IDC_BUTTON_RENAME_DOC = 323;
const int IDC_MOVE_NOW = 324;
wxSizer *MoveDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_JOIN1 = 325;
const int IDC_BUTTON_MOVE_ALL_RIGHT = 326;
const int IDC_BUTTON_MOVE_ALL_LEFT = 327;
const int ID_TEXTCTRL_AS_STATIC_JOIN2 = 328;
const int ID_TEXTCTRL_AS_STATIC_JOIN3 = 329;
const int ID_JOIN_NOW = 330;
const int IDC_STATIC_JOINING_WAIT = 331;
const int ID_TEXTCTRL_AS_STATIC_JOIN4 = 332;
const int IDC_EDIT_NEW_FILENAME = 333;
wxSizer *JoinDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

wxSizer *ListDocInOtherFolderDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_SET_FONT_TITLE = 334;
const int ID_STATIC_CURR_ENCODING_IS = 335;
const int ID_TEXT_CURR_ENCODING = 336;
const int ID_LISTBOX_POSSIBLE_FACENAMES = 337;
const int ID_LISTBOX_POSSIBLE_ENCODINGS = 338;
extern wxSizer *pTestBoxStaticTextBoxSizer;
const int ID_TEXT_TEST_ENCODING_BOX = 339;
const int ID_BUTTON_CHART_FONT_SIZE_DECREASE = 340;
const int ID_BUTTON_CHART_FONT_SIZE_INCREASE = 341;
const int ID_STATIC_CHART_FONT_SIZE = 342;
const int ID_SCROLLED_ENCODING_WINDOW = 343;
wxSizer *SetEncodingDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_CCT = 344;
wxSizer *CCTableEditDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_LIST_CCTABLES = 345;
const int IDC_EDIT_SELECTED_TABLE = 346;
const int IDC_BUTTON_BROWSE = 347;
const int IDC_BUTTON_CREATE_CCT = 348;
const int IDC_BUTTON_EDIT_CCT = 349;
const int IDC_BUTTON_SELECT_NONE = 350;
const int IDC_EDIT_FOLDER_PATH = 351;
wxSizer *CCTablePageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_SRC_ONLY_FIND = 352;
const int IDC_RADIO_TGT_ONLY_FIND = 353;
const int IDC_RADIO_SRC_AND_TGT_FIND = 354;
const int IDC_CHECK_IGNORE_CASE_FIND = 355;
const int IDC_STATIC_SRC_FIND = 356;
const int IDC_EDIT_SRC_FIND = 357;
const int IDC_STATIC_TGT_FIND = 358;
const int IDC_EDIT_TGT_FIND = 359;
const int IDC_CHECK_INCLUDE_PUNCT_FIND = 360;
const int IDC_CHECK_SPAN_SRC_PHRASES_FIND = 361;
const int IDC_STATIC_SPECIAL = 362;
extern wxSizer *IDC_STATIC_SIZER_SPECIAL;
const int IDC_RADIO_RETRANSLATION = 363;
const int IDC_RADIO_NULL_SRC_PHRASE = 364;
const int IDC_RADIO_SFM = 365;
const int IDC_STATIC_SELECT_MKR = 366;
const int IDC_COMBO_SFM = 367;
const int IDC_BUTTON_SPECIAL = 368;
wxSizer *FindDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_SRC_ONLY_REPLACE = 369;
const int IDC_RADIO_TGT_ONLY_REPLACE = 370;
const int IDC_RADIO_SRC_AND_TGT_REPLACE = 371;
const int IDC_CHECK_IGNORE_CASE_REPLACE = 372;
const int IDC_STATIC_SRC_REPLACE = 373;
const int IDC_EDIT_SRC_REPLACE = 374;
const int IDC_STATIC_TGT_REPLACE = 375;
const int IDC_EDIT_TGT_REPLACE = 376;
const int IDC_CHECK_INCLUDE_PUNCT_REPLACE = 377;
const int IDC_CHECK_SPAN_SRC_PHRASES_REPLACE = 378;
const int IDC_STATIC_REPLACE = 379;
const int IDC_EDIT_REPLACE = 380;
const int IDC_REPLACE = 381;
const int IDC_REPLACE_ALL_BUTTON = 382;
wxSizer *ReplaceDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC = 383;
const int IDC_EDIT_TBLNAME = 384;
wxSizer *CCTableNameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_EDIT_AS_STATIC = 385;
const int ID_CHECKBOX_INCLUDE_FREE_TRANS_TEXT = 386;
const int ID_CHECKBOX_INCLUDE_GLOSSES_TEXT = 387;
const int ID_RADIO_ALL = 388;
const int ID_RADIO_SELECTION = 389;
const int IDC_RADIO_PAGES = 390;
const int IDC_EDIT_PAGES_FROM = 391;
const int IDC_EDIT_PAGES_TO = 392;
const int IDC_RADIO_CHAPTER_VERSE_RANGE = 393;
const int IDC_EDIT3 = 394;
const int IDC_EDIT4 = 395;
const int IDC_CHECK_SUPPRESS_PREC_HEADING = 396;
const int IDC_CHECK_INCLUDE_FOLL_HEADING = 397;
const int IDC_CHECK_SUPPRESS_FOOTER = 398;
wxSizer *PrintOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CC_TABBED_NOTEBOOK = 399;
wxSizer *CCTabbedNotebookFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LIST_UI_LANGUAGES = 400;
const int ID_TEXT_AS_STATIC_SHORT_LANG_NAME = 401;
const int ID_TEXT_AS_STATIC_LONG_LANG_NAME = 402;
const int IDC_LOCALIZATION_PATH = 403;
wxSizer *ChooseLanguageDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_COMBO_REMOVALS = 404;
const int ID_STATIC_TEXT_REMOVALS = 405;
const int IDC_BUTTON_UNDO_LAST_COPY = 406;
wxSizer *RemovalsBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_EDIT_MSG_TEXT = 407;
const int IDC_BUTTON_PREV_STEP = 408;
const int IDC_BUTTON_NEXT_STEP = 409;
const int ID_BUTTON_END_NOW = 410;
const int ID_BUTTON_CANCEL_ALL_STEPS = 411;
wxSizer *VertEditBarFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_TITLE = 412;
const int IDC_TOGGLE_UNNNN_BTN = 413;
const int ID_TEXTCTRL_AS_STATIC_PUNCT_CORRESP_PAGE = 414;
const int IDC_EDIT_SRC0 = 415;
const int IDC_EDIT_TGT0 = 416;
const int IDC_EDIT_SRC1 = 417;
const int IDC_EDIT_TGT1 = 418;
const int IDC_EDIT_SRC2 = 419;
const int IDC_EDIT_TGT2 = 420;
const int IDC_EDIT_SRC3 = 421;
const int IDC_EDIT_TGT3 = 422;
const int IDC_EDIT_SRC4 = 423;
const int IDC_EDIT_TGT4 = 424;
const int IDC_EDIT_SRC5 = 425;
const int IDC_EDIT_TGT5 = 426;
const int IDC_EDIT_SRC6 = 427;
const int IDC_EDIT_TGT6 = 428;
const int IDC_EDIT_SRC7 = 429;
const int IDC_EDIT_TGT7 = 430;
const int IDC_EDIT_SRC8 = 431;
const int IDC_EDIT_TGT8 = 432;
const int IDC_EDIT_SRC9 = 433;
const int IDC_EDIT_TGT9 = 434;
const int IDC_EDIT_SRC10 = 435;
const int IDC_EDIT_TGT10 = 436;
const int IDC_EDIT_SRC11 = 437;
const int IDC_EDIT_TGT11 = 438;
const int IDC_EDIT_SRC12 = 439;
const int IDC_EDIT_TGT12 = 440;
const int IDC_EDIT_SRC13 = 441;
const int IDC_EDIT_TGT13 = 442;
const int IDC_EDIT_SRC14 = 443;
const int IDC_EDIT_TGT14 = 444;
const int IDC_EDIT_SRC15 = 445;
const int IDC_EDIT_TGT15 = 446;
const int IDC_EDIT_SRC16 = 447;
const int IDC_EDIT_TGT16 = 448;
const int IDC_EDIT_SRC17 = 449;
const int IDC_EDIT_TGT17 = 450;
const int IDC_EDIT_SRC18 = 451;
const int IDC_EDIT_TGT18 = 452;
const int IDC_EDIT_SRC19 = 453;
const int IDC_EDIT_TGT19 = 454;
const int IDC_EDIT_SRC20 = 455;
const int IDC_EDIT_TGT20 = 456;
const int IDC_EDIT_SRC21 = 457;
const int IDC_EDIT_TGT21 = 458;
const int IDC_EDIT_SRC22 = 459;
const int IDC_EDIT_TGT22 = 460;
const int IDC_EDIT_SRC23 = 461;
const int IDC_EDIT_TGT23 = 462;
const int IDC_EDIT_SRC24 = 463;
const int IDC_EDIT_TGT24 = 464;
const int IDC_EDIT_SRC25 = 465;
const int IDC_EDIT_TGT25 = 466;
const int IDC_EDIT_2SRC0 = 467;
const int IDC_EDIT_2TGT0 = 468;
const int IDC_EDIT_2SRC1 = 469;
const int IDC_EDIT_2TGT1 = 470;
const int IDC_EDIT_2SRC2 = 471;
const int IDC_EDIT_2TGT2 = 472;
const int IDC_EDIT_2SRC3 = 473;
const int IDC_EDIT_2TGT3 = 474;
const int IDC_EDIT_2SRC4 = 475;
const int IDC_EDIT_2TGT4 = 476;
const int IDC_EDIT_2SRC5 = 477;
const int IDC_EDIT_2TGT5 = 478;
const int IDC_EDIT_2SRC6 = 479;
const int IDC_EDIT_2TGT6 = 480;
const int IDC_EDIT_2SRC7 = 481;
const int IDC_EDIT_2TGT7 = 482;
const int IDC_EDIT_2SRC8 = 483;
const int IDC_EDIT_2TGT8 = 484;
const int IDC_EDIT_2SRC9 = 485;
const int IDC_EDIT_2TGT9 = 486;
wxSizer *PunctCorrespPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_TOP;
extern wxSizer *ID_CONTROLBAR_2_LINE_SIZER_BOTTOM;
wxSizer *ControlBar2LineFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_MSG1 = 487;
const int ID_BUTTON_LOCATE_SOURCE_FOLDER = 488;
const int ID_BITMAPBUTTON_SRC_OPEN_FOLDER_UP = 489;
const int ID_TEXT_SOURCE_FOLDER_PATH = 490;
const int ID_TEXTCTRL_SOURCE_PATH = 491;
const int ID_LISTCTRL_SOURCE_CONTENTS = 492;
const int ID_BUTTON_LOCATE_DESTINATION_FOLDER = 493;
const int ID_BITMAPBUTTON_DEST_OPEN_FOLDER_UP = 494;
const int ID_TEXTCTRL_DESTINATION_PATH = 495;
const int ID_LISTCTRL_DESTINATION_CONTENTS = 496;
const int ID_BUTTON_MOVE = 497;
const int ID_BUTTON_COPY = 498;
const int ID_BUTTON_PEEK = 499;
const int ID_BUTTON_RENAME = 500;
const int ID_BUTTON_DELETE = 501;
wxSizer *MoveOrCopyFilesOrFoldersFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_MSG1 = 502;
const int ID_STATICBITMAP = 503;
const int ID_TEXTCTRL_SOURCE_FILE_DETAILS = 504;
const int ID_TEXTCTRL_DESTINATION_FILE_DETAILS = 505;
const int ID_RADIOBUTTON_REPLACE = 506;
const int ID_RADIOBUTTON_NO_COPY = 507;
const int ID_RADIOBUTTON_COPY_AND_RENAME = 508;
const int ID_TEXT_MODIFY_NAME = 509;
const int ID_CHECKBOX_HANDLE_SAME = 510;
wxSizer *FilenameConflictFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LISTBOX_UPDATED = 511;
const int ID_TEXTCTRL_INFO_SOURCE = 512;
const int ID_TEXTCTRL_INFO_REFS = 513;
const int ID_LISTBOX_MATCHED = 514;
const int ID_BUTTON_UPDATE = 515;
const int ID_TEXTCTRL_LOCAL_SEARCH = 516;
const int ID_BUTTON_FIND_NEXT = 517;
const int ID_TEXTCTRL_EDITBOX = 518;
const int ID_BUTTON_RESTORE = 519;
const int ID_BUTTON_REMOVE_UPDATE = 520;
wxSizer *KBEditSearchFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATICTEXT_SCROLL_LIST = 521;
const int ID_LIST_LANGUAGE_CODES_NAMES = 522;
const int ID_STATICTEXT_SEARCH_FOR_LANG_NAME = 523;
const int ID_TEXTCTRL_SEARCH_LANG_NAME = 524;
const int ID_BUTTON_FIND_CODE = 525;
const int ID_BUTTON_FIND_LANGUAGE = 526;
const int ID_BUTTON_USE_SEL_AS_SRC = 527;
const int ID_BUTTON_USE_SEL_AS_TGT = 528;
const int ID_BUTTON_USE_SEL_AS_GLS = 529;
const int ID_BUTTON_USE_SEL_AS_FRTR = 530;
const int ID_SRC_LANGUAGE_CODE = 531;
const int ID_TGT_LANGUAGE_CODE = 532;
const int ID_GLS_LANGUAGE_CODE = 533;
const int ID_TEXT_FRTR = 534;
const int ID_TEXTCTRL_SRC_LANG_CODE = 535;
const int ID_TEXTCTRL_TGT_LANG_CODE = 536;
const int ID_TEXTCTRL_GLS_LANG_CODE = 537;
const int ID_TEXTCTRL_FRTR_LANG_CODE = 538;
wxSizer *LanguageCodesDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_PEEKMSG = 539;
extern wxSizer *m_pHorizBox_for_textctrl;
const int ID_TEXTCTRL_LINES100 = 540;
const int ID_BUTTON_TOGGLE_TEXT_DIRECTION = 541;
wxSizer *PeekAtFileFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_INSTRUCTIONS = 542;
const int ID_LISTBOX_LOADABLES_FILENAMES = 543;
wxSizer *NewDocFromSourceDataFolderFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_STATIC_SELECT_A_TAB = 544;
const int ID_MENU_EDITOR_NOTEBOOK = 545;
const int ID_RADIOBUTTON_NONE = 546;
const int ID_RADIOBUTTON_USE_PROFILE = 547;
const int ID_COMBO_PROFILE_ITEMS = 548;
const int ID_BUTTON_RESET_TO_FACTORY = 549;
const int ID_TEXT_STATIC_DESCRIPTION = 550;
const int ID_TEXTCTRL_PROFILE_DESCRIPTION = 551;
wxSizer *MenuEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECKLISTBOX_MENU_ITEMS = 552;
wxSizer *MenuEditorPanelFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_RADIO_USE_UBS_SET_ONLY = 553;
const int IDC_RADIO_USE_SILPNG_SET_ONLY = 554;
const int IDC_RADIO_USE_BOTH_SETS = 555;
const int IDC_RADIO_USE_UBS_SET_ONLY_PROJ = 556;
const int IDC_RADIO_USE_SILPNG_SET_ONLY_PROJ = 557;
const int IDC_RADIO_USE_BOTH_SETS_PROJ = 558;
const int IDC_CHECK_CHANGE_FIXED_SPACES_TO_REGULAR_SPACES_USFM = 559;
const int ID_TEXTCTRL_AS_STATIC_FILTERPAGE = 560;
const int IDC_LIST_SFMS_PROJ = 561;
wxSizer *UsfmFilterPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_CHECK_USE_GUESSER = 562;
const int ID_PANEL_GUESS_COLOR_DISPLAY = 563;
const int ID_BUTTON_GUESS_HIGHLIGHT_COLOR = 564;
const int ID_SLIDER_GUESSER = 565;
const int ID_CHECK_ALLOW_GUESSER_ON_UNCHANGED_CC_OUTPUT = 566;
const int ID_TEXT_STATIC_NUM_CORRESP_ADAPTATIONS_GUESSER = 567;
const int ID_TEXT_STATIC_NUM_CORRESP_GLOSSING_GUESSER = 568;
wxSizer *GuesserSettingsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_DEVS_EMAIL_ADDR = 569;
const int ID_TEXTCTRL_MY_EMAIL_ADDR = 570;
const int ID_TEXTCTRL_SUMMARY_SUBJECT = 571;
extern wxSizer *STATIC_TEXT_DESCRIPTION;
const int ID_TEXTCTRL_DESCRIPTION_BODY = 572;
const int ID_TEXTCTRL_SENDERS_NAME = 573;
const int ID_CHECKBOX_LET_DEVS_KNOW_AI_USAGE = 574;
const int ID_BUTTON_VIEW_USAGE_LOG = 575;
const int ID_TEXT_AI_VERSION = 576;
const int ID_TEXT_RELEASE_DATE = 577;
const int ID_TEXT_DATA_TYPE = 578;
const int ID_TEXT_FREE_MEMORY = 579;
const int ID_TEXT_SYS_LOCALE = 580;
const int ID_TEXT_INTERFACE_LANGUAGE = 581;
const int ID_TEXT_SYS_ENCODING = 582;
const int ID_TEXT_SYS_LAYOUT_DIR = 583;
const int ID_TEXT_WXWIDGETS_VERSION = 584;
const int ID_TEXT_OS_VERSION = 585;
const int ID_BUTTON_SAVE_REPORT_AS_TEXT_FILE = 586;
const int ID_BUTTON_LOAD_SAVED_REPORT = 587;
const int ID_RADIOBUTTON_SEND_DIRECTLY_FROM_AI = 588;
const int ID_RADIOBUTTON_SEND_TO_MY_EMAIL = 589;
const int ID_BUTTON_ATTACH_PACKED_DOC = 590;
const int ID_BUTTON_SEND_NOW = 591;
wxSizer *EmailReportDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_LOG_FILE_PATH_AND_NAME = 592;
const int ID_TEXTCTRL_LOGGED_TEXT = 593;
wxSizer *LogViewerFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

extern wxSizer *STATIC_TEXT_PTorBE_PROJECTS;
const int ID_TEXT_SRC_PROJ = 594;
const int ID_STATIC_TEXT_SRC_PROJ = 595;
const int ID_TEXT_TGT_PROJ = 596;
const int ID_STATIC_TEXT_TGT_PROJ = 597;
const int ID_TEXT_FREETRANS_PROJ = 598;
const int ID_STATIC_TEXT_FREETRANS_PROJ = 599;
const int ID_TEXT_AI_PROJ = 600;
const int ID_TEXT_SELECT_A_CHAPTER = 601;
const int ID_LISTBOX_BOOK_NAMES = 602;
const int ID_LISTCTRL_CHAPTER_NUMBER_AND_STATUS = 603;
const int ID_TEXTCTRL_AS_STATIC_NOTE = 604;
const int ID_LINE_1 = 605;
wxSizer *GetSourceTextFromEditorDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_AS_STATIC_TOP_INFO = 606;
const int ID_CHECKBOX_PROTECT_SOURCE_INPUTS = 607;
const int ID_BUTTON_PRE_LOAD_SOURCE_TEXTS = 608;
const int ID_CHECKBOX_PROTECT_FREETRANS_OUTPUTS = 609;
const int ID_CHECKBOX_PROTECT_FREETRANS_RTF_OUTPUTS = 610;
const int ID_CHECKBOX_PROTECT_GLOSS_OUTPUTS = 611;
const int ID_CHECKBOX_PROTECT_GLOSS_RTF_OUTPUTS = 612;
const int ID_CHECKBOX_PROTECT_SOURCE_OUTPUTS = 613;
const int ID_CHECKBOX_PROTECT_SOURCE_RTF_OUTPUTS = 614;
const int ID_CHECKBOX_PROTECT_TARGET_OUTPUTS = 615;
const int ID_CHECKBOX_PROTECT_TARGET_RTF_OUTPUTS = 616;
const int ID_CHECKBOX_PROTECT_REPORTS_OUTPUTS = 617;
const int ID_CHECKBOX_PROTECT_INTERLINEAR_RTF_OUTPUTS = 618;
const int ID_CHECKBOX_PROTECT_XHTML_OUTPUTS = 619;
const int ID_CHECKBOX_PROTECT_PATHWAY_OUTPUTS = 620;
const int ID_CHECKBOX_PROTECT_KB_INPUTS_AND_OUTPUTS = 621;
const int ID_CHECKBOX_PROTECT_LIFT_INPUTS_AND_OUTPUTS = 622;
const int ID_CHECKBOX_PROTECT_PACKED_INPUTS_AND_OUTPUTS = 623;
const int ID_CHECKBOX_PROTECT_CCTABLE_INPUTS_AND_OUTPUTS = 624;
const int ID_BUTTON_UNSELECT_ALL_CHECKBOXES = 625;
const int ID_BUTTON_SELECT_ALL_CHECKBOXES = 626;
wxSizer *AssignLocationsForInputsOutputsFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_SOURCE_PHRASE_1 = 627;
const int ID_TEXT_EMPTY_STR = 628;
const int ID_RADIO_NO_ADAPTATION = 629;
const int ID_RADIO_LEAVE_HOLE = 630;
const int ID_RADIO_NOT_IN_KB = 631;
const int ID_RADIOBUTTON_TYPE_AORG = 632;
const int ID_TEXTCTRL_TYPED_AORG = 633;
const int ID_CHECK_DO_SAME = 634;
wxSizer *ConsistencyCheck_EmptyNoTU_DlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXTCTRL_SOURCE_PHRASE_2 = 635;
const int ID_TEXTCTRL_TARGET_PHRASE_2 = 636;
const int ID_TEXT_EXISTS_STR = 637;
const int ID_RADIO_STORE_NORMALLY = 638;
const int ID_RADIO_NOT_IN_KB_LEAVEINDOC = 639;
const int ID_CHECK_DO_SAME2 = 640;
wxSizer *ConsistencyCheck_ExistsNoTU_DlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_BITMAPBUTTON_MOVE_BACK = 641;
const int ID_BITMAPBUTTON_MOVE_FORWARD = 642;
const int ID_BUTTON_OPEN_HTML_FILE = 643;
const int ID_TEXTCTRL_HTML_FILE_PATH = 644;
const int ID_HTML_WINDOW = 645;
wxSizer *HtmlFileViewerDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_SRC = 646;
const int ID_TEXTCTRL_SRC_LANG = 647;
const int ID_TEXT_NOTCHANGED = 648;
const int ID_TEXT_TGT_CODE = 649;
const int ID_LISTBOX_TGT = 650;
const int ID_TEXT_GLOSS_CODE = 651;
const int ID_LISTBOX_GLOSS = 652;
const int ID_TEXTCTRL_TELL = 653;
const int ID_TEXTCTRL_MSG2 = 654;
wxSizer *LiftLangFilterFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_RADIOBOX_KB_EXPORT_IMPORT_OPTIONS = 655;
extern wxSizer *pKBExpImpCheckBoxesSizer;
wxSizer *KBExportImportOptionsFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_SELECTED_AI_PROJECT = 656;
const int ID_BUTTON_TELL_ME_MORE = 657;
const int ID_RADIOBUTTON_TURN_COLLAB_ON = 658;
const int ID_TEXTCTRL_NOT_INSTALLED_ERROR_MSG = 659;
const int ID_RADIOBUTTON_TURN_COLLAB_OFF = 660;
const int ID_RADIOBUTTON_READ_ONLY_MODE = 661;
wxSizer *ChooseCollabOptionsDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_USE_THIS_DIALOG = 662;
const int ID_COMBO_AI_PROJECTS = 663;
const int ID_BUTTON_CREATE_NEW_AI_PROJECT = 664;
const int ID_TEXT_STATIC_LIST_OF_PROJECTS = 665;
const int ID_RADIOBOX_EXTERNAL_SCRIPTURE_EDITOR = 666;
const int IDC_LIST_OF_COLLAB_PROJECTS = 667;
const int ID_TEXTCTRL_AS_STATIC_TOP_NOTE = 668;
const int ID_TEXT_STATIC_SELECT_WHICH_PROJECTS = 669;
const int ID_TEXT_STATIC_SRC_FROM_THIS_PROJECT = 670;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_SRC_PROJ = 671;
const int ID_BUTTON_SELECT_FROM_LIST_SOURCE_PROJ = 672;
const int ID_RADIO_BY_CHAPTER_ONLY = 673;
const int ID_RADIO_BY_WHOLE_BOOK = 674;
const int ID_TEXT_STATIC_TARGET_TO_THIS_PROJECT = 675;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_TGT_PROJ = 676;
const int ID_BUTTON_SELECT_FROM_LIST_TARGET_PROJ = 677;
const int ID_TEXT_STATIC_TO_THIS_FT_PROJECT = 678;
const int ID_TEXTCTRL_AS_STATIC_SELECTED_FREE_TRANS_PROJ = 679;
const int ID_BUTTON_SELECT_FROM_LIST_FREE_TRANS_PROJ = 680;
const int ID_BUTTON_NO_FREE_TRANS = 681;
const int ID_LINE_2 = 682;
const int ID_BUTTON_SAVE_SETUP_FOR_THIS_PROJ_NOW = 683;
const int ID_BUTTON_REMOVE_THIS_PROJ_FROM_COLLAB = 684;
wxSizer *SetupCollaborationBetweenAIandEditorFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_TOP_INFO_1 = 685;
const int ID_TEXT_TOP_INFO_2 = 686;
const int ID_TEXTCTRL_SRC_LANG_NAME = 687;
const int ID_TEXTCTRL_TGT_LANG_NAME = 688;
const int ID_TEXT_AS_STATIC_NEW_AI_PROJ_NAME = 689;
const int ID_TEXTCTRL_NEW_AI_PROJ_NAME = 690;
wxSizer *CreateNewAIProjForCollabFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT_STATIC_LAST_BOOKNAME = 691;
const int ID_TEXTCTRL_OLD_BOOKNAME = 692;
const int ID_TEXT_STATIC_TOP_MSG = 693;
const int ID_RADIO_USE_LAST_BOOKNAME = 694;
const int ID_RADIO_BOOKNAME_IS_INAPPROPRIATE = 695;
const int ID_RADIO_SUGGESTED_BOOKNAME_ACCEPTABLE = 696;
const int ID_RADIO_DIFFERENT_BOOKNAME = 697;
const int ID_TEXTCTRL_BOOKNAME = 698;
wxSizer *BookNameDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_SPINCTRL_RECEIVE = 699;
const int ID_RADIO_SHARING_OFF = 700;
const int ID_GET_RECENT = 701;
const int ID_GET_ALL = 702;
const int ID_SEND_ALL = 703;
wxSizer *kb_sharing_dlg_func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_SERVER_URL_LABEL = 704;
const int ID_TEXTCTRL_SERVER_URL = 705;
const int ID_TEXT_USERNAME_LABEL = 706;
const int ID_KB_SHARING_REMOVE_SETUP = 707;
wxSizer *kb_sharing_setup_func( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LST_TOOLBAR_BUTTONS = 708;
const int ID_BMP_TOOLBAR_SMALL = 709;
const int ID_BMP_TOOLBAR_MEDIUM = 710;
const int ID_BMP_TOOLBAR_LARGE = 711;
const int ID_RDO_TOOLBAR_SMALL = 712;
const int ID_RDO_TOOLBAR_MEDIUM = 713;
const int ID_RDO_TOOLBAR_LARGE = 714;
const int ID_CBO_TOOLBAR_ICON = 715;
const int ID_BTN_TOOLBAR_MINIMAL = 716;
const int ID_TOOLBAR_RESET = 717;
wxSizer *ToolbarPageFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_BUTTON_CANCEL_ASK = 718;
const int ID_BUTTON_CANCEL_AND_SELECT = 719;
wxSizer *ChooseTranslationDlgFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int IDC_COMMIT_COMMENT = 720;
const int IDC_COMMIT_BLURB = 721;
wxSizer *DVCSDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_COMMITTER = 722;
const int ID_VERSION_DATE = 723;
const int ID_VERSION_COMMENT = 724;
const int ID_BTN_PREV = 725;
const int ID_BTN_NEXT = 726;
const int ID_ACCEPT = 727;
const int ID_LATEST = 728;
wxSizer *DVCSNavDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_LST_VERSIONS = 729;
wxSizer *DVCSLogDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

const int ID_FILE_MENU = 730;
const int ID_SAVE_AS = 731;
const int ID_FILE_PACK_DOC = 732;
const int ID_FILE_UNPACK_DOC = 733;
const int ID_MENU = 734;
const int ID_FILE_STARTUP_WIZARD = 735;
const int ID_FILE_CLOSEKB = 736;
const int ID_FILE_CHANGEFOLDER = 737;
const int ID_FILE_SAVEKB = 738;
const int ID_FILE_BACKUP_KB = 739;
const int ID_FILE_RESTORE_KB = 740;
const int ID_FILE_SAVE_COMMIT = 741;
const int ID_FILE_REVERT_FILE = 742;
const int ID_FILE_LIST_VERSIONS = 743;
const int ID_FILE_TAKE_OWNERSHIP = 744;
const int ID_EDIT_MENU = 745;
const int ID_EDIT_CUT = 746;
const int ID_EDIT_COPY = 747;
const int ID_EDIT_PASTE = 748;
const int ID_GO_TO = 749;
const int ID_EDIT_SOURCE_TEXT = 750;
const int ID_EDIT_CONSISTENCY_CHECK = 751;
const int ID_EDITMENU_CHANGE_PUNCTS_MKRS_PLACE = 752;
const int ID_EDIT_MOVE_NOTE_FORWARD = 753;
const int ID_EDIT_MOVE_NOTE_BACKWARD = 754;
const int ID_VIEW_MENU = 755;
const int ID_VIEW_TOOLBAR = 756;
const int ID_VIEW_STATUS_BAR = 757;
const int ID_VIEW_COMPOSE_BAR = 758;
const int ID_VIEW_MODE_BAR = 759;
const int ID_COPY_SOURCE = 760;
const int ID_MARKER_WRAPS_STRIP = 761;
const int ID_UNITS = 762;
const int ID_CHANGE_INTERFACE_LANGUAGE = 763;
const int ID_VIEW_SHOW_ADMIN_MENU = 764;
const int ID_TOOLS_MENU = 765;
const int ID_TOOLS_DEFINE_CC = 766;
const int ID_UNLOAD_CC_TABLES = 767;
const int ID_USE_CC = 768;
const int ID_ACCEPT_CHANGES = 769;
const int ID_TOOLS_DEFINE_SILCONVERTER = 770;
const int ID_USE_SILCONVERTER = 771;
const int ID_TOOLS_KB_EDITOR = 772;
const int ID_TOOLS_AUTO_CAPITALIZATION = 773;
const int ID_RETRANS_REPORT = 774;
const int ID_TOOLS_SPLIT_DOC = 775;
const int ID_TOOLS_JOIN_DOCS = 776;
const int ID_TOOLS_MOVE_DOC = 777;
const int ID_EXPORT_IMPORT_MENU = 778;
const int ID_FILE_EXPORT_SOURCE = 779;
const int ID_FILE_EXPORT = 780;
const int ID_FILE_EXPORT_TO_RTF = 781;
const int ID_EXPORT_GLOSSES = 782;
const int ID_EXPORT_FREE_TRANS = 783;
const int ID_FILE_EXPORT_KB = 784;
const int ID_IMPORT_TO_KB = 785;
const int ID_MENU_IMPORT_EDITED_SOURCE_TEXT = 786;
const int ID_ADVANCED_MENU = 787;
const int ID_ADVANCED_SEE_GLOSSES = 788;
const int ID_ADVANCED_GLOSSING_USES_NAV_FONT = 789;
const int ID_ADVANCED_TRANSFORM_ADAPTATIONS_INTO_GLOSSES = 790;
const int ID_ADVANCED_DELAY = 791;
const int ID_ADVANCED_BOOKMODE = 792;
const int ID_ADVANCED_FREE_TRANSLATION_MODE = 793;
const int ID_ADVANCED_TARGET_TEXT_IS_DEFAULT = 794;
const int ID_ADVANCED_GLOSS_TEXT_IS_DEFAULT = 795;
const int ID_ADVANCED_REMOVE_FILTERED_FREE_TRANSLATIONS = 796;
const int ID_ADVANCED_COLLECT_BACKTRANSLATIONS = 797;
const int ID_ADVANCED_REMOVE_FILTERED_BACKTRANSLATIONS = 798;
const int ID_ADVANCED_USETRANSLITERATIONMODE = 799;
const int ID_ADVANCED_SENDSYNCHRONIZEDSCROLLINGMESSAGES = 800;
const int ID_ADVANCED_RECEIVESYNCHRONIZEDSCROLLINGMESSAGES = 801;
const int ID_LAYOUT_MENU = 802;
const int ID_ALIGNMENT = 803;
const int ID_HELP_MENU = 804;
const int ID_MENU_AI_QUICK_START = 805;
const int ID_REPORT_A_PROBLEM = 806;
const int ID_GIVE_FEEDBACK = 807;
const int ID_HELP_USE_TOOLTIPS = 808;
const int ID_ADMINISTRATOR_MENU = 809;
const int ID_MENU_HELP_FOR_ADMINISTRATORS = 810;
const int ID_SETUP_EDITOR_COLLABORATION = 811;
const int ID_EDIT_USER_MENU_SETTINGS_PROFILE = 812;
const int ID_MENU_TEMP_TURN_OFF_CURRENT_PROFILE = 813;
const int ID_ASSIGN_LOCATIONS_FOR_INPUTS_OUTPUTS = 814;
const int ID_MOVE_OR_COPY_FOLDERS_OR_FILES = 815;
const int ID_SET_PASSWORD_MENU = 816;
const int ID_CUSTOM_WORK_FOLDER_LOCATION = 817;
const int ID_LOCK_CUSTOM_LOCATION = 818;
const int ID_UNLOCK_CUSTOM_LOCATION = 819;
const int ID_LOCAL_WORK_FOLDER_MENU = 820;
const int ID_DVCS_VERSION = 821;
wxMenuBar *AIMenuBarFunc();

// Declare toolbar functions

const int ID_BUTTON_GUESSER = 822;
const int ID_BUTTON_CREATE_NOTE = 823;
const int ID_BUTTON_PREV_NOTE = 824;
const int ID_BUTTON_NEXT_NOTE = 825;
const int ID_BUTTON_DELETE_ALL_NOTES = 826;
const int ID_BUTTON_RESPECTING_BDRY = 827;
const int ID_BUTTON_SHOWING_PUNCT = 828;
const int ID_BUTTON_TO_END = 829;
const int ID_BUTTON_TO_START = 830;
const int ID_BUTTON_STEP_DOWN = 831;
const int ID_BUTTON_STEP_UP = 832;
const int ID_BUTTON_BACK = 833;
const int ID_BUTTON_MERGE = 834;
const int ID_BUTTON_RETRANSLATION = 835;
const int ID_BUTTON_EDIT_RETRANSLATION = 836;
const int ID_REMOVE_RETRANSLATION = 837;
const int ID_BUTTON_NULL_SRC = 838;
const int ID_BUTTON_REMOVE_NULL_SRCPHRASE = 839;
const int ID_BUTTON_CHOOSE_TRANSLATION = 840;
const int ID_SHOWING_ALL = 841;
const int ID_BUTTON_EARLIER_TRANSLATION = 842;
const int ID_BUTTON_NO_PUNCT_COPY = 843;
void AIToolBarFunc( wxToolBar *parent );

void AIToolBar32x30Func( wxToolBar *parent );

// Declare bitmap functions

wxBitmap AIToolBarBitmapsUnToggledFunc( size_t index );

const int ID_BITMAP_FOLDERAI = 844;
const int ID_BITMAP_FILEAI = 845;
const int ID_BITMAP_EMPTY_FOLDER = 846;
wxBitmap AIMainFrameIcons( size_t index );

const int ID_BUTTON_IGNORING_BDRY = 847;
const int ID_BUTTON_HIDING_PUNCT = 848;
const int ID_SHOWING_TGT = 849;
const int ID_BUTTON_ENABLE_PUNCT_COPY = 850;
wxBitmap AIToolBarBitmapsToggledFunc( size_t index );

wxBitmap WhichFilesBitmapsFunc( size_t index );

wxBitmap AIToolBarBitmapsToggled32x30Func( size_t index );

wxBitmap AIToolBarBitmapsUnToggled32x30Func( size_t index );

wxBitmap HtmlWindowBitmapsFunc( size_t index );

#endif

// End of generated file
